let SouvenirModuleData = [
	{ original: "0",	name: "0",	id: "0",	questions: ["Wie lautete die Startzahl?"] },
	{ original: "The 1, 2, 3 Game",	name: "The 1, 2, 3 Game",	id: "TheOneTwoThreeGame",	questions: ["Was war der Name und Avatar des Gegners?"] },
	{ original: "21",	name: "21",	id: "TwennyWan",	questions: ["Welche Zahl war auf dem Display?"] },
	{ original: "3 LEDs",	name: "3 LEDs",	id: "threeLEDsModule",	questions: ["Wie sahen die LEDs am Anfang aus?"] },
	{ original: "3N+1",	name: "3N+1",	id: "threeNPlusOne",	questions: ["Welche Zahl war am Anfang auf dem Display?"] },
	{ original: "64",	name: "64",	id: "64",	questions: ["Welche Zahl war auf dem Display?"] },
	{ original: "7",	name: "7",	id: "7",	questions: ["Welche Farbe hatten die LEDs in welcher Stufe?", "Was waren die Anfangswerte Farbkanäle?"] },
	{ original: "9-Ball",	name: "9-Ball",	id: "GSNineBall",	questions: ["Welche Zahlen waren auf den Bällen?"] },
	{ original: "Abyss",	name: "Abyss",	id: "GSAbyss",	questions: ["Welche Zeichen waren auf dem Display?"] },
	{ original: "Adventure Game",	name: "Adventure Game",	id: "spwizAdventureGame",	questions: ["Which items were present?"] },
	{ original: "Alfa-Bravo",	name: "Alfa-Bravo",	id: "alfa_bravo",	questions: ["Welcher Buchstabe wurde am Ende eingegeben?", "Welche Buchstaben waren links und rechts vom letzten?", "Welche Ziffer war zuletzt auf dem kleinen Display?"] },
	{ original: "Algebra",	name: "Algebra",	id: "algebra",	questions: ["Was waren die ersten zwei Gleichungen?"] },
	{ original: "Algorithmia",	name: "Algorithmia",	id: "algorithmia",	questions: ["Wo war die Start- und Zielposition?", "Welche Farbe hatte die Glühlampe?", "Welche Zahlen kamen im Seedcode vor?"] },
	{ original: "Alphabetical Ruling",	name: "Alphabetical Ruling",	id: "alphabeticalRuling",	questions: ["Welche Buchstaben und Ziffern kamen in welcher Stufe vor?"] },
	{ original: "Alphabet Numbers",	name: "Alphabet Numbers",	id: "alphabetNumbers",	questions: ["Welche Zahlen waren in welcher Stufe auf den Tasten?"] },
	{ original: "Alpha-Bits",	name: "Alpha-Bits",	id: "alphaBits",	questions: ["Welche Zeichen waren auf den Displays?"] },
	{ original: "Ángel Hernández",	name: "Ángel Hernández",	id: "AngelHernandezModule",	questions: ["Welche Buchstaben wurden in welcher Stufe durch die erhöhten Tasten angedeutet?"] },
	{ original: "Barcode Cipher",	name: "Barcode Cipher",	id: "BarcodeCipherModule",	questions: ["Welche Zahl war auf dem Display?", "Welche Peripherie-Info wurde durch welchen Barcode erfragt?", "Welcher Barcode ergab welche Lösung?"] },
	{ original: "Binary Shift",	name: "Binary Shift",	id: "binary_shift",	questions: ["Was waren die Zahlen am Anfang?", "What number was selected at each stage?"] },
	{ original: "Blinkstop",	name: "Blinkstop",	id: "blinkstopModule",	questions: ["Wie oft hat die LED geblinkt?", "Welche Farbe hat die LED am wenigsten geblinkt?"] },
	{ original: "Blockbusters",	name: "Blockbusters",	id: "blockbusters",	questions: ["What letters were in the leftmost column at the start?"] },
	{ original: "Bob Barks",	name: "Bob Barks",	id: "ksmBobBarks",	questions: ["Welcome Aufschrift hatten die Indikatoren?", "Welche Tasten haben nacheinander geleuchtet?"] },
	{ original: "Boggle",	name: "Boggle",	id: "boggle",	questions: ["Welche Buchstaben waren am Anfang sichtbar?"] },
	{ original: "Bomb Diffusal",	name: "Bomb Diffusal",	id: "bombDiffusal",	questions: ["Was war die Lizenznummer?"] },
	{ original: "Boob Tube",	name: "Boob Tube",	id: "boobTubeModule",	questions: ["Welche Wörter kamen vor?"] },
	{ original: "Book of Mario",	name: "Book of Mario",	id: "BookOfMarioModule",	questions: ["Wer hat in welcher Stufe was gesagt?", "Was war das Zitat welcher Figur?"] },
	{ original: "Bordered Keys",	name: "Bordered Keys",	id: "borderedKeys",	questions: ["Was war beim Druck auf die Tasten deren Rahmenfarbe, Displayziffer, Tastenfarbe, Aufschrift und Aufschriftfarbe?"] },
	{ original: "Bottom Gear",	name: "Bottom Gear",	id: "GSBottomGear",	questions: ["Welcher Tweet war am Anfang zu sehen?"] },
	{ original: "Boxing",	name: "Boxing",	id: "boxing",	questions: ["Welche Kandidaten und Ersatzpersonen kamen vor (Vor- und Nachnamen)?", "Wer hatte welche Schlagstärke?"] },
	{ original: "Braille",	name: "Braille",	id: "BrailleModule",	questions: ["Welche Braille-Muster kamen vor?"] },
	{ original: "CA-RPS",	name: "CA-RPS",	id: "caRPS",	questions: ["Was waren die Farben am Anfang?"] },
	{ original: "Catchphrase",	name: "Catchphrase",	id: "catchphrase",	questions: ["Welche Blende hatte welche Farbe?"] },
	{ original: "Challenge & Contact",	name: "Challenge & Contact",	id: "challengeAndContact",	questions: ["Welche Buchstaben kamen vor?"] },
	{ original: "↻↺",	name: "↻↺",	id: "clockCounter",	questions: ["Welche Pfeile kamen vor?"] },
	{ original: "Codenames",	name: "Codenames",	id: "codenames",	questions: ["Welche Wörter wurden eingegeben?"] },
	{ original: "Coffeebucks",	name: "Coffeebucks",	id: "coffeebucks",	questions: ["Was war beim letzten Kunden der bevorzugte Zuckergehalt, die Tageszeit, das Stressniveau und die Größe?"] },
	{ original: "Color Addition",	name: "Color Addition",	id: "colorAddition",	questions: ["Was waren die drei Zahlen?"] },
	{ original: "Color One Two",	name: "Color One Two",	id: "colorOneTwo",	questions: ["Welche Farbe hatten die LEDs?"] },
	{ original: "DetoNATO",	name: "DetoNATO",	id: "Detonato",	questions: ["Was war in welcher Stufe auf dem Display?"] },
	{ original: "Digisibility",	name: "Digisibility",	id: "digisibility",	questions: ["Welche Zahlen waren auf den Tasten?"] },
	{ original: "Digit String",	name: "Digit String",	id: "digitString",	questions: ["Wie lautete die Ziffernfolge auf dem Display?"] },
	{ original: "Disordered Keys",	name: "Disordered Keys",	id: "disorderedKeys",	questions: ["Was war bei welcher Taste die enthüllte/verborgene Tastenfarbe, Aufschrift, Aufschriftfarbe und fehlende Information?"] },
	{ original: "Earthbound",	name: "Earthbound",	id: "EarthboundModule",	questions: ["Was war der Hintergrund?", "Welches Monster war zu sehen?"] },
	{ original: "eeB gnillepS",	name: "eeB gnillepS",	id: "eeBgnilleps",	questions: ["Die Schreibweise welches Wortes wurde verlangt?"] },
	{ original: "Emoji",	name: "Emoji",	id: "emoji",	questions: ["Welche Emojis kamen vor?"] },
	{ original: "English Entries",	name: "English Entries",	id: "EnglishEntries",	questions: ["Welches Zitat war auf dem Display?"] },
	{ original: "Etterna",	name: "Etterna",	id: "etterna",	questions: ["Welcher Beat wurde für welchen Pfeil eingegeben?"] },
	{ original: "FizzBuzz",	name: "FizzBuzz",	id: "fizzBuzzModule",	questions: ["Welche Zahlen waren auf den Displays?"] },
	{ original: "Forget’s Ultimate Showdown",	name: "Forget’s Ultimate Showdown",	id: "ForgetsUltimateShowdownModule",	questions: ["Was war die Zahl am Anfang?", "Was war die Zahl unten?", "Was war die Lösung?", "Welche Verschlüsselungsmethoden kamen zum Einsatz?"] },
	{ original: "The Gamepad",	name: "The Gamepad",	id: "TheGamepadModule",	questions: ["Welche Zahlen kamen vor?"] },
	{ original: "Garfield Kart",	name: "Garfield Kart",	id: "garfieldKart",	questions: ["Welchen Namen hatte die Rennstrecke?", "Wie viele Puzzleteile waren zu sehen?"] },
	{ original: "h",	name: "h",	id: "Averageh",	questions: ["Welcher Buchstabe wurde übermittelt?"] },
	{ original: "Halli Galli",	name: "Halli Galli",	id: "halliGalli",	questions: ["Which fruit was there five of and in what counts?"] },
	{ original: "Hereditary Base Notation",	name: "Hereditary Base Notation",	id: "hereditaryBaseNotationModule",	questions: ["Welche Zahl war auf dem unteren Display?"] },
	{ original: "hexOrbits",	name: "hexOrbits",	id: "hexOrbits",	questions: ["Welche Formen waren auf dem Display?"] },
	{ original: "hexOS",	name: "hexOS",	id: "hexOS",	questions: ["Wie lautete die entschlüsselte Botschaft (Buchstaben oder Phrase)?", "Welche 3-stelligen Zahlen kamen auf dem Display vor?", "Welche Rhythmuswerte kamen vor?"] },
	{ original: "Hogwarts",	name: "Hogwarts",	id: "HogwartsModule",	questions: ["Welches Modul wurde für welches Haus entschärft?"] },
	{ original: "Hold Ups",	name: "Hold Ups",	id: "KritHoldUps",	questions: ["Welchen Namen hatte welcher Schatten?"] },
	{ original: "The Hypercube",	name: "The Hypercube",	id: "TheHypercubeModule",	questions: ["Welche Rotationen kamen vor?"] },
	{ original: "HyperForget",	name: "HyperForget",	id: "HyperForget",	questions: ["Welche Rotationen kamen vor?"] },
	{ original: "IPA",	name: "IPA",	id: "ipa",	questions: ["Was war das richtige Zeichen?"] },
	{ original: "Jenga",	name: "Jenga",	id: "jenga",	questions: ["Welche Symbole waren auf dem ersten korrekt gezogenen Stein?"] },
	{ original: "Kanji",	name: "Kanji",	id: "KanjiModule",	questions: ["Welches Wort wurde in welcher Stufe abgefragt?"] },
	{ original: "KayMazey Talk",	name: "KayMazey Talk",	id: "KMazeyTalk",	questions: ["Was war das Start- und Zielwort?"] },
	{ original: "Kudosudoku",	name: "Kudosudoku",	id: "KudosudokuModule",	questions: ["Welche Felder waren am Anfang schon ausgefüllt?"] },
	{ original: "Kugelblitz",	name: "Kugelblitz",	id: "kugelblitz",	questions: ["Welche Partikel waren in welcher Stufe vorhanden?", "Welche Werte hatten die Partikel in welcher Stufe?"] },
	{ original: "Kuro",	name: "Kuro",	id: "Kuro",	questions: ["Welche Stimmung hatte Kuro?"] },
	{ original: "LEDs",	name: "LEDs",	id: "leds",	questions: ["Welche Farbe hatte die LED, die sich verändert hat?"] },
	{ original: "Linq",	name: "Linq",	id: "Linq",	questions: ["Welche Funktionen kamen vor?"] },
	{ original: "The London Underground",	name: "The London Underground",	id: "londonUnderground",	questions: ["Welche Haltestelle war Start und Ziel?"] },
	{ original: "Mad Memory",	name: "Mad Memory",	id: "MadMemory",	questions: ["Was war in welcher Stufe auf dem Display?"] },
	{ original: "Mafia",	name: "Mafia",	id: "MafiaModule",	questions: ["Wer war Mitspieler, aber nicht der Pate?"] },
	{ original: "Mahjong",	name: "Mahjong",	id: "MahjongModule",	questions: ["Welcher Spielstein war unten links zu sehen?"] },
	{ original: "Main Page",	name: "Main Page",	id: "mainpage",	questions: ["Welche Farbe und Botschaft war (nicht) auf der Blase sichtbar?", "Von welcher Hauptseite war Homestar, der Hintergrund und die Effekte der Tasten?"] },
	{ original: "M&Ms",	name: "M&Ms",	id: "MandMs",	questions: ["Welche Taste hatte welche Aufschrift und in welcher Farbe?"] },
	{ original: "M&Ns",	name: "M&Ns",	id: "MandNs",	questions: ["Welche Taste hatte eine Aufschrift in welcher Farbe?", "Welche Aufschrift hatte die korrekte Taste?"] },
	{ original: "Mashematics",	name: "Mashematics",	id: "mashematics",	questions: ["Welche Zahlen kamen in der Rechenaufgabe vor?"] },
	{ original: "Master Tapes",	name: "Master Tapes",	id: "masterTape",	questions: ["Welcher Song war zu hören?"] },
	{ original: "Match Refereeing",	name: "Match Refereeing",	id: "matchRefereeing",	questions: ["Welche Planeten kamen in welcher Stufe vor?"] },
	{ original: "Math ’em",	name: "Math ’em",	id: "mathem",	questions: ["Welche Farbe und welches Design hatten die Steine vorm Mischen?"] },
	{ original: "The Matrix",	name: "The Matrix",	id: "matrix",	questions: ["Welches Wort kam im letzten Zugangscode vor?", "Wie lautete das gestörte Wort?"] },
	{ original: "Maze",	name: "Maze",	id: "Maze",	questions: ["Wo war die Startposition?"] },
	{ original: "Maze³",	name: "Maze³",	id: "maze3",	questions: ["Welche Farbe war auf der Startfläche?"] },
	{ original: "Maze Identification",	name: "Maze Identification",	id: "GSMazeIdentification",	questions: ["Was war der Seedcode?", "Welche Taste hatte welche Funktion?"] },
	{ original: "Mazematics",	name: "Mazematics",	id: "mazematics",	questions: ["Was war der Start- und Zielwert?"] },
	{ original: "Maze Scrambler",	name: "Maze Scrambler",	id: "MazeScrambler",	questions: ["Wo war die Startposition?", "Wo war die Zielposition?", "Wo waren die Markierungen?"] },
	{ original: "Mazeseeker",	name: "Mazeseeker",	id: "GSMazeseeker",	questions: ["Welche Position war von wie vielen Wänden umgeben?", "Wo war die Start- und Zielposition?"] },
	{ original: "Maze Swap",	name: "Maze Swap",	id: "mazeSwap",	questions: ["Wo war die Start- und Zielposition?"] },
	{ original: "Memorable Buttons",	name: "Memorable Buttons",	id: "memorableButtons",	questions: ["Welche Symbole waren auf den korrekten Tasten?"] },
	{ original: "Memory",	name: "Memory",	id: "Memory",	questions: ["Welche Ziffer war in welcher Stufe auf dem Display?"] },
	{ original: "Memory Wires",	name: "Memory Wires",	id: "memoryWires",	questions: ["Welche Farbe hatten die Drähte?", "Welche Ziffern waren auf dem Display?"] },
	{ original: "Metamorse",	name: "Metamorse",	id: "metamorse",	questions: ["Welcher Buchstabe wurde entnommen?"] },
	{ original: "Metapuzzle",	name: "Metapuzzle",	id: "metapuzzle",	questions: ["Was war das Lösungswort am Ende?"] },
	{ original: "Minsk Metro",	name: "Minsk Metro",	id: "minskMetro",	questions: ["An welcher Haltestelle ging es los?"] },
	{ original: "Mister Softee",	name: "Mister Softee",	id: "misterSoftee",	questions: ["Wo war das Spongebob-Eis?", "Welche Eissorten waren im Angebot?"] },
	{ original: "Mixometer",	name: "Mixometer",	id: "mixometer",	questions: ["Wo war die Eingabetaste?"] },
	{ original: "Module Listening",	name: "Module Listening",	id: "moduleListening",	questions: ["Welche Sounds waren zu hören?", "Welche Sounds wurden durch welche Taste ausgelöst?"] },
	{ original: "Module Maze",	name: "Module Maze",	id: "ModuleMaze",	questions: ["Was war das Startsymbol?"] },
	{ original: "Module Movements",	name: "Module Movements",	id: "moduleMovements",	questions: ["Welches Modul kam in welcher Stufe vor?"] },
	{ original: "Money Game",	name: "Money Game",	id: "MoneyGame",	questions: ["Welche Phrasen kamen vor?"] },
	{ original: "Monsplode, Fight!",	name: "Monsplode, Fight!",	id: "monsplodeFight",	questions: ["Welche Kreatur war auf dem Display?", "Welche Züge waren auswählbar?"] },
	{ original: "Monsplode Trading Cards",	name: "Monsplode Trading Cards",	id: "monsplodeCards",	questions: ["Welche Namen und Druckversionen hatten die drei Karten auf der Hand vor der letzten Aktion?"] },
	{ original: "The Moon",	name: "The Moon",	id: "moon",	questions: ["Welche Richtungen haben am Anfang geleuchtet und welche nicht?"] },
	{ original: "More Code",	name: "More Code",	id: "MoreCode",	questions: ["Welches Wort wurde übermittelt?"] },
	{ original: "Morse-A-Maze",	name: "Morse-A-Maze",	id: "MorseAMaze",	questions: ["Wo waren die Start- und Zielposition?", "Welches Wort wurde in Morsezeichen übermittelt?"] },
	{ original: "Morse Buttons",	name: "Morse Buttons",	id: "morseButtons",	questions: ["Welche Zeichen wurden von welchen Tasten in welchen Farben übermittelt?"] },
	{ original: "Morse War",	name: "Morse War",	id: "MorseWar",	questions: ["Welche LEDs waren an/aus?", "Welcher Code wurde übermittelt?"] },
	{ original: "M-Seq",	name: "M-Seq",	id: "mSeq",	questions: ["Wie lauteten die ermittelten Ziffern?", "Was war die letzte Ziffer aus dem Iterationsprozess?"] },
	{ original: "Mystery Module",	name: "Mystery Module",	id: "mysterymodule",	questions: ["Welches Modul war versteckt?", "Die Entschärfung welches Moduls wurde als erstes verlangt?"] },
	{ original: "Mystic Square",	name: "Mystic Square",	id: "MysticSquareModule",	questions: ["Welche Ziffer war am Anfang in der Mitte?"] },
	{ original: "Name Codes",	name: "Name Codes",	id: "nameCodes",	questions: ["Wie weit war der Links- und Rechtsschritt?"] },
	{ original: "Naming Conventions",	name: "Naming Conventions",	id: "NamingConventions",	questions: ["Was stand auf der ersten Taste?"] },
	{ original: "N&Ms",	name: "N&Ms",	id: "NandMs",	questions: ["Welche Aufschrift hatte die korrekte Taste?"] },
	{ original: "N&Ns",	name: "N&Ns",	id: "NandNs",	questions: ["Welche Beschriftungen kamen in Stufe 2 und 3 vor?", "Welche Farbe hat in Stufe 3 gefehlt?"] },
	{ original: "Navigation Determination",	name: "Navigation Determination",	id: "NavigationDeterminationModule",	questions: ["Welche Farbe und Beschriftung hatte das Labyrinth?"] },
	{ original: "Negativity",	name: "Negativity",	id: "Negativity",	questions: ["Welcher Wert wurde eingegeben (im Dezimal- und im balancierten Ternärsystem)?"] },
	{ original: "Neptune",	name: "Neptune",	id: "neptune",	questions: ["Welcher Stern war auf dem Display?"] },
	{ original: "Neutralization",	name: "Neutralization",	id: "neutralization",	questions: ["Welche Farbe und welches Volumen hatte die Säure?"] },
	{ original: "Next In Line",	name: "Next In Line",	id: "NextInLine",	questions: ["Welche Farbe hatte der erste Draht?"] },
	{ original: "Nim",	name: "Nim",	id: "nim",	questions: ["Welche Reihe hatte wie viele Streichhölzer?"] },
	{ original: "❖",	name: "❖",	id: "nonverbalSimon",	questions: ["Was hat geblinkt?"] },
	{ original: "Object Shows",	name: "Object Shows",	id: "objectShows",	questions: ["Welche Kandidaten kamen vor?"] },
	{ original: "The Octadecayotton",	name: "The Octadecayotton",	id: "TheOctadecayotton",	questions: ["Bei welcher Kugel ging es los?", "Welche Transformation bestand aus welchen Teiltransformationen?"] },
	{ original: "Only Connect",	name: "Only Connect",	id: "OnlyConnectModule",	questions: ["Welche ägyptische Hieroglyphe war an welcher Stelle?"] },
	{ original: "Orange Arrows",	name: "Orange Arrows",	id: "orangeArrowsModule",	questions: ["Welche Pfeile waren in welcher Stufe unter den ersten drei?"] },
	{ original: "Ordered Keys",	name: "Ordered Keys",	id: "orderedKeys",	questions: ["In welcher Stufe hatte welche Taste welche Farbe, Aufschrift und Aufschriftfarbe?"] },
	{ original: "Pickup Identification",	name: "Pickup Identification",	id: "PickupIdentification",	questions: ["Welche Pickups waren zu sehen?"] },
	{ original: "Pictionary",	name: "Pictionary",	id: "pictionaryModule",	questions: ["Wie lautete der Code?"] },
	{ original: "Pie",	name: "Pie",	id: "pieModule",	questions: ["Welche Ziffern waren zu sehen?"] },
	{ original: "Pie Flash",	name: "Pie Flash",	id: "pieFlash",	questions: ["Welche Zahlen waren auf dem Display?"] },
	{ original: "Pinpoint",	name: "Pinpoint",	id: "pinpoint",	questions: ["Wie lauteten die Punktkoordinaten und Abstände?"] },
	{ original: "Placeholder Talk",	name: "Placeholder Talk",	id: "placeholderTalk",	questions: ["Wie lautete die gesamte erste Phrase?", "Welcher Wert wurde für die zweite Phrase berechnet?"] },
	{ original: "Puzzle Identification",	name: "Puzzle Identification",	id: "GSPuzzleIdentification",	questions: ["Welches Rätsel war aus welchem Spiel?", "Welches Rätsel hatte welchen Namen und welche Nummer?"] },
	{ original: "Q & A",	name: "Q & A",	id: "q&a",	questions: ["Welche Fragen wurden gestellt?"] },
	{ original: "Quaver",	name: "Quaver",	id: "Quaver",	questions: ["Welche Folge hatte welche Lösung?"] },
	{ original: "Quiplash",	name: "Quiplash",	id: "QLModule",	questions: ["Welche Zahl war auf dem Display?"] },
	{ original: "Quiz Buzz",	name: "Quiz Buzz",	id: "quizBuzz",	questions: ["Welche Zahl war am Anfang auf dem Display?"] },
	{ original: "Qwirkle",	name: "Qwirkle",	id: "qwirkle",	questions: ["Welche Steine wurden platziert?"] },
	{ original: "ReGret-B Filtering",	name: "ReGret-B Filtering",	id: "regretbFiltering",	questions: ["Welche Berechnungen kamen vor?"] },
	{ original: "Robot Programming",	name: "Robot Programming",	id: "robotProgramming",	questions: ["Welcher Roboter hatte welche Form und welche Farbe?"] },
	{ original: "Roger",	name: "Roger",	id: "roger",	questions: ["Wie lautete die vorgegebene 4-stellige Zahl?"] },
	{ original: "RPS Judging",	name: "RPS Judging",	id: "RPSJudging",	questions: ["In welcher Runde war unentschieden bzw. wer gewann/verlor?"] },
	{ original: "Saturn",	name: "Saturn",	id: "saturn",	questions: ["Wo war das Ziel?"] },
	{ original: "Schlag den Bomb",	name: "Schlag den Bomb",	id: "qSchlagDenBomb",	questions: ["Wie lauteten beide Punktzahlen sowie der Name des Kandidaten?"] },
	{ original: "Sea Shells",	name: "Sea Shells",	id: "SeaShells",	questions: ["Welche Phrasen kamen vor?"] },
	{ original: "Simon Smothers",	name: "Simon Smothers",	id: "simonSmothers",	questions: ["Welche Farben und Richtungen haben in welcher Stufe aufgeleuchtet?"] },
	{ original: "Simon Sounds",	name: "Simon Sounds",	id: "simonSounds",	questions: ["Welche Probetaste entsprach dem Geräusch in welcher Stufe?"] },
	{ original: "Simon Speaks",	name: "Simon Speaks",	id: "SimonSpeaksModule",	questions: ["Was waren die relevanten Merkmale der aufleuchtenden Sprechblasen?"] },
	{ original: "Simon Stacks",	name: "Simon Stacks",	id: "simonstacks",	questions: ["Which colors flashed in each stage?"] },
	{ original: "Simon Stops",	name: "Simon Stops",	id: "simonStops",	questions: ["Welche Farben kamen in der vorgegebenen Farbfolge vor?"] },
	{ original: "Simon Stores",	name: "Simon Stores",	id: "simonStores",	questions: ["Was war am Ende die Farbfolge?"] },
	{ original: "Simon Subdivides",	name: "Simon Subdivides",	id: "simonSubdivides",	questions: ["Welche zerteilte Zelle hatte welche Farbe?"] },
	{ original: "Simon Supports",	name: "Simon Supports",	id: "simonSupports",	questions: ["Wie lauteten die drei Themen?"] },
	{ original: "Simon Swizzles",	name: "Simon Swizzles",	id: "simonSwizzles",	questions: ["Wo waren AN und AUS?", "Wie lautete die versteckte Binärzahl?"] },
	{ original: "Simply Simon",	name: "Simply Simon",	id: "simplysimon",	questions: ["Which colors flashed in each stage?"] },
	{ original: "Simultaneous Simons",	name: "Simultaneous Simons",	id: "simultaneousSimons",	questions: ["Welche Farben haben auf welchem Simon aufgeleuchtet?"] },
	{ original: "Skewed Slots",	name: "Skewed Slots",	id: "SkewedSlotsModule",	questions: ["Wie lauteten die Ziffern am Anfang?"] },
	{ original: "Skewers",	name: "Skewers",	id: "Skewers",	questions: ["Welche Farbe hatte welcher Edelstein?"] },
	{ original: "Skyrim",	name: "Skyrim",	id: "skyrim",	questions: ["Welche Rassen, Waffen, Gegner, Städte und Drachenrufe waren auswählbar, aber nicht Teil der Lösung?"] },
	{ original: "Small Circle",	name: "Small Circle",	id: "smallCircle",	questions: ["Um wie viele Stellen verschob sich die Folge?", "Welcher Sektor löste am Anfang das abweichende Geräusch aus?", "Welche Farben kamen in der Lösung vor?"] },
	{ original: "Small Talk",	name: "Small Talk",	id: "SmallTalk",	questions: ["Welche Wörter standen auf dem Display?"] },
	{ original: "Smash, Marry, Kill",	name: "Smash, Marry, Kill",	id: "smashmarrykill",	questions: ["Welches Modul war in welcher Kategorie?"] },
	{ original: "Snooker",	name: "Snooker",	id: "snooker",	questions: ["Wie viele Roten gab es am Anfang?"] },
	{ original: "Snowflakes",	name: "Snowflakes",	id: "snowflakes",	questions: ["Welche Schneeflocken waren zu sehen?"] },
	{ original: "Sonic & Knuckles",	name: "Sonic & Knuckles",	id: "sonicKnuckles",	questions: ["Welcher Monitor und welcher Bösewicht war zu sehen?"] },
	{ original: "Sonic the Hedgehog",	name: "Sonic the Hedgehog",	id: "sonic",	questions: ["Welcher Bildschirm löste welchen Sound aus?", "Welche Bilder kamen vor?"] },
	{ original: "Sorting",	name: "Sorting",	id: "sorting",	questions: ["Welche Positionen waren am letzten Tausch beteiligt?"] },
	{ original: "Souvenir",	name: "Souvenir",	id: "SouvenirModule",	questions: ["Von welchem Modul handelte die erste Frage auf dem anderen Souvenir?"] },
	{ original: "Space Traders",	name: "Space Traders",	id: "space_traders",	questions: ["Was war der Steuerhöchstbetrag pro Raumschiff?"] },
	{ original: "Spelling Bee",	name: "Spelling Bee",	id: "spellingBee",	questions: ["Die Schreibweise welches Wortes wurde verlangt?"] },
	{ original: "Spongebob Birthday Identification",	name: "Spongebob Birthday Identification",	id: "spongebobBirthdayIdentification",	questions: ["Welche Namen wurden eingegeben?"] },
	{ original: "Subbly Jubbly",	name: "Subbly Jubbly",	id: "subblyJubbly",	questions: ["Wie lauteten die Ersatzphrasen?"] },
	{ original: "Subscribe to Pewdiepie",	name: "Subscribe to Pewdiepie",	id: "subscribeToPewdiepie",	questions: ["Wie viele Abonnenten hatten Pewdiepie und T-Series?"] },
	{ original: "Subway",	name: "Subway",	id: "subway",	questions: ["Welches Brot wurde vom Kunden verlangt?", "Welche Zutat wurde nicht verlangt?"] },
	{ original: "Suits and Colours",	name: "Suits and Colours",	id: "GSSuitsAndColours",	questions: ["Welche Zelle hatte welche Farbe/Kartenfarbe?"] },
	{ original: "Superparsing",	name: "Superparsing",	id: "superparsing",	questions: ["Welches Wort war auf dem Display?"] },
	{ original: "SUSadmin",	name: "SUSadmin",	id: "susadmin",	questions: ["Welche Sicherheitsprotokolle waren installiert?", "Wie lautete die Versionsnummer?"] },
	{ original: "Switching Maze",	name: "Switching Maze",	id: "MazeSwitching",	questions: ["Was war der Seedcode?", "Welche Farbe hatte das Startlabyrinth?"] },
	{ original: "Symbol Cycle",	name: "Symbol Cycle",	id: "SymbolCycleModule",	questions: ["Auf welchem Display wurden wie viele Symbole angezeigt?"] },
	{ original: "Symbolic Coordinates",	name: "Symbolic Coordinates",	id: "symbolicCoordinates",	questions: ["Which symbols were present in each stage?"] },
	{ original: "Synapse Says",	name: "Synapse Says",	id: "synapseSays",	questions: ["Welche Zahl war in welcher Stufe zu sehen?", "Welche Farbe war in welcher Stufe an welcher Stelle?", "Welche Farben haben in welcher Stufe aufgeleuchtet?"] },
	{ original: "SYNC-125 [3]",	name: "SYNC-125 [3]",	id: "sync125_3",	questions: ["Was war in welcher Stufe auf dem Display?"] },
	{ original: "Synonyms",	name: "Synonyms",	id: "synonyms",	questions: ["Welche Zahl war auf dem Display?"] },
	{ original: "Sysadmin",	name: "Sysadmin",	id: "sysadmin",	questions: ["Welcher Fehlercode wurde korrigiert?"] },
	{ original: "TAC",	name: "TAC",	id: "TACModule",	questions: ["Welche Karten wurden ausgetauscht?", "Welche Karten waren in der Hand?"] },
	{ original: "Tasha Squeals",	name: "Tasha Squeals",	id: "tashaSqueals",	questions: ["Welche Farben leuchteten auf?"] },
	{ original: "Tasque Managing",	name: "Tasque Managing",	id: "tasqueManaging",	questions: ["Wo war die Startposition?"] },
	{ original: "Tetriamonds",	name: "Tetriamonds",	id: "tetriamonds",	questions: ["Wie lautete die pulsierende Farbfolge?"] },
	{ original: "Text Field",	name: "Text Field",	id: "TextField",	questions: ["Welcher Buchstabe kam vor?"] },
	{ original: "Thinking Wires",	name: "Thinking Wires",	id: "thinkingWiresModule",	questions: ["Welcher Draht musste als erster durchtrennt werden?", "Welche Farbe hatte der zweite korrekt durchtrennte Draht?", "Welche Zahl war auf dem Display?"] },
	{ original: "Third Base",	name: "Third Base",	id: "ThirdBase",	questions: ["Welche Wörter standen auf dem Display?"] },
	{ original: "Thirty Dollar Module",	name: "Thirty Dollar Module",	id: "ThirtyDollarModule",	questions: ["Welche Sounds kamen vor?"] },
	{ original: "Time Signatures",	name: "Time Signatures",	id: "timeSignatures",	questions: ["In welchen Takten wurde gespielt?"] },
	{ original: "Timezone",	name: "Timezone",	id: "timezone",	questions: ["Wie lauteten die Abfahrts- und Ankunftsstadt?"] },
	{ original: "Tip Toe",	name: "Tip Toe",	id: "TipToe",	questions: ["Welche Felder in Reihe 9 und 10 waren sicher?"] },
	{ original: "Topsy Turvy",	name: "Topsy Turvy",	id: "topsyTurvy",	questions: ["Welches Wort war am Anfang auf dem Display?"] },
	{ original: "Touch Transmission",	name: "Touch Transmission",	id: "touchTransmission",	questions: ["Welches Wort wurde übermittelt?", "In welcher Reihenfolge wurde das Braille gelesen?"] },
	{ original: "Toxic Crystals",	name: "Toxic Crystals",	id: "ToxicCrystals",	questions: ["Welcher Buchstabe stand beim Entschärfen auf dem Gehäuse?"] },
	{ original: "Transmitted Morse",	name: "Transmitted Morse",	id: "transmittedMorseModule",	questions: ["Welche Nachrichten wurden übertragen?"] },
	{ original: "Triamonds",	name: "Triamonds",	id: "triamonds",	questions: ["Wie lautete die pulsierende Farbfolge?"] },
	{ original: "Tribal Council",	name: "Tribal Council",	id: "TribalCouncil",	questions: ["Welche Namen waren im Nordosten und Südwesten?"] },
	{ original: "The Ultracube",	name: "The Ultracube",	id: "TheUltracubeModule",	questions: ["Welche Rotationen kamen vor?"] },
	{ original: "UltraStores",	name: "UltraStores",	id: "UltraStores",	questions: ["Welche Rotationen kamen vor?"] },
	{ original: "Unfair Cipher",	name: "Unfair Cipher",	id: "unfairCipher",	questions: ["Wie lautete die verschlüsselte Nachricht?"] },
	{ original: "Unicode",	name: "Unicode",	id: "UnicodeModule",	questions: ["Welche Codes wurden eingegeben?"] },
	{ original: "UNO!",	name: "UNO!",	id: "UNO",	questions: ["Was war die Startkarte?"] },
	{ original: "Unordered Keys",	name: "Unordered Keys",	id: "unorderedKeys",	questions: ["In welcher Stufe hatte welche Taste welche Farbe, Aufschrift und Aufschriftfarbe?"] },
	{ original: "Updog",	name: "Updog",	id: "Updog",	questions: ["Welches Wort war auf dem Display?", "Welche Farben haben aufgeleuchtet?"] },
	{ original: "V",	name: "V",	id: "V",	questions: ["Welche Wörter kamen vor?"] },
	{ original: "Vcrcs",	name: "Vcrcs",	id: "VCRCS",	questions: ["Welches Wort war auf dem Display?"] },
	{ original: "WASD",	name: "WASD",	id: "wasdModule",	questions: ["What was the displayed location?"] },
	{ original: "What’s on Second",	name: "What’s on Second",	id: "WhatsOnSecond",	questions: ["Was stand in welcher Stufe auf dem Display und in welcher Farbe?"] },
	{ original: "WhoOF",	name: "WhoOF",	id: "whoOF",	questions: ["Was war in welcher Stufe auf dem Display?"] },
	{ original: "Who’s on First",	name: "Who’s on First",	id: "WhosOnFirst",	questions: ["Welche Wörter standen auf dem Display?"] },
	{ original: "Who’s on Gas",	name: "Who’s on Gas",	id: "whosOnGas",	questions: ["Was war in welcher Stufe während der ersten Phase auf dem Display?"] },
	{ original: "Who’s on Morse",	name: "Who’s on Morse",	id: "whosOnMorseModule",	questions: ["Welches Wort wurde in welcher Stufe übermittelt?"] },
	{ original: "Wumbo",	name: "Wumbo",	id: "wumbo",	questions: ["Welche Zahl kam vor?"] },
	{ original: "X-Ring",	name: "X-Ring",	id: "xring",	questions: ["Welche Symbole wurden gescannt?"] },
	{ original: "X-Rotor",	name: "X-Rotor",	id: "xrotor",	questions: ["Welche Symbole wurden gescannt?"] },
	{ original: "Zoni",	name: "Zoni",	id: "lgndZoni",	questions: ["Welche Wörter kamen vor?"] },
	{ original: "Épelle-moi Ça",	name: "Épelle-moi Ça",	id: "epelleMoiCa",	questions: ["Die Schreibweise welches Wortes wurde verlangt?"] },
	{ original: ".--/---/..-.",	name: ".--/.../.-/-../-.-",	id: "morseWoF",	questions: ["Welche Wörter standen auf dem Display?"] },
	{ original: "100 Levels of Defusal",	name: "100 Ebenen der Entschärfung",	id: "100LevelsOfDefusal",	questions: ["Welche Buchstaben kamen vor?"] },
	{ original: "1000 Words",	name: "1000 Wörter",	id: "OneThousandWords",	questions: ["Welche Wörter kamen vor?"] },
	{ original: "1D Chess",	name: "1D-Schach",	id: "1DChess",	questions: ["Welche Züge haben der Spieler und Rustmate gemacht?"] },
	{ original: "3D Tap Code",	name: "3D-Klopfzeichen",	id: "3DTapCodeModule",	questions: ["Welches Wort wurde übermittelt?"] },
	{ original: "3D Maze",	name: "3D-Labyrinth",	id: "spwiz3DMaze",	questions: ["Was waren die Markierungen?", "Was war die Himmelsrichtung?"] },
	{ original: "3D Tunnels",	name: "3D-Tunnel",	id: "3dTunnels",	questions: ["Welche Symbole waren die Ziele?"] },
	{ original: "4D Tunnels",	name: "4D-Tunnel",	id: "4dTunnels",	questions: ["Welche Symbole waren die Ziele?"] },
	{ original: "A Letter",	name: "A Buachstob",	id: "LetterModule",	questions: ["Welcher Buchstabe war am Anfang auf dem Display?"] },
	{ original: "A Message",	name: "A Nachricht",	id: "AMessage",	questions: ["What was the received message?"] },
	{ original: "A Square",	name: "A Quadrat",	id: "ASquareModule",	questions: ["Was waren die Indexfarben?", "Welche Farben wurden eingegeben?"] },
	{ original: "Eight",	name: "Acht",	id: "eight",	questions: ["Welche Ziffer war zuletzt auf dem kleinen Display?", "An welcher Stelle war die letzte kaputte Ziffer?", "Was waren die letzten Ergebnisziffern?", "Welche Zahl war zuletzt auf dem Display?"] },
	{ original: "Affine Cycle",	name: "Affine Schiffer",	id: "affineCycle",	questions: ["In welche Richtung zeigten die Drehknöpfe?", "Was stand auf den Drehknöpfen?"] },
	{ original: "State of Aggregation",	name: "Aggregatzustand",	id: "stateOfAggregation",	questions: ["Welches Element war zu sehen?"] },
	{ original: "Chord Qualities",	name: "Akkordqualität",	id: "ChordQualities",	questions: ["Welche Noten kamen im vorgegebenen Akkord vor?"] },
	{ original: "Accumulation",	name: "Akkumulator",	id: "accumulation",	questions: ["Welche Stufe hatte welche Hintergrundfarbe?", "Was war die Rahmenfarbe?"] },
	{ original: "Burglar Alarm",	name: "Alarmanlage",	id: "burglarAlarm",	questions: ["Welche Ziffern waren auf dem Display?"] },
	{ original: "Burger Alarm",	name: "Alarmbeilage",	id: "burgerAlarm",	questions: ["Welche Ziffern waren auf dem Display?", "Was waren die Bestellnummern?"] },
	{ original: "Alphabet Tiles",	name: "Alphabet-Kacheln",	id: "AlphabetTiles",	questions: ["Welche Buchstaben kamen in welchem Zyklus vor?", "Welcher Buchstabe hat gefehlt?"] },
	{ original: "Old AI",	name: "Alte KI",	id: "SCP079",	questions: ["Welche Bedingung haben die Zahlen auf dem Display befolgt?"] },
	{ original: "Old Fogey",	name: "Alter Kauz",	id: "oldFogey",	questions: ["Welche Farbe hatte am Anfang das Modullämpchen?"] },
	{ original: "Elder Futhark",	name: "Älteres Futhark",	id: "elderFuthark",	questions: ["Welche Runen waren zu sehen?"] },
	{ original: "Alcoholic Rampage",	name: "Amoksauf",	id: "alcoholicRampageModule",	questions: ["Welche Söldner wurden angezeigt?"] },
	{ original: "Working Title",	name: "Arbeitstitel",	id: "workingTitle",	questions: ["What was the label shown?"] },
	{ original: "Arithmetic Cipher",	name: "Arithmetik-Geheimschrift",	id: "ArithmeticCipherModule",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Arithmelogic",	name: "Arithmologik",	id: "arithmelogic",	questions: ["Welches Symbol war auf der Eingabetaste?"] },
	{ original: "Dr. Doctor",	name: "Arztpraxis",	id: "DrDoctorModule",	questions: ["Welche Krankheiten und Symptome kamen vor?"] },
	{ original: "ASCII Maze",	name: "ASCII-Labyrinth",	id: "asciiMaze",	questions: ["Welche Zeichen kamen vor?"] },
	{ original: "Audio Morse",	name: "Audio-Morse",	id: "lgndAudioMorse",	questions: ["Was war der Morsecode?"] },
	{ original: "Bakery",	name: "Bäckerei",	id: "bakery",	questions: ["Was stand auf dem Menü?"] },
	{ original: "Railway Cargo Loading",	name: "Bahnfrachtverladung",	id: "RailwayCargoLoading",	questions: ["Welche Waggons wurden gekoppelt?", "Welche Frachtregeln in der Tabelle trafen zu?"] },
	{ original: "Bar Charts",	name: "Balkendiagramme",	id: "GSBarCharts",	questions: ["Welche Höhe, Farbe und Beschriftung hatten die Balken?", "Was war die Kategorie?", "Was war die Einheit?"] },
	{ original: "Bartending",	name: "Bartender",	id: "BartendingModule",	questions: ["Welche Zutat war an welcher Stelle?"] },
	{ original: "Conditional Buttons",	name: "Bedingte Knöpfe",	id: "conditionalButtons",	questions: ["What was the color of each button?"] },
	{ original: "Splitting The Loot",	name: "Beute Aufteilen",	id: "SplittingTheLootModule",	questions: ["Welcher Sack war am Anfang bereits gefärbt?"] },
	{ original: "Binary",	name: "Binär-LEDs",	id: "Binary",	questions: ["Welches Wort war auf dem Display?"] },
	{ original: "Bitmaps",	name: "Bitmap",	id: "BitmapsModule",	questions: ["Wie viele Pixel waren in welchem Quadranten schwarz bzw. weiß?"] },
	{ original: "Blue Cipher",	name: "Blaue Geheimschrift",	id: "blueCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Blue Huffman Cipher",	name: "Blaue Huffman-Geheimschrift",	id: "BlueHuffmanCipherModule",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Blue Arrows",	name: "Blaue Pfeile",	id: "blueArrowsModule",	questions: ["Welche Zeichen waren auf dem Display?"] },
	{ original: "Blind Maze",	name: "Blinder Irrgarten",	id: "BlindMaze",	questions: ["Welche Farbe hatten die Tasten?"] },
	{ original: "Blindfolded Yahtzee",	name: "Blindes Kniffel",	id: "GSBlindfoldedYahtzee",	questions: ["Welche Würfelergebnisse hat das Modul behauptet?"] },
	{ original: "Flashing Lights",	name: "Blinkende Lichter",	id: "flashingLights",	questions: ["Welche LED hat wie oft in welcher Farbe geblinkt?"] },
	{ original: "Blinking Notes",	name: "Blinkende Noten",	id: "blinkingNotes",	questions: ["Welches Lied war zu hören?"] },
	{ original: "Flashing Arrows",	name: "Blinkende Pfeile",	id: "flashingArrowsModule",	questions: ["What was the number shown on the display?", "Welche Farbe hatten die maßgeblichen Pfeile?"] },
	{ original: "Beans",	name: "Bohnen",	id: "beans",	questions: ["Welche Farbe hatten die gegessenen Bohnen?", "Welche Bohnen haben gewackelt?"] },
	{ original: "Bean Sprouts",	name: "Bohnensprossen",	id: "beanSprouts",	questions: ["Welche Farbe hatten die gegessenen Sprosse?", "Wo befanden sich die gegessenen Bohnen?"] },
	{ original: "Bone Apple Tea",	name: "Bonner Partie",	id: "boneAppleTea",	questions: ["Welche Phrasen kamen vor?"] },
	{ original: "Boolean Wires",	name: "Boolesche Drähte",	id: "booleanWires",	questions: ["Welche Operatoren wurden in welcher Stufe eingegeben?"] },
	{ original: "Boomtar the Great",	name: "Boomtar der Große",	id: "boomtarTheGreat",	questions: ["Was waren die erste und zweite Regel?"] },
	{ original: "Brown Cipher",	name: "Braune Geheimschrift",	id: "brownCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Letter Math",	name: "Buchstaben-Mathe",	id: "letterMath",	questions: ["Welche Buchstaben waren auf dem Display?"] },
	{ original: "Literal Maze",	name: "Buchstäbliches Labyrinth",	id: "literalMaze",	questions: ["Welcher Buchstabe stand an welcher Stelle?"] },
	{ original: "Cartinese",	name: "Cartinesisch",	id: "cartinese",	questions: ["Welcher Songtext wurde durch welche Taste abgespielt?", "Welche Taste hatte welche Farbe?"] },
	{ original: "Caesar Psycho",	name: "Cäsar-Psycho",	id: "caesarPsycho",	questions: ["Was stand in welcher Stufe auf dem oberen Display, und in welcher Farbe?"] },
	{ original: "Caesar Cycle",	name: "Cäsar-Schiffer",	id: "caesarCycle",	questions: ["In welche Richtung zeigten die Drehknöpfe?", "Was stand auf den Drehknöpfen?"] },
	{ original: "Caesar’s Maths",	name: "Cäsars Mathe",	id: "caesarsMaths",	questions: ["What were the colors of each LED?"] },
	{ original: "Chinese Counting",	name: "Chinesisch Zählen",	id: "chineseCounting",	questions: ["Welche Farbe hatten die LEDs?"] },
	{ original: "Chinese Remainder Theorem",	name: "Chinesischer Restsatz",	id: "ChineseRemainderTheoremModule",	questions: ["Wie lauteten die Gleichungen?"] },
	{ original: "Cream Cipher",	name: "Creme-Geheimschrift",	id: "creamCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "DACH Maze",	name: "DACH-Irrgarten",	id: "DACH",	questions: ["In welcher Region ging es los?"] },
	{ original: "The iPhone",	name: "Das iPhone",	id: "iPhone",	questions: ["Wie lautete die PIN?"] },
	{ original: "The Klaxon",	name: "Das Klaxon",	id: "klaxon",	questions: ["Welches Modul hat als erstes den Klaxon losgetreten?"] },
	{ original: "The Samsung",	name: "Das Samsung",	id: "theSamsung",	questions: ["Welche App war an welcher Stelle?"] },
	{ original: "The Tea Set",	name: "Das Teeservice",	id: "GSTeaSet",	questions: ["In welcher Reihenfolge wurden die Zutaten angezeigt?"] },
	{ original: "Find The Date",	name: "Datumsfindung",	id: "DateFinder",	questions: ["Welcher Tag, Monat und Jahr kam in welcher Stufe vor?"] },
	{ original: "Faulty Buttons",	name: "Defekte Knöpfe",	id: "GSFaultyButtons",	questions: ["Welche Taste bezog sich auf welche?"] },
	{ original: "Faulty RGB Maze",	name: "Defektes RGB-Labyrinth",	id: "faultyrgbMaze",	questions: ["Wo im Labyrinth waren der Ausgang und die Schlüssel?", "Welches Labyrinth hatte welche Nummer?"] },
	{ original: "Denial Displays",	name: "Dementi-Displays",	id: "DenialDisplaysModule",	questions: ["Was war am Anfang auf den Displays?"] },
	{ original: "The Azure Button",	name: "Der Azurfarbene Knopf",	id: "AzureButtonModule",	questions: ["Was waren T und die restlichen angezeigten Karten?", "Was war M?", "Welche Pfeile kamen vor?"] },
	{ original: "The Blue Button",	name: "Der Blaue Knopf",	id: "BlueButtonModule",	questions: ["Was waren D, E, F, G, H, M, N, P, Q und X?"] },
	{ original: "The Code",	name: "Der Code",	id: "theCodeModule",	questions: ["Welche Zahl war auf dem Display?"] },
	{ original: "The Wire",	name: "Der Draht",	id: "wire",	questions: ["Welche Farbe hatten die Drehregler?", "Welche Zahl war auf dem Display?"] },
	{ original: "The Missing Letter",	name: "Der Fehlende Buchstabe",	id: "theMissingLetter",	questions: ["Welcher Buchstabe hat gefehlt?"] },
	{ original: "The French Republican Calendar",	name: "Der Französische Revolutionskalender",	id: "FrenchRepublicanCalendar",	questions: ["Welche Farbe hatte die LED?"] },
	{ original: "The Yellow Button",	name: "Der Gelbe Knopf",	id: "YellowButtonModule",	questions: ["Welche Farben kamen vor?"] },
	{ original: "The Glitched Button",	name: "Der Gestörte Knopf",	id: "GlitchedButtonModule",	questions: ["Wie lautete die zyklische Bitfolge?"] },
	{ original: "The Garnet Thief",	name: "Der Granatdieb",	id: "theGarnetThief",	questions: ["Welche Fraktion hat welcher Kandidat behauptet, gewählt zu haben?"] },
	{ original: "The Gray Button",	name: "Der Graue Knopf",	id: "GrayButtonModule",	questions: ["Welche Koordinaten waren auf dem Display?"] },
	{ original: "The Green Button",	name: "Der Grüne Knopf",	id: "GreenButtonModule",	questions: ["Welches Wort wurde eingegeben?"] },
	{ original: "The Hexabutton",	name: "Der Hexaknopf",	id: "hexabutton",	questions: ["Welche Farbe hatte die Taste beim Gedrückthalten?", "Welcher Buchstabe wurde als Morsezeichen übermittelt?"] },
	{ original: "The Hyperlink",	name: "Der Hyperlink",	id: "hyperlink",	questions: ["Wie lautete der Hyperlink?", "Auf welches Modul wurde Bezug genommen?"] },
	{ original: "The Labyrinth",	name: "Der Irrgarten",	id: "labyrinth",	questions: ["Wo waren auf welcher Ebene die Portale?"] },
	{ original: "The Maroon Button",	name: "Der Kastanienknopf",	id: "MaroonButtonModule",	questions: ["Was war A?"] },
	{ original: "The Button",	name: "Der Knopf",	id: "BigButton",	questions: ["In welcher Farbe leuchtete der Streifen?"] },
	{ original: "Not the Button",	name: "Der Knopf Mal Anders",	id: "NotButton",	questions: ["In welcher Farbe leuchtete der Streifen?"] },
	{ original: "Not The Plunger Button",	name: "Der Kolbenknopf Mal Anders",	id: "notPlungerButtonModule",	questions: ["In welchen Farben leuchtete der Hintergrund?"] },
	{ original: "The Navy Button",	name: "Der Königsblaue Knopf",	id: "NavyButtonModule",	questions: ["Welche griechischen Buchstaben kamen vor?", "Welche Koordinaten und welchen Wert hatte die vorgegebene Stelle?"] },
	{ original: "The Necronomicon",	name: "Der Königsblaue Knopf",	id: "necronomicon",	questions: ["Welche Kapitelnummer stand auf welcher Seite?"] },
	{ original: "The Purple Button",	name: "Der Lilane Knopf",	id: "PurpleButtonModule",	questions: ["Welche Zahlen kamen in der zyklischen Folge vor?"] },
	{ original: "The Pink Button",	name: "Der Pinkfarbene Knopf",	id: "PinkButtonModule",	questions: ["Welche Wörter waren auf dem Display und in welcher Farbe?"] },
	{ original: "The Switch",	name: "Der Schalter",	id: "BigSwitch",	questions: ["Welche Farbe hatten die LEDs?"] },
	{ original: "The Deck of Many Things",	name: "Der Stapel Vieler Dinge",	id: "deckOfManyThings",	questions: ["Zu welchem Deck gehörte die erste Karte?"] },
	{ original: "The Cyan Button",	name: "Der Türkise Knopf",	id: "CyanButtonModule",	questions: ["Where was the button at each stage?"] },
	{ original: "The Hidden Value",	name: "Der Versteckte Wert",	id: "theHiddenValue",	questions: ["Welche Zahlen und Farben waren auf dem Display?"] },
	{ original: "The Cube",	name: "Der Würfel",	id: "cube",	questions: ["Was waren die Würfelrotationen?"] },
	{ original: "The Xenocryst",	name: "Der Xenokrist",	id: "GSXenocryst",	questions: ["Welche Farbe leuchtete wann auf?"] },
	{ original: "The Arena",	name: "Die Arena",	id: "TheArena",	questions: ["Was war die höchste Waffenstärke in der Angriffsphase?", "Welche Gegner kamen in der Verteidigungsphase vor?", "Welche Zahlen kamen in der Greifphase vor?"] },
	{ original: "The cRule",	name: "Die CRegel",	id: "the_cRule",	questions: ["Welche Zellen waren am Anfang vorgegeben?", "Welches Symbolpaar erschien wo?"] },
	{ original: "The Duck",	name: "Die Ente",	id: "theDuck",	questions: ["Welche Farbe hatte der Vorhang?", "Wie wurde auf die Ente zugegangen?"] },
	{ original: "The Bulb",	name: "Die Glühlampe",	id: "TheBulbModule",	questions: ["War die Glühlampe am Anfang an?"] },
	{ original: "Not The Bulb",	name: "Die Glühlampe Mal Anders",	id: "notTheBulb",	questions: ["Welches Wort wurde übermittelt?"] },
	{ original: "The Great Void",	name: "Die Große Leere",	id: "greatVoid",	questions: ["Welche Ziffern und Farben kamen vor?"] },
	{ original: "The High Score",	name: "Die Highscore",	id: "ksmHighScore",	questions: ["An welcher Stelle war der Spieler mit welcher Punktzahl?"] },
	{ original: "The Kanye Encounter",	name: "Die Kanye-Begegnung",	id: "TheKanyeEncounter",	questions: ["Welche Nahrungsmittel kamen vor?"] },
	{ original: "The Sphere",	name: "Die Kugel",	id: "sphere",	questions: ["Welche Farben leuchteten auf?"] },
	{ original: "The Rule",	name: "Die Regel",	id: "theRule",	questions: ["Welche Nummer hatte die Regel?"] },
	{ original: "Not The Screw",	name: "Die Schraube Mal Anders",	id: "notTheScrew",	questions: ["Wo war die Startposition?"] },
	{ original: "Dimension Disruption",	name: "Dimensionsspaltung",	id: "dimensionDisruption",	questions: ["Welche Zeichen waren sichtbar?"] },
	{ original: "DNA Mutation",	name: "DNA-Mutation",	id: "DNAMutation",	questions: ["Welche Farbe hatten die DNA-Stränge?", "Welche Buchstaben und Farben hatten die vorgegebenen Nukleotide?"] },
	{ original: "Doofenshmirtz Evil Inc.",	name: "Doofenshmirtz Gesellschaft mit böswilliger Haftung",	id: "doofenshmirtzEvilIncModule",	questions: ["Welcher Jingle war zu hören?", "Welche Bilder waren zu sehen?"] },
	{ original: "Double Screen",	name: "Doppel-Display",	id: "doubleScreenModule",	questions: ["What colors were the screens in each stage?"] },
	{ original: "Not Double-Oh",	name: "Doppel-Null Mal Anders",	id: "NotDoubleOhModule",	questions: ["Welche Positionen waren in der zweiten Stufe auf dem Display?"] },
	{ original: "Double Expert",	name: "Doppelexperte",	id: "doubleExpert",	questions: ["What was the starting key number?"] },
	{ original: "Double Color",	name: "Doppelfarben",	id: "doubleColor",	questions: ["Welche Farbe hatte das Display in welcher Stufe?"] },
	{ original: "Double Arrows",	name: "Doppelpfeile",	id: "doubleArrows",	questions: ["Wo war die Startposition?", "Welche Tasten entsprachen welchen Bewegungsrichtungen?"] },
	{ original: "Double Listening",	name: "Doppelt Zuhören",	id: "doubleListening",	questions: ["Welche Sounds waren zu hören?"] },
	{ original: "Double Digits",	name: "Doppelziffern",	id: "doubleDigitsModule",	questions: ["Welche Zahlen waren auf den Displays?"] },
	{ original: "Wire Ordering",	name: "Draht-Reihenfolge",	id: "kataWireOrdering",	questions: ["Welche Farben und Zahlen waren auf dem Display?", "Welche Farbe hatten die Drähte?"] },
	{ original: "Wire Sequence",	name: "Drahtfolge",	id: "WireSequence",	questions: ["Wie viele Drähte gab es von jeder Farbe?"] },
	{ original: "Rule of Three",	name: "Dreierregel",	id: "RuleOfThreeModule",	questions: ["In welchem Zyklus hatte welche Kugel welche Position auf welcher Achse?", "Welche Koordinaten hatten die Eckpunkte?"] },
	{ original: "Triple Term",	name: "Dreifachbegriff",	id: "tripleTermModule",	questions: ["Wie lauteten die Passwörter?"] },
	{ original: "Stupid Slots",	name: "Dummer Automat",	id: "stupidSlots",	questions: ["Welcher Pfeil hatte welchen Wert?"] },
	{ original: "Corners",	name: "Ecken",	id: "CornersModule",	questions: ["Welche Farbe hatten die Ecken?"] },
	{ original: "Off-White Cipher",	name: "Eierschalengeheimschrift",	id: "offWhiteCipher",	questions: ["Was war auf welchem Display?"] },
	{ original: "One Links To All",	name: "Ein Link Für Alle",	id: "oneLinksToAllModule",	questions: ["Welche Artikel waren am Anfang zu sehen?"] },
	{ original: "Silly Slots",	name: "Einarmiger Bandit",	id: "SillySlots",	questions: ["Welche Symbole erschienen in welcher Stufe?"] },
	{ original: "Entry Number One",	name: "Eintrag Nummer Eins",	id: "GSEntryNumberOne",	questions: ["What were the numbers shown?"] },
	{ original: "Entry Number Four",	name: "Eintrag Nummer Vier",	id: "GSEntryNumberFour",	questions: ["What were the numbers shown?"] },
	{ original: "Ice Cream",	name: "Eiscreme",	id: "iceCreamModule",	questions: ["Welche Kunden kamen vor?", "Welche Geschmacksrichtungen wurden welchen Kunden angeboten?"] },
	{ original: "Infinite Loop",	name: "Endlosschleife",	id: "InfiniteLoop",	questions: ["What was the selected word?"] },
	{ original: "Enigma Cycle",	name: "Enigma-Schiffer",	id: "enigmaCycle",	questions: ["In welche Richtung zeigten die Drehknöpfe?", "Was stand auf den Drehknöpfen?"] },
	{ original: "Decolored Squares",	name: "Entfärbte Felder",	id: "DecoloredSquaresModule",	questions: ["Welche Farben bestimmten die Startzeile und -spalte?"] },
	{ original: "Decolour Flash",	name: "Entfärbte Folge",	id: "DecolourFlashModule",	questions: ["Welches Ziel hatte welches Wort und welche Farbe?"] },
	{ original: "Exoplanets",	name: "Exoplaneten",	id: "exoplanets",	questions: ["What were the starting and final target planet and digit?"] },
	{ original: "ƎNA Cipher",	name: "ƎNA-Chiffre",	id: "enaCipher",	questions: ["Was war das Schlüsselwort, der Umstellungsschlüssel und das verschlüsselte Wort?"] },
	{ original: "Factory Maze",	name: "Fabriklabyrinth",	id: "factoryMaze",	questions: ["In welchem Raum ging es los?"] },
	{ original: "Factoring Maze",	name: "Faktorlabyrinth",	id: "factoringMaze",	questions: ["Welche Primzahlen kamen zum Einsatz?"] },
	{ original: "Color Braille",	name: "Farbbraille",	id: "ColorBrailleModule",	questions: ["Welche Farbe hatten die Punkte?"] },
	{ original: "Color Decoding",	name: "Farbdekodierung",	id: "Color Decoding",	questions: ["Welche Muster und Farben hatten die Indikatoren in welcher Stufe?"] },
	{ original: "Watching Paint Dry",	name: "Farbe Beim Trocknen Zusehen",	id: "watchingPaintDry",	questions: ["Wie viele Pinselstriche gab es?"] },
	{ original: "Varicolour Flash",	name: "Farbenfrohe Folge",	id: "varicolourFlash",	questions: ["Welches Ziel hatte welches Wort und welche Farbe?"] },
	{ original: "Colors Maximization",	name: "Farbmaximierung",	id: "colors_maximization",	questions: ["Wie viele Tasten gab es in welcher Farbe?"] },
	{ original: "Faerie Fires",	name: "Feenfeuer",	id: "FaerieFiresModule",	questions: ["Welche Farbe und Tonhöhe hatten die Feen?"] },
	{ original: "Mssngv Wls",	name: "Fehlender Vokal",	id: "MssngvWls",	questions: ["Welcher Vokal hat gefehlt?"] },
	{ original: "Error Codes",	name: "Fehlercodes",	id: "errorCodes",	questions: ["Welcher Fehlercode war aktiv?"] },
	{ original: "Character Slots",	name: "Figurenkabinett",	id: "characterSlots",	questions: ["Wer war in welcher Stufe in welchem Fensterchen zu sehen?"] },
	{ original: "Flags",	name: "Flaggen",	id: "FlagsModule",	questions: ["Welche Flaggen waren vorhanden, was war die Hauptflagge und die Ziffer auf dem Display?"] },
	{ original: "Vexillology",	name: "Flaggenkunde",	id: "vexillology",	questions: ["Welche Farben hatte die Fahnenstange?"] },
	{ original: "Flavor Text EX",	name: "Flairtext EX",	id: "FlavorTextCruel",	questions: ["Der Würztext welches Moduls kamen in welcher Stufe vor?"] },
	{ original: "Flyswatting",	name: "Fliegenschlagen",	id: "flyswatting",	questions: ["Welche Fliegen waren vorhanden aber nicht Teil der Lösung?"] },
	{ original: "Follow Me",	name: "Folge Mir",	id: "FollowMe",	questions: ["Welche Richtungen haben aufgeleuchtet?"] },
	{ original: "The Sequencyclopedia",	name: "Folgenzyklopädie",	id: "TheSequencyclopedia",	questions: ["Welche Folge kam vor?"] },
	{ original: "Shapes And Bombs",	name: "Formen und Bomben",	id: "ShapesBombs",	questions: ["Was war der Startbuchstabe?"] },
	{ original: "Shape Shift",	name: "Formfluss",	id: "shapeshift",	questions: ["Welche Form war am Anfang da?"] },
	{ original: "Question Mark",	name: "Fragezeichen",	id: "Questionmark",	questions: ["Welche Symbole wurden übermittelt?"] },
	{ original: "Free Parking",	name: "Frei Parken",	id: "freeParking",	questions: ["Welcher Spielstein kam vor?"] },
	{ original: "Pigpen Cycle",	name: "Freimaurer-Schiffer",	id: "pigpenCycle",	questions: ["In welche Richtung zeigten die Drehknöpfe?", "Was stand auf den Drehknöpfen?"] },
	{ original: "Dialtones",	name: "Freizeichen",	id: "xelDialtones",	questions: ["Welche Töne waren zu hören?"] },
	{ original: "Amusement Parks",	name: "Freizeitparks",	id: "amusementParks",	questions: ["Welche Attraktionen standen zur Auswahl?"] },
	{ original: "Girlfriend",	name: "Freundin",	id: "Girlfriend",	questions: ["Welche Sprache war ausgewählt?"] },
	{ original: "Breakfast Egg",	name: "Frühstücksei",	id: "breakfastEgg",	questions: ["Welche Farben waren auf dem Ei?"] },
	{ original: "Functions",	name: "Funktionen",	id: "qFunctions",	questions: ["Was war die letzte Ziffer des ersten Anfrageergebnisses?", "Welche Zahlen und welcher Buchstabe standen unten?"] },
	{ original: "Gadgetron Vendor",	name: "Gadgetron-Verkäufer",	id: "lgndGadgetronVendor",	questions: ["Welche Waffen wurden angezeigt?"] },
	{ original: "Safety Square",	name: "Gefahrendiamant",	id: "safetySquare",	questions: ["Welche Ziffern waren auf dem Display?", "Was war die Spezialregel?"] },
	{ original: "Prison Break",	name: "Gefängnisausbruch",	id: "prisonBreak",	questions: ["Wo ging es für den Gefangenen und den Entschärfer los?"] },
	{ original: "Colored Squares",	name: "Gefärbte Felder",	id: "ColoredSquaresModule",	questions: ["Welche Farbe hatte die erste Eingabe?"] },
	{ original: "Not Colored Squares",	name: "Gefärbte Felder Mal Anders",	id: "NotColoredSquaresModule",	questions: ["Welche Position wurde als erste eingegeben?"] },
	{ original: "Colour Flash",	name: "Gefärbte Folge",	id: "ColourFlash",	questions: ["Welche Farbe hatte das letzte Wort in der Sequenz?"] },
	{ original: "Not Colour Flash",	name: "Gefärbte Folge Mal Anders",	id: "notColourFlash",	questions: ["Welche Wort- und Farbfolgen kamen vor?"] },
	{ original: "Color Morse",	name: "Gefärbte Morsezeichen",	id: "ColorMorseModule",	questions: ["Welche Farbe hatten die LEDs?", "Welche Zeichen wurden über die LEDs geblinkt?"] },
	{ original: "Juxtacolored Squares",	name: "Gefärbte Nachbarfelder",	id: "JuxtacoloredSquaresModule",	questions: ["Welches Feld hatte welche Farbe?"] },
	{ original: "Colored Switches",	name: "Gefärbte Schalter",	id: "ColoredSwitchesModule",	questions: ["Wie standen die Schalter am Anfang?"] },
	{ original: "Not Colored Switches",	name: "Gefärbte Schalter Mal Anders",	id: "NotColoredSwitchesModule",	questions: ["Wie lautete das verschlüsselte Wort?"] },
	{ original: "Colored Keys",	name: "Gefärbte Tasten",	id: "lgndColoredKeys",	questions: ["Welches Wort war auf dem Display und in welcher Farbe?", "Welche Farben und Buchstaben waren auf den Tasten?"] },
	{ original: "Coloured Cubes",	name: "Gefärbte Würfel",	id: "ColouredCubes",	questions: ["In welcher Stufe hatte der Würfel und der Stufenanzeiger welche Farbe?"] },
	{ original: "Coloured Cylinder",	name: "Gefärbter Zylinder",	id: "colouredCylinder",	questions: ["In welcher Farbe blinkten die Zylinder?"] },
	{ original: "Ghost Movement",	name: "Geisterbewegung",	id: "ghostMovement",	questions: ["Wo waren Pac-Man und die Geister?"] },
	{ original: "Yellow Cipher",	name: "Gelbe Geheimschrift",	id: "yellowCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Yellow Huffman Cipher",	name: "Gelbe Huffman-Geheimschrift",	id: "YellowHuffmanCipherModule",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Yellow Arrows",	name: "Gelbe Pfeile",	id: "yellowArrowsModule",	questions: ["Welcher Buchstabe entsprach der Startreihe?"] },
	{ original: "Yellow Button’t",	name: "Gelber Knopf Mal Anders",	id: "yellowbuttont",	questions: ["Wie lautete der Dateiname?"] },
	{ original: "Stacked Sequences",	name: "Gestapelte Folgen",	id: "stackedSequences",	questions: ["Wie lang waren die Folgen?"] },
	{ original: "Divided Squares",	name: "Geteilte Kacheln",	id: "DividedSquaresModule",	questions: ["Welche Farbe erschien, als das korrekte Quadrat betätigt wurde?"] },
	{ original: "Light Bulbs",	name: "Glühlampen",	id: "LightBulbs",	questions: ["Welche Glühlampe hatte welche Farbe?"] },
	{ original: "Goofy’s Game",	name: "Goofys Spiel",	id: "goofysgame",	questions: ["Welche Zahlen wurden als Morsezeichen übermittelt?"] },
	{ original: "Gray Cipher",	name: "Graue Geheimschrift",	id: "grayCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Horrible Memory",	name: "Grausiges Memory",	id: "horribleMemory",	questions: ["Welche Taste hatte in welcher Stufe welche Farbe und welche Aufschrift?", "Welche Ziffer war in welcher Stufe auf dem Display?"] },
	{ original: "Gryphons",	name: "Greifen",	id: "gryphons",	questions: ["Welchen Namen und welches Alter hatte der Greif?"] },
	{ original: "Big Bean",	name: "Großbohne",	id: "bigBean",	questions: ["Welche Farbe und Wackeligkeit hatte die Bohne?"] },
	{ original: "Big Circle",	name: "Großer Kreis",	id: "BigCircle",	questions: ["Wierum hat sich der Kreis gedreht?"] },
	{ original: "Green Cipher",	name: "Grüne Geheimschrift",	id: "greenCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Green Arrows",	name: "Grüne Pfeile",	id: "greenArrowsModule",	questions: ["Was war die letzte Zahl auf dem Display?"] },
	{ original: "Gyromaze",	name: "Gyrolabyrinth",	id: "gyromaze",	questions: ["Welche LED hatte welche Farbe?"] },
	{ original: "Encrypted Hangman",	name: "Hangman Verschlüsselt",	id: "encryptedHangman",	questions: ["Welcher Modulname wurde wie verschlüsselt?"] },
	{ original: "Hexamaze",	name: "Hexalabyrinth",	id: "HexamazeModule",	questions: ["Welche Farbe hatte die Spielfigur?"] },
	{ original: "Hill Cycle",	name: "Hill-Schiffer",	id: "hillCycle",	questions: ["In welche Richtung zeigten die Drehknöpfe?", "Was stand auf den Drehknöpfen?"] },
	{ original: "Cruel Keypads",	name: "Höllische Tastenfelder",	id: "CruelKeypads",	questions: ["Welche Symbole waren in welcher Stufe auf dem Display und welche Farbe hatte der Balken?"] },
	{ original: "Cruel Binary",	name: "Höllisches Binärsystem",	id: "CruelBinary",	questions: ["Welches Wort war auf dem Display?"] },
	{ original: "Game of Life Cruel",	name: "Höllisches Spiel des Lebens",	id: "GameOfLifeCruel",	questions: ["Welche Farbkombinationen kamen vor?"] },
	{ original: "Holographic Memory",	name: "Holographisches Gedächtnis",	id: "holographicMemory",	questions: ["Auf welcher Seite erschien welches Symbol?"] },
	{ original: "Identification Crisis",	name: "Identifikationskrise",	id: "identificationCrisis",	questions: ["Welche Formen und Identifikationsmodule kamen vor?"] },
	{ original: "Identity Parade",	name: "Identitätsparade",	id: "identityParade",	questions: ["Welche Haarfarben, Körperbaus und Garderoben standen zur Auswahl?"] },
	{ original: "Indigo Cipher",	name: "Indigo-Geheimschrift",	id: "indigoCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Inner Connections",	name: "Innere Verbindungen",	id: "InnerConnectionsModule",	questions: ["Welche Farbe hatte die LED?", "Welche Ziffer wurde in Morsezeichen übermittelt?"] },
	{ original: "Interpunct",	name: "Interpunkt",	id: "interpunct",	questions: ["Welches Symbol war in welcher Stufe auf dem Display?"] },
	{ original: "...?",	name: "Interpunktionszeichen",	id: "punctuationMarks",	questions: ["Welche Zahl war auf dem Display?"] },
	{ original: "Hunting",	name: "Jagd",	id: "hunting",	questions: ["Welche Piktogramme kamen vor?"] },
	{ original: "The Jewel Vault",	name: "Juwelentresor",	id: "jewelVault",	questions: ["Welches Rad setzte sich durch welches andere Rad in Bewegung?"] },
	{ original: "Coffee Beans",	name: "Kaffeebohnen",	id: "coffeeBeans",	questions: ["Welche Bewegungen kamen vor?"] },
	{ original: "Cacti’s Conundrum",	name: "Kakteen-Zwickmühle",	id: "CactusPConundrum",	questions: ["Welche Farben hatte die LED?"] },
	{ original: "Calendar",	name: "Kalender",	id: "calendar",	questions: ["Um welchen Feiertag ging es?"] },
	{ original: "Broken Guitar Chords",	name: "Kaputte Gitarrenakkorde",	id: "BrokenGuitarChordsModule",	questions: ["Welcher Akkord war auf dem Display?", "Welche Saite war kaputt?"] },
	{ original: "Crimson Cipher",	name: "Karmin-Geheimschrift",	id: "crimsonCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Maroon Cipher",	name: "Kastanien-Geheimschrift",	id: "maroonCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Know Your Way",	name: "Kenne Den Weg",	id: "KnowYourWay",	questions: ["In welche Richtung zeigte der Pfeil?", "Welche LED war grün?"] },
	{ original: "Kooky Keypad",	name: "Kirres Tastenfeld",	id: "kookyKeypadModule",	questions: ["Welche Farbe hatten die LEDs?"] },
	{ original: "Not Piano Keys",	name: "Klavier Mal Anders",	id: "notPianoKeys",	questions: ["Welche Symbole waren zu sehen?"] },
	{ original: "Cheap Checkout",	name: "Klingelkasse",	id: "CheapCheckoutModule",	questions: ["Welche Beträge wurden angeboten?"] },
	{ original: "Tap Code",	name: "Klopfzeichen",	id: "tapCode",	questions: ["Welches Wort wurde übermittelt?"] },
	{ original: "Yahtzee",	name: "Kniffel",	id: "YahtzeeModule",	questions: ["Was wurde als erstes gewürfelt?"] },
	{ original: "Buttonage",	name: "Knopferei",	id: "buttonageModule",	questions: ["Welche Farbe und Rahmenfarbe kam wie oft vor?", "Wie viele Spezialtasten gab es?", "Wie viele Tasten hatten ein P?"] },
	{ original: "Button Sequence",	name: "Knopffolgen",	id: "buttonSequencesModule",	questions: ["Welche Farbe kam wie oft vor?"] },
	{ original: "Order Picking",	name: "Kommissionierung",	id: "OrderPickingModule",	questions: ["Welche Bestellung hatte welche Bestellnummer, Produktnummer und Palette?"] },
	{ original: "Concentration",	name: "Konzentrationsspiel",	id: "ConcentrationModule",	questions: ["Wie war das Arrangement am Anfang?"] },
	{ original: "Grand Piano",	name: "Konzertflügel",	id: "grandPiano",	questions: ["Welche Noten waren vorgegeben?"] },
	{ original: "Coordinates",	name: "Koordinaten",	id: "CoordinatesModule",	questions: ["Was war die Rastergröße?"] },
	{ original: "Not Coordinates",	name: "Koordinaten Mal Anders",	id: "notCoordinates",	questions: ["Wie lauteten die Eckpunkte des Quadrats?"] },
	{ original: "Coordination",	name: "Koordinierung",	id: "Coordination",	questions: ["What was the label and position of the starting coordinate?"] },
	{ original: "Coral Cipher",	name: "Korall-Geheimschrift",	id: "coralCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Cornflower Cipher",	name: "Kornblumen-Geheimschrift",	id: "cornflowerCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Cosmic",	name: "Kosmik",	id: "CosmicModule",	questions: ["Welche Zahl war am Anfang auf dem Display?"] },
	{ original: "Critters",	name: "Kriechtiere",	id: "CrittersModule",	questions: ["What was the alteration color?"] },
	{ original: "Cryptic Cycle",	name: "Kryptische Schiffer",	id: "crypticCycle",	questions: ["In welche Richtung zeigten die Drehknöpfe?", "Was stand auf den Drehknöpfen?"] },
	{ original: "Cryptic Keypad",	name: "Kryptisches Tastenfeld",	id: "GSCrypticKeypad",	questions: ["Welche Aufschrift und Himmelsrichtung war auf den Tasten?"] },
	{ original: "Customer Identification",	name: "Kundenidentifikation",	id: "xelCustomerIdentification",	questions: ["Welche Kunden kamen vor?"] },
	{ original: "Not Maze",	name: "Labyrinth Mal Anders",	id: "NotMaze",	questions: ["Was war die Startdistanz?"] },
	{ original: "Long Words",	name: "Lange Wörter",	id: "LongWords",	questions: ["Welches Wort war auf dem oberen Display?"] },
	{ original: "Langton’s Anteater",	name: "Langton-Ameisenbär",	id: "GSLangtonsAnteater",	questions: ["Wie sah das Spielfeld am Anfang aus?"] },
	{ original: "LED Grid",	name: "LED-Gitter",	id: "ledGrid",	questions: ["Wie viele LEDs waren an?"] },
	{ original: "LED Math",	name: "LED-Mathe",	id: "lgndLEDMath",	questions: ["Welche LED hatte welche Farbe?"] },
	{ original: "LED Encryption",	name: "LED-Verschlüsselung",	id: "LEDEnc",	questions: ["Welche Buchstaben kamen in welcher Stufe vor?"] },
	{ original: "LEGOs",	name: "LEGO",	id: "LEGOModule",	questions: ["Welches Teil hatte welche Größe?"] },
	{ original: "Ladder Lottery",	name: "Leiterlotterie",	id: "ladderLottery",	questions: ["Welches Licht war an?"] },
	{ original: "Ladders",	name: "Leitern",	id: "ladders",	questions: ["Welche Farben kamen auf der zweiten Leiter vor?", "Welche Farbe hat auf der dritten Leiter gefehlt?"] },
	{ original: "Lempel-Ziv Cipher",	name: "Lempel-Ziv-Geheimschrift",	id: "LempelZivCipherModule",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Purple Arrows",	name: "Lilane Pfeile",	id: "purpleArrowsModule",	questions: ["Was war das Zielwort?"] },
	{ original: "Lime Arrows",	name: "Limette-Pfeile",	id: "limeArrowsModule",	questions: ["Was waren die Startkoordinaten?"] },
	{ original: "Logic Gates",	name: "Logikgatter",	id: "logicGates",	questions: ["Welches Gatter war A, B, C, D?"] },
	{ original: "Logical Buttons",	name: "Logiktasten",	id: "logicalButtonsModule",	questions: ["Welche Taste hatte in welcher Stufe welche Farbe und welche Aufschrift?", "Was war in welcher Stufe der letzte Operator?"] },
	{ original: "Lombax Cubes",	name: "Lombax-Würfel",	id: "lgndLombaxCubes",	questions: ["Welche Buchstaben waren auf den Tasten?"] },
	{ original: "Lion’s Share",	name: "Löwenanteil",	id: "LionsShareModule",	questions: ["Um welches Jahr ging es?", "Welche Löwen wurden entfernt?"] },
	{ original: "Magenta Cipher",	name: "Magenta-Geheimschrift",	id: "magentaCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Painting Cube",	name: "Malfarbenwürfel",	id: "paintingCube",	questions: ["Welche Farbe hat gefehlt?"] },
	{ original: "Slow Math",	name: "Mathe in Zeitlupe",	id: "SlowMathModule",	questions: ["Was war das letzte Buchstabentripel?"] },
	{ original: "Fast Math",	name: "Mathe in Zeitraffer",	id: "fastMath",	questions: ["Was war das letzte Buchstabenpaar?"] },
	{ original: "Mouse In The Maze",	name: "Maus im Labyrinth",	id: "MouseInTheMaze",	questions: ["Welche Farbe hatte der Torus?"] },
	{ original: "Varicolored Squares",	name: "Mischgefärbte Felder",	id: "VaricoloredSquaresModule",	questions: ["Welche Farbe wurde als erste eingegeben?"] },
	{ original: "Module Maneuvers",	name: "Modulmanöver",	id: "moduleManeuvers",	questions: ["Wo war das Ziel?"] },
	{ original: "Murder",	name: "Mord",	id: "murder",	questions: ["Welche Verdächtigten und Waffen kamen vor?", "Wo wurde die Leiche gefunden?"] },
	{ original: "Not Murder",	name: "Mord Mal Anders",	id: "notMurder",	questions: ["Welche Verdachtsperson war am Anfang in welchem Raum?", "Welche Verdachtsperson hatte am Anfang welche Waffe?"] },
	{ original: "Reverse Morse",	name: "Morse Andersrum",	id: "reverseMorse",	questions: ["Welche Symbole waren auf dem Display und in welcher Farbe?"] },
	{ original: "Morsematics",	name: "Morsematik",	id: "MorseV2",	questions: ["Welche Buchstaben wurden übermittelt?"] },
	{ original: "Not Morsematics",	name: "Morsematik Mal Anders",	id: "notMorsematics",	questions: ["Welches Wort wurde übermittelt?"] },
	{ original: "Not Morse Code",	name: "Morsezeichen Mal Anders",	id: "NotMorseCode",	questions: ["Welche Wortfolge wurde eingegeben?"] },
	{ original: "The Multiverse Hotline",	name: "Multiversum-Hotline",	id: "MultiverseHotline",	questions: ["Was war der Ursprung des Universums und dessen Zahl am Anfang?"] },
	{ original: "Coinage",	name: "Münzerei",	id: "Coinage",	questions: ["Welche Münze war umgekehrt?"] },
	{ original: "Pattern Recognition",	name: "Mustererkennung",	id: "patternRecognition",	questions: ["Was war das sich wiederholende Muster?"] },
	{ original: "Pattern Cube",	name: "Musterwürfel",	id: "PatternCubeModule",	questions: ["Welches Symbol war hervorgehoben?"] },
	{ original: "Navinums",	name: "Navinummern",	id: "navinums",	questions: ["Welche Richtungstasten wurden gedrückt?", "Welche Ziffer war am Anfang in der Mitte?"] },
	{ original: "Regular Crazy Talk",	name: "Normales Verrücktes Gerede",	id: "RegularCrazyTalkModule",	questions: ["Welche Ziffer auf dem Display gehörte zur Lösungsphrase?", "Welche Verzierung hatte die Lösungsphrase?"] },
	{ original: "Zero, Zero",	name: "Null, Null",	id: "zeroZero",	questions: ["Welcher Stern hatte welche Farbe und wie viele Zacken?", "Welche Felder waren gefärbt?"] },
	{ original: "Numbered Buttons",	name: "Nummerierte Knöpfe",	id: "numberedButtonsModule",	questions: ["Welche Zahlen wurden korrekt eingegeben?"] },
	{ original: "Orange Cipher",	name: "Orangene Geheimschrift",	id: "orangeCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Orientation Hypercube",	name: "Orientierungshyperwürfel",	id: "OrientationHypercube",	questions: ["Wo war der Beobachter am Anfang?", "Welche Fläche hatte am Anfang welche Farbe?"] },
	{ original: "Orientation Cube",	name: "Orientierungswürfel",	id: "OrientationCube",	questions: ["Wo war der Beobachter am Anfang?"] },
	{ original: "Palindromes",	name: "Palindrome",	id: "palindromes",	questions: ["Was war X, Y, Z und die Anzeige auf dem Display?"] },
	{ original: "Papa’s Pizzeria",	name: "Papas Pizzeria",	id: "papasPizzeria",	questions: ["Was war die Bestellnummer?"] },
	{ original: "Parity",	name: "Parität",	id: "parity",	questions: ["Was stand auf dem Display?"] },
	{ original: "Partial Derivatives",	name: "Partielle Ableitungen",	id: "partialDerivatives",	questions: ["Was waren die Terme der Funktion?", "Welche LED hatte in welcher Stufe welche Farbe?"] },
	{ original: "Passport Control",	name: "Passkontrolle",	id: "passportControl",	questions: ["Welches Ablaufjahr hatte der Reisepass von welchem Reisenden?"] },
	{ original: "Not Password",	name: "Passwort Mal Anders",	id: "NotPassword",	questions: ["Welcher Buchstabe hat gefehlt?"] },
	{ original: "Password Destroyer",	name: "Passwortzerstörer",	id: "pwDestroyer",	questions: ["Was war der 2FAST™-Wert?"] },
	{ original: "Retirement",	name: "Pension",	id: "retirement",	questions: ["Welche Altersheime waren im Angebot, aber nicht Bobs Wahl?"] },
	{ original: "The Pentabutton",	name: "Pentaknopf",	id: "GSPentabutton",	questions: ["Was war die Basisfarbe?"] },
	{ original: "Periodic Words",	name: "Periodische Wörter",	id: "periodicWordsRB",	questions: ["Welches Wort wurde in welcher Stufe abgefragt?"] },
	{ original: "Human Resources",	name: "Personalabteilung",	id: "HumanResourcesModule",	questions: ["Welche Angestellten und Bewerber waren vorhanden?", "Welche Beschreibungen kamen in rot bzw. grün vor?"] },
	{ original: "Perspective Pegs",	name: "Perspektivstöpsel",	id: "spwizPerspectivePegs",	questions: ["Was war die anfängliche Farbfolge?"] },
	{ original: "Not Perspective Pegs",	name: "Perspektivstöpsel Mal Anders",	id: "NotPerspectivePegsModule",	questions: ["Welche Farbe leuchtete an welcher Position und in welcher Perspektive?"] },
	{ original: "Phosphorescence",	name: "Phosphoreszenz",	id: "Phosphorescence",	questions: ["Was waren die Tasteneingaben und das Offset?"] },
	{ original: "Pixel Cipher",	name: "Pixelgeheimschrift",	id: "pixelcipher",	questions: ["Wie lautete das Schlüsselwort?"] },
	{ original: "Planets",	name: "Planeten",	id: "planets",	questions: ["Welcher Planet war zu sehen?", "What was the color for each strip?"] },
	{ original: "Placement Roulette",	name: "Platzierungsroulette",	id: "PlacementRouletteModule",	questions: ["Welche Figur, Rennstrecke und Rennwagen waren aufgelistet?"] },
	{ original: "Fast Playfair Cipher",	name: "Playfair-Chiffre im Zeitraffer",	id: "FastPlayfairCipher",	questions: ["What was the last displayed message?"] },
	{ original: "Playfair Cycle",	name: "Playfair-Schiffer",	id: "playfairCycle",	questions: ["In welche Richtung zeigten die Drehknöpfe?", "Was stand auf den Drehknöpfen?"] },
	{ original: "Pokémon Sprite Cipher",	name: "Pokémon-Sprite-Geheimschrift",	id: "PokemonSpriteCipherModule",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Polyhedral Maze",	name: "Polyederlabyrinth",	id: "PolyhedralMazeModule",	questions: ["Wo war die Startposition?"] },
	{ original: "Polygons",	name: "Polygone",	id: "polygons",	questions: ["Welche Polygone waren vorhanden?"] },
	{ original: "Prime Encryption",	name: "Primverschlüsselung",	id: "primeEncryption",	questions: ["Welche Zahl war auf dem Display?"] },
	{ original: "Procedural Maze",	name: "Prozedurales Labyrinth",	id: "ProceduralMaze",	questions: ["What was the initial seed?"] },
	{ original: "Scrutiny Squares",	name: "Prüfquadrate",	id: "scrutinySquares",	questions: ["Welches Merkmal war beim ersten Quadrat falsch?"] },
	{ original: "Quadrants",	name: "Quadranten",	id: "Quadrants",	questions: ["What was on each button in each stage?"] },
	{ original: "Quantum Ternary Converter",	name: "Quanten-Ternär-Konverter",	id: "quTern",	questions: ["Welche Zahlen kamen vor?"] },
	{ original: "Quantum Passwords",	name: "Quantenpasswörter",	id: "quantumPasswords",	questions: ["Which words were used?"] },
	{ original: "Quintuples",	name: "Quintupel",	id: "quintuples",	questions: ["Welche Stelle enthielt welche Zahlen und Farben?", "Wie viele Zahlen gab es von welcher Farbe?"] },
	{ original: "Puzzling Hexabuttons",	name: "Rätselhafte Hexaknöpfe",	id: "puzzlingHexabuttons",	questions: ["Welche Buchstaben waren während der Eingabe zu sehen?"] },
	{ original: "Noise Identification",	name: "Rauschen-Identifikation",	id: "noiseIdentification",	questions: ["Welcher Klangtyp war zuerst zu sehen?"] },
	{ original: "Reformed Role Reversal",	name: "Reformierte Rollenumkehr",	id: "ReformedRoleReversal",	questions: ["Was besagte die Lösungsbedingung?", "Welcher Draht hatte welche Farbe?"] },
	{ original: "Rainbow Arrows",	name: "Regenbogenpfeile",	id: "ksmRainbowArrows",	questions: ["Welche Zahl war auf dem Display?"] },
	{ original: "Recursive Password",	name: "Rekursives Passwort",	id: "RecursivePassword",	questions: ["Wie lauteten die unvollständigen Wörter?", "Wie lautete das Passwort?"] },
	{ original: "RGB Sequences",	name: "RGB-Folgen",	id: "RGBSequences",	questions: ["Welche Taste hatte welche Farbe?"] },
	{ original: "RGB Maze",	name: "RGB-Labyrinth",	id: "rgbMaze",	questions: ["Wo im Labyrinth waren die Schlüssel und das Ziel?", "Welches Labyrinth hatte welche Nummer?"] },
	{ original: "RGB Encryption",	name: "RGB-Verschlüsselung",	id: "RGBEncryption",	questions: ["Wie lautete die Morse- und die Farbsequenz?"] },
	{ original: "Rhythms",	name: "Rhythmen",	id: "MusicRhythms",	questions: ["Welche Farbe hatte die LED?"] },
	{ original: "Directional Button",	name: "Richtungsknopf",	id: "directionalButton",	questions: ["In welche Stufe wurde die Taste wie oft betätigt?"] },
	{ original: "Giants Cipher",	name: "Riesen-Geheimschrift",	id: "GiantsCipher",	questions: ["Was war das Schlüsselwort auf dem Display?"] },
	{ original: "RNG Crystal",	name: "RNG-Kristall",	id: "rngCrystal",	questions: ["Wo waren die Taps?"] },
	{ original: "Robo-Scanner",	name: "RoboScanner",	id: "roboScannerModule",	questions: ["Wo war die leere Zelle?"] },
	{ original: "Role Reversal",	name: "Rollenumkehr",	id: "roleReversal",	questions: ["Mit der Bedingung mit welcher Ziffer wurde das Modul entschärft?", "Welche Farben hatten die internen Drähte?"] },
	{ original: "Not X-Ray",	name: "Röntgen Mal Anders",	id: "NotXRayModule",	questions: ["Welches Labyrinth kam zum Einsatz?", "Welche Taste ging in welche Richtung?", "Welche Farbe hatte der Scanner?"] },
	{ original: "Red Cipher",	name: "Rote Geheimschrift",	id: "redCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Red Arrows",	name: "Rote Pfeile",	id: "redArrowsModule",	questions: ["Wie lautete die Startzahl?"] },
	{ original: "Not Red Arrows",	name: "Rote Pfeile Mal Anders",	id: "notRedArrowsModule",	questions: ["Wie lautete die Startzahl?"] },
	{ original: "Red Herring",	name: "Roter Hering",	id: "RedHerring",	questions: ["Welche Farbe ist als erste aufgeleuchtet?"] },
	{ original: "Red Button’t",	name: "Roter Knopf Mal Anders",	id: "redbuttont",	questions: ["Welches Wort war auf dem Display?"] },
	{ original: "S.E.T. Theory",	name: "S.E.T.-Theorie",	id: "SetTheory",	questions: ["In welcher Stufe war welche Gleichung auf dem Display?"] },
	{ original: "Sbemail Songs",	name: "Sbemail-Lieder",	id: "sbemailsongs",	questions: ["Welche Songs waren in welcher Stufe auf dem Display?"] },
	{ original: "Chess",	name: "Schach",	id: "ChessModule",	questions: ["Welche Koordinaten kamen vor?"] },
	{ original: "Switches",	name: "Schalter",	id: "switchModule",	questions: ["Wie standen die Schalter am Anfang?"] },
	{ original: "Hinges",	name: "Scharniere",	id: "hinges",	questions: ["Welche Scharniere waren anfangs vorhanden?"] },
	{ original: "Shifting Maze",	name: "Schiebelabyrinth",	id: "MazeShifting",	questions: ["Was war der Seedcode?"] },
	{ original: "Maritime Flags",	name: "Schiffsignalflaggen",	id: "MaritimeFlagsModule",	questions: ["Welche Peilung wurde signalisiert?", "Welches Rufzeichen wurde signalisiert?"] },
	{ original: "Maritime Semaphore",	name: "Schiffsignalwinker",	id: "MaritimeSemaphoreModule",	questions: ["Wo war die Finte?", "Welche Buchstaben wurden signalisiert?"] },
	{ original: "Cheat Checkout",	name: "Schlingelkasse",	id: "kataCheatCheckout",	questions: ["Um welche Kryptowährung ging es?", "Welche Site wurde mit welcher Methode gehackt?"] },
	{ original: "Keywords",	name: "Schlüsselwörter",	id: "xtrkeywords",	questions: ["Welche Buchstaben waren auf dem Display?"] },
	{ original: "Quick Arithmetic",	name: "Schnellarithmetik",	id: "QuickArithmetic",	questions: ["Welche der zwei Folgen enthielt welche Ziffern und Farben?"] },
	{ original: "Scavenger Hunt",	name: "Schnitzeljagd",	id: "scavengerHunt",	questions: ["Welches Feld wurde in der ersten Stufe korrekt eingegeben?", "Wo waren in der ersten Stufe die roten/grünen/blauen Felder?"] },
	{ original: "Creation",	name: "Schöpfung",	id: "CreationModule",	questions: ["Wie war das Wetter am ersten Tag?"] },
	{ original: "The Weakest Link",	name: "Schwächstes Glied",	id: "TheWeakestLink",	questions: ["Wer wurde eliminiert?", "Wer kam in der Geldphase dazu?", "Welche Skills und welche Antwortquote hatten die anderen Kandidaten?"] },
	{ original: "Black Cipher",	name: "Schwarze Geheimschrift",	id: "blackCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Visual Impairment",	name: "Sehbehinderung",	id: "visual_impairment",	questions: ["Welche Farben wurden verlangt?"] },
	{ original: "Shogi Identification",	name: "Shogi-Identifikation",	id: "shogiIdentification",	questions: ["Welcher Spielstein war zu sehen?"] },
	{ original: "The Fuse Box",	name: "Sicherungskasten",	id: "FuseBox",	questions: ["Welche Farben haben aufgeleuchtet?", "Welche Pfeile waren richtig?"] },
	{ original: "Silo Authorization",	name: "Silo-Authorisierung",	id: "siloAuthorization",	questions: ["Was war der Nachrichtentyp, die verschlüsselte Nachricht und der empfangene Zugangscode?"] },
	{ original: "Not Simaze",	name: "Simobyrinth Mal Anders",	id: "NotSimaze",	questions: ["Welches Labyrinth kam zum Einsatz?", "Wo war die Start- und Zielposition?"] },
	{ original: "Simon Shapes",	name: "Simon Formt",	id: "SimonShapesModule",	questions: ["Welche Form wurde am Ende eingegeben?"] },
	{ original: "Simon Shrieks",	name: "Simon Kreischt",	id: "SimonShrieksModule",	questions: ["Wie weit im Uhrzeigersinn vom Pfeil war welche Farbe in der endgültigen Folge?"] },
	{ original: "Simon Smiles",	name: "Simon Lächelt",	id: "SimonSmiles",	questions: ["Welche Taste löste welchen Sound aus?"] },
	{ original: "Simon Shuffles",	name: "Simon Mischt",	id: "GSSimonShuffles",	questions: ["Welche Tasten haben in welcher Stufe aufgeleuchtet?"] },
	{ original: "Simon Shouts",	name: "Simon Ruft",	id: "SimonShoutsModule",	questions: ["Welche Buchstaben wurden auf welchen Tasten übermittelt?"] },
	{ original: "Simon Says",	name: "Simon Sagt",	id: "Simon",	questions: ["Was war am Ende die Farbfolge?"] },
	{ original: "Simon Said",	name: "Simon Sagte",	id: "simonSaidModule",	questions: ["Was war am Ende die Farbfolge?"] },
	{ original: "Simon Screams",	name: "Simon Schreit",	id: "SimonScreamsModule",	questions: ["Welche Farbe aus der Folge war in welcher Stufe ausschlaggebend?", "Welche Regeln trafen in welchen Stufen zu?"] },
	{ original: "Simon Scrambles",	name: "Simon Schüttelt",	id: "simonScrambles",	questions: ["Wie lautete die Farbfolge?"] },
	{ original: "Simon Selects",	name: "Simon Selektiert",	id: "simonSelectsModule",	questions: ["Welche Farben kam in welcher Stufe vor?"] },
	{ original: "Simon Sends",	name: "Simon Sendet",	id: "SimonSendsModule",	questions: ["Welche Buchstaben wurden in rot/grün/blau übermittelt?"] },
	{ original: "Simon Serves",	name: "Simon Serviert",	id: "simonServes",	questions: ["Wer ist bei welchem Gang aufgeleuchtet?", "Welche Gerichte wurden in welchem Gang nicht serviert?"] },
	{ original: "Simon Signals",	name: "Simon Signalisiert",	id: "SimonSignalsModule",	questions: ["Welcher Pfeil hatte welche Farbe, Form und Anzahl Richtungen?"] },
	{ original: "Simon Simons",	name: "Simon Simont",	id: "simonSimons",	questions: ["Welche Tasten haben aufgeleuchtet?"] },
	{ original: "Simon Sings",	name: "Simon Singt",	id: "SimonSingsModule",	questions: ["Welche Noten wurden in welcher Stufe durch Farben angezeigt?"] },
	{ original: "Simon States",	name: "Simon Statuiert",	id: "SimonV2",	questions: ["Welche Farbe(n) leuchtete(n) in den ersten drei Stufen auf?"] },
	{ original: "Simon Stages",	name: "Simon-Stufen",	id: "simonStages",	questions: ["Which colors flashed in each stage?", "Welche Farbe hatte der Indikator in welcher Stufe?"] },
	{ original: "Simon Samples",	name: "Simons Samples",	id: "simonSamples",	questions: ["Welche Rufsamples kamen in welcher Stufe vor?"] },
	{ original: "Simon’s Star",	name: "Simons Stern",	id: "simonsStar",	questions: ["Which colors flashed in each stage?"] },
	{ original: "Pointless Machines",	name: "Sinnlose Maschinen",	id: "PointlessMachines",	questions: ["Welche Farben haben aufgeleuchtet?"] },
	{ original: "Probing",	name: "Sondierung",	id: "Probing",	questions: ["Welche Frequenzen haben in welchem Draht gefehlt?"] },
	{ original: "Dumb Waiters",	name: "Speisenaufzug",	id: "dumbWaiters",	questions: ["Welche Spieler waren vorhanden?"] },
	{ original: "Mirror",	name: "Spiegel",	id: "mirror",	questions: ["Was war das zweite vom ursprünglichen Geist geschriebene Wort?"] },
	{ original: "Stable Time Signatures",	name: "Stabile Taktarten",	id: "StableTimeSignatures",	questions: ["In welchen Takten wurde gespielt?"] },
	{ original: "Stability",	name: "Stabilität",	id: "stabilityModule",	questions: ["Welche Farbe hatte welche LED, die an war?", "Wie lautete die Identifikationsnummer?"] },
	{ original: "Stellar",	name: "Sternchen",	id: "stellar",	questions: ["Welche Buchstaben kamen vor?"] },
	{ original: "Stars",	name: "Sterne",	id: "stars",	questions: ["Welche Ziffer war in der Mitte?"] },
	{ original: "Starstruck",	name: "Sternenbegeisterung",	id: "starstruck",	questions: ["Welche Sterne waren zu sehen?"] },
	{ original: "Stroop’s Test",	name: "Stroop-Test",	id: "stroopsTest",	questions: ["Welche Wörter/Farben wurden eingegeben?"] },
	{ original: "Grocery Store",	name: "Supermarkt",	id: "groceryStore",	questions: ["Welcher Artikel wurde zuerst angezeigt?"] },
	{ original: "Symbolic Tasha",	name: "Symbole-Tasha",	id: "symbolicTasha",	questions: ["Welches Symbol war auf welcher Taste?", "Welche Tasten leuchteten auf?"] },
	{ original: "Not Keypad",	name: "Tastenfeld Mal Anders",	id: "NotKeypad",	questions: ["Aus welchen Farben bestand die endgültige Folge?", "Welche Symbole waren auf den in der endgültigen Folge vertretenen Tasten?"] },
	{ original: "Keypad Combinations",	name: "Tastenfeld-Kombinationen",	id: "keypadCombinations",	questions: ["Welche Zahlen waren vorhanden aber nicht Teil der Lösung?"] },
	{ original: "Keypad Maze",	name: "Tastenfeld-Labyrinth",	id: "KeypadMaze",	questions: ["Welche Zellen waren gelb?"] },
	{ original: "Keypad Sequence",	name: "Tastenfeld-Sequenz",	id: "keypadSeq",	questions: ["Welche Symbole waren auf den Tasten?"] },
	{ original: "Deaf Alley",	name: "Taube Gasse",	id: "deafAlleyModule",	questions: ["Welche Form wurde generiert?"] },
	{ original: "Technical Keypad",	name: "Technisches Tastenfeld",	id: "TechnicalKeypad",	questions: ["Welche Ziffern waren auf dem Display?"] },
	{ original: "Homophones",	name: "Teekesselchen",	id: "homophones",	questions: ["Welcome Phrasen waren auf dem Display?"] },
	{ original: "Divisible Numbers",	name: "Teilbare Zahlen",	id: "divisibleNumbers",	questions: ["In welcher Stufe lauteten die Zahlen wie?"] },
	{ original: "Raiding Temples",	name: "Tempelraubzug",	id: "raidingTemples",	questions: ["Wie viele Juwelen waren am Anfang im gemeinsamen Pool?"] },
	{ original: "Tenpins",	name: "Tenpin-Bowling",	id: "tenpins",	questions: ["Welche Splits kamen vor?"] },
	{ original: "Devilish Eggs",	name: "Teufelseier",	id: "devilishEggs",	questions: ["Welche Rotationen kamen vor?", "Welche Zahlen und Buchstaben kamen auf dem Prisma vor?"] },
	{ original: "Not Text Field",	name: "Textfeld Mal Anders",	id: "notTextField",	questions: ["Welcher Buchstabe kam am Anfang 9-mal vor?", "Welche Buchstaben wurden in der ersten Stufe eingegeben?"] },
	{ original: "Tic Tac Toe",	name: "Tic-Tac-Toe",	id: "TicTacToeModule",	questions: ["Wie sah das Spielfeld am Anfang aus?"] },
	{ original: "Hickory Dickory Dock",	name: "Tickitie-Tackitie-Tock",	id: "hickoryDickoryDockModule",	questions: ["Welche Uhrzeit wurde bei welchem Geläute angezeigt?"] },
	{ original: "Dreamcipher",	name: "Traumschrift",	id: "ksmDreamcipher",	questions: ["Was war das entschlüsselte Wort?"] },
	{ original: "Tricky Tetris Pieces",	name: "Trickreiche Tetris-Teile",	id: "TrickyTetrisPieces",	questions: ["Welche Form hatte das als erstes eingegebene Teil?", "In welche zweite Farbpalette haben sich die Teile verwandelt?"] },
	{ original: "UFO Satellites",	name: "UFO-Satelliten",	id: "UfoSatellites",	questions: ["Welche Zahlen kamen vor?"] },
	{ original: "Ultimate Cipher",	name: "Ultimative Geheimschrift",	id: "ultimateCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Ultimate Cycle",	name: "Ultimative Schiffer",	id: "ultimateCycle",	questions: ["In welche Richtung zeigten die Drehknöpfe?", "Was stand auf den Drehknöpfen?"] },
	{ original: "Recolored Switches",	name: "Umgefärbte Schalter",	id: "R4YRecoloredSwitches",	questions: ["Welche LED hatte welche Farbe?"] },
	{ original: "Reverse Polish Notation",	name: "Umgekehrte Polnische Notation",	id: "revPolNot",	questions: ["Welche Zeichen kamen in welcher Stufe vor?"] },
	{ original: "Reordered Keys",	name: "Umgeordnete Tasten",	id: "reorderedKeys",	questions: ["In welcher Stufe hatte welche Taste am Anfang welche Farbe, Aufschrift und Aufschriftfarbe?"] },
	{ original: "Unpleasant Squares",	name: "Unangenehme Quadrate",	id: "unpleasantSquares",	questions: ["Welche Farbe hatte welches Feld?"] },
	{ original: "Unfair’s Cruel Revenge",	name: "Unfairs Höllische Rache",	id: "unfairsRevengeCruel",	questions: ["Wie lauteten die entschlüsselten Instruktionen?"] },
	{ original: "Unfair’s Revenge",	name: "Unfairs Rache",	id: "unfairsRevenge",	questions: ["Wie lauteten die entschlüsselten Instruktionen?"] },
	{ original: "Uncolored Squares",	name: "Ungefärbte Felder",	id: "UncoloredSquaresModule",	questions: ["Welche Farben kamen in der ersten Stufe zum Einsatz?"] },
	{ original: "Uncolour Flash",	name: "Ungefärbte Folge",	id: "uncolourFlash",	questions: ["Wie lauteten die „YES“- und „NO“-Folgen am Anfang?"] },
	{ original: "Uncolored Switches",	name: "Ungefärbte Schalter",	id: "R4YUncoloredSwitches",	questions: ["Wie sahen die Schalter am Anfang aus?", "Welche LED hatte welche Farbe?"] },
	{ original: "Unown Cipher",	name: "Unown-Geheimschrift",	id: "UnownCipher",	questions: ["Welche Buchstaben wurden eingegeben?"] },
	{ original: "Undertunneling",	name: "Untertunnelung",	id: "undertunneling",	questions: ["Wo im Labyrinth war der Spieler am Ende der ersten Phase?"] },
	{ original: "USA Maze",	name: "USA-Labyrinth",	id: "USA",	questions: ["Welcher Staat war Ausgangspunkt der Reise?"] },
	{ original: "USA Cycle",	name: "USA-Schiffer",	id: "USACycle",	questions: ["Welche Staaten kamen vor?"] },
	{ original: "Vectors",	name: "Vektoren",	id: "vectorsModule",	questions: ["Welche Farben hatten die Vektoren?"] },
	{ original: "Valves",	name: "Ventile",	id: "valves",	questions: ["What was the initial state?"] },
	{ original: "Connection Check",	name: "Verbindungsprüfung",	id: "graphModule",	questions: ["Welche Zahlenpaare kamen vor?"] },
	{ original: "Not Connection Check",	name: "Verbindungsprüfung Mal Anders",	id: "notConnectionCheck",	questions: ["Welche Symbole wurden übermittelt?", "Welche Werte hatten die Tasten?"] },
	{ original: "Connected Monitors",	name: "Verbundene Monitore",	id: "ConnectedMonitorsModule",	questions: ["Welche Zahlen waren am Anfang auf dem Display?", "Welche Farbe hatten die Indikatoren?"] },
	{ original: "Discolored Squares",	name: "Verfärbte Felder",	id: "DiscoloredSquaresModule",	questions: ["Welche Position wurde für welche Farbe vermerkt?"] },
	{ original: "Cursed Double-Oh",	name: "Verfluchte Doppel-Null",	id: "CursedDoubleOhModule",	questions: ["Was war bei der Anfangszahl die erste Ziffer?"] },
	{ original: "Forget Everything",	name: "Vergiss Alles",	id: "HexiEvilFMN",	questions: ["Welche Ziffern waren in Stufe 1 auf dem Zylinder?"] },
	{ original: "Forget The Colors",	name: "Vergiss Die Farben",	id: "ForgetTheColors",	questions: ["Welches Zahnrad, welche letzte Ziffer der Sinuszahl und welche Anzeige auf dem großen Display kam in welcher Stufe vor?", "Welche Peripherie-Regel kam in welcher Stufe zum Einsatz?"] },
	{ original: "Forget This",	name: "Vergiss Dies",	id: "forgetThis",	questions: ["What were the displayed digit and color in each stage?"] },
	{ original: "Forget Any Color",	name: "Vergiss Jede Farbe",	id: "ForgetAnyColor",	questions: ["What colors were the cylinders in each stage?", "Which figure was used in each stage?"] },
	{ original: "Forget Me",	name: "Vergiss Mein",	id: "forgetMe",	questions: ["Welche Zahlen waren am Anfang an welcher Position?"] },
	{ original: "Forget Me Now",	name: "Vergiss Mein Jetzt",	id: "ForgetMeNow",	questions: ["Welche Ziffern waren auf dem Display?"] },
	{ original: "Forget Me Not",	name: "Vergiss Mein Nicht",	id: "MemoryV2",	questions: ["Welche Ziffer war in welcher Stufe auf dem Display?"] },
	{ original: "Forget Us Not",	name: "Vergiss Uns Nicht",	id: "forgetUsNot",	questions: ["Für welche Stufe wurde welches Modul entschärft?"] },
	{ original: "Forget Our Voices",	name: "Vergiss Unsere Stimmen",	id: "forgetOurVoices",	questions: ["Wer hat in welcher Stufe was gesagt?"] },
	{ original: "Keypad Magnified",	name: "Vergrößertes Tastenfeld",	id: "keypadMagnified",	questions: ["Wo war die LED?"] },
	{ original: "Gridlock",	name: "Verkehrsstau",	id: "GridlockModule",	questions: ["Was war die Startfarbe?", "Wo war die Startposition?"] },
	{ original: "Crazy Hamburger",	name: "Verrückter Hamburger",	id: "GSCrazyHamburger",	questions: ["Welche Zutaten wurden angezeigt?"] },
	{ original: "Crazy Maze",	name: "Verrückter Irrgarten",	id: "CrazyMazeModule",	questions: ["Wo war die Start- und Zielposition?"] },
	{ original: "Encrypted Equations",	name: "Verschlüsselte Gleichungen",	id: "EncryptedEquationsModule",	questions: ["Welche Formen entsprachen den drei Operanden?"] },
	{ original: "Encrypted Morse",	name: "Verschlüsselte Morsezeichen",	id: "EncryptedMorse",	questions: ["What was the received key?"] },
	{ original: "Encrypted Dice",	name: "Verschlüsselte Würfel",	id: "EncryptedDice",	questions: ["Was wurde in welcher Stufe gewürfelt?"] },
	{ original: "Encrypted Maze",	name: "Verschlüsseltes Labyrinth",	id: "encryptedMaze",	questions: ["Welches Symbol hat sich wierum gedreht?"] },
	{ original: "Encryption Bingo",	name: "Verschlüsselungsbingo",	id: "encryptionBingo",	questions: ["Welche Kodierung kam als erste zum Einsatz?"] },
	{ original: "Shifted Maze",	name: "Verschobenes Labyrinth",	id: "shiftedMaze",	questions: ["Welche Farbe hatten die Markierungen?"] },
	{ original: "Hidden Colors",	name: "Versteckte Farben",	id: "lgndHiddenColors",	questions: ["Welche Farbe hatte die Haupt-LED?"] },
	{ original: "Off Keys",	name: "Verstimmte Tasten",	id: "offKeys",	questions: ["Welche Runen waren auf dem Display?", "Welche Tasten waren in der Tonlage falsch?"] },
	{ original: "Variety",	name: "Vielfalt",	id: "VarietyModule",	questions: ["Welche LED hatte welche Farbe?", "Was war n für die farbigen Drehregler und Glühlampen?", "Welche Ziffern waren auf dem Zifferndisplay?", "Welche Wörter konnten mit dem Buchstabendisplay gebildet werden?", "Welchen Höchstwert hatten die Timer?"] },
	{ original: "Multicolored Switches",	name: "Vielfarbige Schalter",	id: "R4YMultiColoredSwitches",	questions: ["Welche Farbe hatte welche LED in welchem der zwei Zyklen?"] },
	{ original: "Violet Cipher",	name: "Violette Geheimschrift",	id: "violetCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Forest Cipher",	name: "Wald-Geheimschrift",	id: "forestCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "Walking Cube",	name: "Wandernder Würfel",	id: "WalkingCubeModule",	questions: ["Welche Felder wurden vom Würfel abgelaufen?"] },
	{ original: "Warning Signs",	name: "Warnschilder",	id: "warningSigns",	questions: ["Welches Schild kam vor?"] },
	{ original: "Odd One Out",	name: "Was Nicht Passt",	id: "OddOneOutModule",	questions: ["Welche Tasten wurden korrekt betätigt?"] },
	{ original: "White Cipher",	name: "Weiße Geheimschrift",	id: "whiteCipher",	questions: ["Was stand auf welchem Display?"] },
	{ original: "White Arrows",	name: "Weiße Pfeile",	id: "WhiteArrows",	questions: ["What were the non-white arrows?"] },
	{ original: "Wavetapping",	name: "Wellenschlagen",	id: "Wavetapping",	questions: ["Welche Farbe hatten die ersten zwei Stufen?"] },
	{ original: "Guess Who?",	name: "Wer ist es?",	id: "GuessWho",	questions: ["In welchen Farben erschien „YES“?"] },
	{ original: "Not Who’s on First",	name: "Who’s On First Mal Anders",	id: "NotWhosOnFirst",	questions: ["Welche der betätigten Tasten und welche Referenztasten hatten welche Position und welche Aufschrift?", "Welche Zahl wurde in der zweiten Stufe berechnet?"] },
	{ original: "Scramboozled Eggain",	name: "Wieder Mal Das Ei Gerührt",	id: "ScramboozledEggainModule",	questions: ["Wie lauteten die verschlüsselten Wörter?"] },
	{ original: "Bamboozling Button",	name: "Wieder Übern Knopf Gehauen",	id: "bamboozlingButton",	questions: ["Welche Farbe hatte die Taste in welcher Stufe?", "Welche Aufschrift hatte die Taste in welcher Stufe?", "Was wurde in welcher Stufe auf dem Display angezeigt und in welcher Farbe?"] },
	{ original: "Bamboozled Again",	name: "Wieder Übers Ohr Gehauen",	id: "bamboozledAgain",	questions: ["Welche Farben und Aufschriften hatten die Tasten am Anfang?", "Welche Farben und Dekodierergebnisse hatten die Anzeigen auf dem Display?"] },
	{ original: "Semamorse",	name: "Winkermorse",	id: "semamorse",	questions: ["Für den Startwert kam welcher Morsebuchstabe, welcher Winkerbuchstabe und welche Farbe zum Einsatz?"] },
	{ original: "Jumble Cycle",	name: "Wirrwarr-Schiffer",	id: "jumbleCycle",	questions: ["In welche Richtung zeigten die Drehknöpfe?", "Was stand auf den Drehknöpfen?"] },
	{ original: "Wolf, Goat, and Cabbage",	name: "Wolf, Ziege und Kohl",	id: "wolfGoatCabbageModule",	questions: ["Welche Kreaturen kamen vor?", "Wie groß war das Boot?"] },
	{ original: "Five Letter Words",	name: "Wörter aus fünf Buchstaben",	id: "FiveLetterWords",	questions: ["Welche Wörter waren auf dem Display?"] },
	{ original: "Not Word Search",	name: "Wortsuche Mal Anders",	id: "notWordSearch",	questions: ["Welche Konsonanten haben gefehlt?", "Welcher Buchstabe wurde als erstes korrekt eingegeben?"] },
	{ original: "Word Count",	name: "Wortzähler",	id: "wordCount",	questions: ["Welche Zahl war auf dem Display?"] },
	{ original: "Equations X",	name: "X-Gleichungen",	id: "equationsXModule",	questions: ["Welches Symbol war auf dem Display?"] },
	{ original: "Not X01",	name: "X01 Mal Anders",	id: "notX01",	questions: ["Welche Sektorwerte kamen vor?"] },
	{ original: "XmORse Code",	name: "XmORsezeichen",	id: "xmorse",	questions: ["Welche Buchstaben kamen vor?", "Welches Wort wurde entziffert?"] },
	{ original: "xobekuJ ehT",	name: "xobkisuM eiD",	id: "xobekuj",	questions: ["Welcher Song wurde abgespielt?"] },
	{ original: "XY-Ray",	name: "XY-Scanner",	id: "xyRay",	questions: ["Welche Formen wurden gescannt?"] },
	{ original: "Numbers",	name: "Zahlen",	id: "Numbers",	questions: ["Welche 2-stellige Zahl war vorgegeben?"] },
	{ original: "Not Number Pad",	name: "Zahlenfeld Mal Anders",	id: "notNumberPad",	questions: ["Welche Zahlen haben in welchen Stufen geleuchtet?"] },
	{ original: "Numpath",	name: "Zahlenpfad",	id: "numpath",	questions: ["Welche Zahl kam in welcher Farbe vor?"] },
	{ original: "The Number Game",	name: "Zahlenspiel",	id: "TheNumberGame",	questions: ["Was war die höchste Zahl?"] },
	{ original: "Ten-Button Color Code",	name: "Zehn-Tasten-Farbcode",	id: "TenButtonColorCode",	questions: ["Welche Farben hatten die Tasten am Anfang welcher Stufe?"] },
	{ original: "Character Codes",	name: "Zeichencodes",	id: "characterCodes",	questions: ["Welche Zeichen kamen vor?"] },
	{ original: "Character Shift",	name: "Zeichenschieber",	id: "characterShift",	questions: ["Welche Zeichen gab es bei welchem Schieberegler zur Auswahl?"] },
	{ original: "Sign Language",	name: "Zeichensprache",	id: "signLanguage",	questions: ["Welches Wort wurde entziffert?"] },
	{ original: "Sugar Skulls",	name: "Zuckerschädel",	id: "sugarSkulls",	questions: ["Welche Schädel waren zu sehen?"] },
	{ original: "Listening",	name: "Zuhören",	id: "Listening",	questions: ["Welcher Klang war zu hören?"] },
	{ original: "Ingredients",	name: "Zutaten",	id: "ingredients",	questions: ["Welche Zutaten kamen vor und welche wurden verwendet?"] },
	{ original: "Two Bits",	name: "Zwei Bits",	id: "TwoBits",	questions: ["Welche Antwort kam auf die drei korrekten Anfragen?"] },
	{ original: "Cheep Checkout",	name: "Zwitscherkasse",	id: "cheepCheckout",	questions: ["Welche Vögel kamen vor?"] },
	{ original: "Twodoku",	name: "Zwodoku",	id: "TwodokuModule",	questions: ["Welche Ziffern, Symbole und Hervorhebungen waren wo?"] },
];