let SouvenirModuleData = [
	{ original: "100 Levels of Defusal",	name: "100 уровней обезвреживания",	id: "100LevelsOfDefusal",	questions: ["Какие буквы были показаны?"] },
	{ original: "1000 Words",	name: "1000 слов",	id: "OneThousandWords",	questions: ["Какие слова были показаны?"] },
	{ original: "3D Maze",	name: "3D лабиринт",	id: "spwiz3DMaze",	questions: ["Какими буквами был обозначен лабиринт?", "Какое было направление нужной стены?"] },
	{ original: "3D Tunnels",	name: "3D тоннели",	id: "3dTunnels",	questions: ["Какие символы были вашими целями?"] },
	{ original: "4D Tunnels",	name: "4D тоннели",	id: "4dTunnels",	questions: ["What were the goal symbols?"] },
	{ original: "N&Ms",	name: "N и M",	id: "NandMs",	questions: ["What was the label of the correct button?"] },
	{ original: "Third Base",	name: "А меня – Сава",	id: "ThirdBase",	questions: ["Какие слова были показаны?"] },
	{ original: "Chord Qualities",	name: "Аккордные лады",	id: "ChordQualities",	questions: ["Какие ноты присутствовали в начальном аккорде?"] },
	{ original: "Algebra",	name: "Алгебра",	id: "algebra",	questions: ["Какими были первые два уравнения?"] },
	{ original: "USA Maze",	name: "Американский лабиринт",	id: "USA",	questions: ["С какого штата вы начали свой путь?"] },
	{ original: "Discolored Squares",	name: "Бесцветные квадраты",	id: "DiscoloredSquaresModule",	questions: ["В какой позиции находился каждый начальный цвет?"] },
	{ original: "Uncolored Switches",	name: "Бесцветные переключатели",	id: "R4YUncoloredSwitches",	questions: ["Какое было начальное положение переключателей?", "Какого цвета были светодиоды?"] },
	{ original: "Bitmaps",	name: "Битовые изображения",	id: "BitmapsModule",	questions: ["Сколько чёрных/белых пикселей было в каждом квадранте?"] },
	{ original: "Fast Math",	name: "Быстрая математика",	id: "fastMath",	questions: ["Какая пара букв была последней?"] },
	{ original: "Perspective Pegs",	name: "Взгляд на колышки",	id: "spwizPerspectivePegs",	questions: ["Какая была начальная последовательность цветов?"] },
	{ original: "The Gamepad",	name: "Геймпад",	id: "TheGamepadModule",	questions: ["Какие числа были на экране?"] },
	{ original: "Hexamaze",	name: "Гексабиринт",	id: "HexamazeModule",	questions: ["Какого цвета была пешка?"] },
	{ original: "The Hypercube",	name: "Гиперкуб",	id: "TheHypercubeModule",	questions: ["Какие были повороты у куба?"] },
	{ original: "Two Bits",	name: "Два бита",	id: "TwoBits",	questions: ["Какие были три правильных ответа на запросы?"] },
	{ original: "Binary",	name: "Двоичные светодиоды",	id: "Binary",	questions: ["Какое слово было показано?"] },
	{ original: "Bone Apple Tea",	name: "Еле-еле ели ели",	id: "boneAppleTea",	questions: ["Какие фразы были показаны?"] },
	{ original: "Yellow Arrows",	name: "Жёлтые стрелки",	id: "yellowArrowsModule",	questions: ["Какая была буква у начальной строки?"] },
	{ original: "Forget Me Now",	name: "Забудка",	id: "ForgetMeNow",	questions: ["Какие цифры были показаны?"] },
	{ original: "Forget The Colors",	name: "Забудь цвета",	id: "ForgetTheColors",	questions: ["Какая последняя цифра была указана на экране/шестерёнке/синусе на каждом этапе?", "Какая информация с бомбы была применена на каждом этапе?"] },
	{ original: "Railway Cargo Loading",	name: "Загрузка ЖД состава",	id: "RailwayCargoLoading",	questions: ["Какие вагоны были присоединены?", "Какие правила из грузовой таблицы были применены?"] },
	{ original: "Green Arrows",	name: "Зелёные стрелки",	id: "greenArrowsModule",	questions: ["Какое последнее число было показано на экране?"] },
	{ original: "Shape Shift",	name: "Изменение формы",	id: "shapeshift",	questions: ["Какая была начальная фигура?"] },
	{ original: "Skewed Slots",	name: "Искажённые слоты",	id: "SkewedSlotsModule",	questions: ["Какие три цифры были указаны в начале?"] },
	{ original: "Kanji",	name: "Кандзи",	id: "KanjiModule",	questions: ["Какое слово было показано на каждом этапе?"] },
	{ original: "The Button",	name: "Кнопка",	id: "BigButton",	questions: ["Какого цвета был цветной индикатор?"] },
	{ original: "The Code",	name: "Код",	id: "theCodeModule",	questions: ["Какое число было показано на экране?"] },
	{ original: "Monsplode Trading Cards",	name: "Коллекционные карточки по Монсплодам",	id: "monsplodeCards",	questions: ["Какие были имена и издания трёх начальных и последней предложенной карты?"] },
	{ original: "Coordinates",	name: "Координаты",	id: "CoordinatesModule",	questions: ["Какой был размер сетки?"] },
	{ original: "Red Arrows",	name: "Красные стрелки",	id: "redArrowsModule",	questions: ["Какое было начальное число?"] },
	{ original: "Tic Tac Toe",	name: "Крестики-нолики",	id: "TicTacToeModule",	questions: ["Какое было начальное состояние поля?"] },
	{ original: "The Cube",	name: "Куб",	id: "cube",	questions: ["Какие повороты были у куба?"] },
	{ original: "Kudosudoku",	name: "Кудосудоку",	id: "KudosudokuModule",	questions: ["Which squares were initially pre-filled?"] },
	{ original: "Maze",	name: "Лабиринт",	id: "Maze",	questions: ["Где была начальная позиция?"] },
	{ original: "Only Connect",	name: "Лишь Соедините!",	id: "OnlyConnectModule",	questions: ["Какое положение было у египетских иероглифов?"] },
	{ original: "Logic Gates",	name: "Логические элементы",	id: "logicGates",	questions: ["Какие логические элементы присутствовали?"] },
	{ original: "Mazematics",	name: "Матебиринт",	id: "mazematics",	questions: ["Какими были начальная и целевая величины?"] },
	{ original: "Mafia",	name: "Мафия",	id: "MafiaModule",	questions: ["Кто был игроком, но не был крёстным отцом?"] },
	{ original: "Who’s on First",	name: "Меня зовут Авас, а вас?",	id: "WhosOnFirst",	questions: ["Какие слова были показаны на экране?"] },
	{ original: "Multicolored Switches",	name: "Многоцветные переключатели",	id: "R4YMultiColoredSwitches",	questions: ["Какого цвета были светодиоды во всех последовательностях?"] },
	{ original: "Module Maze",	name: "Модульный лабиринт",	id: "ModuleMaze",	questions: ["Какая была начальная иконка?"] },
	{ original: "Monsplode, Fight!",	name: "Монсплоды, в атаку!",	id: "monsplodeFight",	questions: ["Какое существо было показано на экране?", "Какие приёмы были доступны?"] },
	{ original: "Ice Cream",	name: "Мороженое",	id: "iceCreamModule",	questions: ["Кем были ваши посетители?", "Какие вкусы были предложены каждому посетителю?"] },
	{ original: "Sea Shells",	name: "Морские ракушки",	id: "SeaShells",	questions: ["Какие были фразы?"] },
	{ original: "Mouse In The Maze",	name: "Мышь в лабиринте",	id: "MouseInTheMaze",	questions: ["What color was the torus?"] },
	{ original: "Accumulation",	name: "Накопление",	id: "accumulation",	questions: ["Какого цвета были подложка и обрамление на каждом этапе?", "What was the border color?"] },
	{ original: "Directional Button",	name: "Направляющая кнопка",	id: "directionalButton",	questions: ["Сколько раз вы нажали кнопку на каждом этапе?"] },
	{ original: "Not Keypad",	name: "Не клавиатура",	id: "NotKeypad",	questions: ["Какие цвета горели на последнем этапе?", "Какие символы были на горящих кнопках в последнем этапе?"] },
	{ original: "Not the Button",	name: "Не кнопка",	id: "NotButton",	questions: ["Какого цвета была цветная полоска?"] },
	{ original: "Forget Me Not",	name: "Незабудка",	id: "MemoryV2",	questions: ["Какие цифры были показаны на каждом этапе?"] },
	{ original: "Neutralization",	name: "Нейтрализация",	id: "neutralization",	questions: ["Какой объём/цвет был у кислоты?"] },
	{ original: "Uncolored Squares",	name: "Неокрашенные квадраты",	id: "UncoloredSquaresModule",	questions: ["Какие цвета были использованы на первом этапе?"] },
	{ original: "Object Shows",	name: "Обджект-шоу",	id: "objectShows",	questions: ["Какие участники были показаны, но проиграли?"] },
	{ original: "Decolored Squares",	name: "Обесцвеченные квадраты",	id: "DecoloredSquaresModule",	questions: ["Какие цвета отвечали за начальную строку и столбец?"] },
	{ original: "Silly Slots",	name: "Однорукий бандит",	id: "SillySlots",	questions: ["Какие слоты были на каждом этапе?"] },
	{ original: "Orange Arrows",	name: "Оранжевые стрелки",	id: "orangeArrowsModule",	questions: ["Какие первые три стрелки были показаны на каждом этапе?"] },
	{ original: "Orientation Cube",	name: "Ориентация куба",	id: "OrientationCube",	questions: ["Какая была начальная позиция у наблюдателя?"] },
	{ original: "Memory",	name: "Память",	id: "Memory",	questions: ["Что было на экране на каждом этапе?"] },
	{ original: "Switches",	name: "Переключатели",	id: "switchModule",	questions: ["Какая была начальная позиция переключателей?"] },
	{ original: "Recolored Switches",	name: "Перекрашенные переключатели",	id: "R4YRecoloredSwitches",	questions: ["Какого цвета были светодиоды?"] },
	{ original: "Hinges",	name: "Петли",	id: "hinges",	questions: ["Какие петли изначально присутствовали?"] },
	{ original: "Visual Impairment",	name: "Повреждённое зрение",	id: "visual_impairment",	questions: ["Какие были целевые цвета?"] },
	{ original: "Bamboozled Again",	name: "Повторное надувательство",	id: "bamboozledAgain",	questions: ["Какой текст и цвет были на каждой верной кнопке?", "Какой расшифрованный текст и цвет были у каждого показанного сообщения?"] },
	{ original: "Yahtzee",	name: "Покер на костях",	id: "YahtzeeModule",	questions: ["Какой был первый бросок?"] },
	{ original: "Text Field",	name: "Поле из букв",	id: "TextField",	questions: ["Какая буква была показана?"] },
	{ original: "Forget Everything",	name: "Полное забвение",	id: "HexiEvilFMN",	questions: ["Какие цифры были на первом этапе?"] },
	{ original: "Button Sequence",	name: "Последовательность кнопок",	id: "buttonSequencesModule",	questions: ["Сколько раз встречался каждый цвет?"] },
	{ original: "Wire Sequence",	name: "Последовательность проводов",	id: "WireSequence",	questions: ["Сколько проводов было каждого цвета?"] },
	{ original: "Spelling Bee",	name: "Правописание",	id: "spellingBee",	questions: ["Какое слово нужно было прописать?"] },
	{ original: "Adventure Game",	name: "Приключение",	id: "spwizAdventureGame",	questions: ["Which items were present?"] },
	{ original: "Connection Check",	name: "Проверка соединения",	id: "graphModule",	questions: ["Какие пары чисел присутствовали?"] },
	{ original: "Probing",	name: "Прозвонка",	id: "Probing",	questions: ["Какие частоты отсутствовали в каждом проводе?"] },
	{ original: "Listening",	name: "Прослушка",	id: "Listening",	questions: ["Какая запись была проиграна?"] },
	{ original: "Working Title",	name: "Рабочее название",	id: "workingTitle",	questions: ["Какие надписи были показаны?"] },
	{ original: "Pattern Cube",	name: "Развёртка куба",	id: "PatternCubeModule",	questions: ["Какой символ был выделен?"] },
	{ original: "Splitting The Loot",	name: "Разделение добычи",	id: "SplittingTheLootModule",	questions: ["Какой мешок изначально был окрашен?"] },
	{ original: "Varicolored Squares",	name: "Разноцветные квадраты",	id: "VaricoloredSquaresModule",	questions: ["Какой был первый нажатый цвет?"] },
	{ original: "Color Decoding",	name: "Расшифровка цветов",	id: "Color Decoding",	questions: ["Какой узор и каких цветов был на каждом этапе?"] },
	{ original: "Rhythms",	name: "Ритмы",	id: "MusicRhythms",	questions: ["Какой был цвет?"] },
	{ original: "Simon Stages",	name: "Саймон выступает",	id: "simonStages",	questions: ["Какие цвета горели на каждом этапе?", "Какого цвета был индикатор на каждом этапе?"] },
	{ original: "Simon Says",	name: "Саймон говорит",	id: "Simon",	questions: ["Какие цвета горели на последнем этапе?"] },
	{ original: "Simon Screams",	name: "Саймон кричит",	id: "SimonScreamsModule",	questions: ["Какой цвет вспышки был использован на каждом этапе?", "Какие правила были применены на каком этапе?"] },
	{ original: "Simon Speaks",	name: "Саймон общается",	id: "SimonSpeaksModule",	questions: ["Какие атрибуты горящих облаков были необходимы?"] },
	{ original: "Simon States",	name: "Саймон утверждает",	id: "SimonV2",	questions: ["Какие цвета горели на первых трёх этапах?"] },
	{ original: "Cheap Checkout",	name: "Свободная касса!",	id: "CheapCheckoutModule",	questions: ["Сколько конкретно денег было заплачено?"] },
	{ original: "LED Grid",	name: "Сетка светодиодов",	id: "ledGrid",	questions: ["Сколько светодиодов не горели?"] },
	{ original: "Burglar Alarm",	name: "Сигнализация",	id: "burglarAlarm",	questions: ["Какие цифры были показаны?"] },
	{ original: "Juxtacolored Squares",	name: "Смежные цветные квадраты",	id: "JuxtacoloredSquaresModule",	questions: ["Какой был цвет каждого квадрата?"] },
	{ original: "Sorting",	name: "Сортировка",	id: "sorting",	questions: ["Какие позиции участвовали в последней замене чисел?"] },
	{ original: "Souvenir",	name: "Сувенир",	id: "SouvenirModule",	questions: ["О каком модуле был первый вопрос на другом Сувенире?"] },
	{ original: "Creation",	name: "Творение",	id: "CreationModule",	questions: ["Какая была погода в каждый день?"] },
	{ original: "Murder",	name: "Убийство",	id: "murder",	questions: ["Кем были подозреваемые и какие оружия были найдены?", "Где было найдено тело?"] },
	{ original: "Corners",	name: "Углы",	id: "CornersModule",	questions: ["Каких цветов были углы?"] },
	{ original: "Forget’s Ultimate Showdown",	name: "Финальная битва забвения",	id: "ForgetsUltimateShowdownModule",	questions: ["Какое было исходное число?", "Какое число было снизу?", "Какой был ответ?", "Какие методы шифрования были использованы?"] },
	{ original: "Purple Arrows",	name: "Фиолетовые стрелки",	id: "purpleArrowsModule",	questions: ["Какое слово было зашифровано?"] },
	{ original: "Color One Two",	name: "Цвет раз два",	id: "colorOneTwo",	questions: ["Какие цвета были на светодиодах?"] },
	{ original: "Color Morse",	name: "Цветная азбука Морзе",	id: "ColorMorseModule",	questions: ["Какие цвета были у светодиодов?", "Какие символы были представлены светодиодами?"] },
	{ original: "Colour Flash",	name: "Цветная вспышка",	id: "ColourFlash",	questions: ["Какого цвета было последнее слово в последовательности?"] },
	{ original: "Colored Squares",	name: "Цветные квадраты",	id: "ColoredSquaresModule",	questions: ["Какого цвета была первая группа?"] },
	{ original: "Colored Keys",	name: "Цветные кнопки",	id: "lgndColoredKeys",	questions: ["Какое слово и какого цвета было показано?", "Какие цвета и буквы были на каждой клавише?"] },
	{ original: "Colored Switches",	name: "Цветные переключатели",	id: "ColoredSwitchesModule",	questions: ["Какое было начальное положение переключателей?"] },
	{ original: "Chess",	name: "Шахматы",	id: "ChessModule",	questions: ["Какие координаты присутствовали на модуле?"] },
	{ original: "Braille",	name: "Шрифт Брайля",	id: "BrailleModule",	questions: ["Какие были буквы (паттерны)?"] },
	{ original: "0",	name: "0",	id: "0",	questions: ["Какое число было изначально показано?"] },
	{ original: "The 1, 2, 3 Game",	name: "The 1, 2, 3 Game",	id: "TheOneTwoThreeGame",	questions: ["What was the opponent’s avatar and name?"] },
	{ original: "1D Chess",	name: "1D Chess",	id: "1DChess",	questions: ["Какие были ходы у вас и Rustmate?"] },
	{ original: "21",	name: "21",	id: "TwennyWan",	questions: ["What was the displayed number?"] },
	{ original: "3D Tap Code",	name: "3D Tap Code",	id: "3DTapCodeModule",	questions: ["Какое слово было получено?"] },
	{ original: "3 LEDs",	name: "3 LEDs",	id: "threeLEDsModule",	questions: ["Какое было исходное состояние у светодиодов?"] },
	{ original: "3N+1",	name: "3N+1",	id: "threeNPlusOne",	questions: ["Какое число было изначально показано?"] },
	{ original: "64",	name: "64",	id: "64",	questions: ["Какое число было показано?"] },
	{ original: "7",	name: "7",	id: "7",	questions: ["Какой был цвет у светодиода на каждом этапе?", "Какие были начальные величины у каждого цветового канала?"] },
	{ original: "9-Ball",	name: "9-Ball",	id: "GSNineBall",	questions: ["Какие числа были на каждом шаре?"] },
	{ original: "Abyss",	name: "Abyss",	id: "GSAbyss",	questions: ["Какие символы были показаны?"] },
	{ original: "Affine Cycle",	name: "Affine Cycle",	id: "affineCycle",	questions: ["Какое было исходное сообщение и ответ?", "What was written on each dial?"] },
	{ original: "Alcoholic Rampage",	name: "Alcoholic Rampage",	id: "alcoholicRampageModule",	questions: ["Which mercenaries were displayed?"] },
	{ original: "A Letter",	name: "A Letter",	id: "LetterModule",	questions: ["Какая была начальная буква?"] },
	{ original: "Alfa-Bravo",	name: "Alfa-Bravo",	id: "alfa_bravo",	questions: ["Какая буква была нажата последней?", "Какие буквы были слева и справа от последней нажатой?", "Какая последняя цифра была на маленьком экране?"] },
	{ original: "Algorithmia",	name: "Algorithmia",	id: "algorithmia",	questions: ["Какие были начальная и целевая позиции?", "Какого цвета был светодиод?", "Какие числа присутствовали в зерне?"] },
	{ original: "Alphabetical Ruling",	name: "Alphabetical Ruling",	id: "alphabeticalRuling",	questions: ["Какие буквы и числа были показаны на каждом этапе?"] },
	{ original: "Alphabet Numbers",	name: "Alphabet Numbers",	id: "alphabetNumbers",	questions: ["Какие числа были на кнопках на каждом этапе?"] },
	{ original: "Alphabet Tiles",	name: "Alphabet Tiles",	id: "AlphabetTiles",	questions: ["Какие буквы были показаны в каждом цикле?", "Какая буква отсутствовала?"] },
	{ original: "Alpha-Bits",	name: "Alpha-Bits",	id: "alphaBits",	questions: ["Какие символы были показаны на каждом экране?"] },
	{ original: "A Message",	name: "A Message",	id: "AMessage",	questions: ["What was the received message?"] },
	{ original: "Amusement Parks",	name: "Amusement Parks",	id: "amusementParks",	questions: ["Какие аттракционы были доступны?"] },
	{ original: "Ángel Hernández",	name: "Ángel Hernández",	id: "AngelHernandezModule",	questions: ["Какая буква была показана поднятой кнопкой на каждом этапе?"] },
	{ original: "The Arena",	name: "The Arena",	id: "TheArena",	questions: ["What was the maximum weapon damage of the attack phase?", "What enemies were present in the defend phase?", "What numbers were present in the grab phase?"] },
	{ original: "Arithmelogic",	name: "Arithmelogic",	id: "arithmelogic",	questions: ["Какой символ был на кнопке отправки?"] },
	{ original: "Arithmetic Cipher",	name: "Arithmetic Cipher",	id: "ArithmeticCipherModule",	questions: ["What was on each screen?"] },
	{ original: "ASCII Maze",	name: "ASCII Maze",	id: "asciiMaze",	questions: ["Какие символы были показаны?"] },
	{ original: "A Square",	name: "A Square",	id: "ASquareModule",	questions: ["Какие были цвета-индексы?", "Какие цвета были введены?"] },
	{ original: "Audio Morse",	name: "Audio Morse",	id: "lgndAudioMorse",	questions: ["Что было передано по Морзе?"] },
	{ original: "The Azure Button",	name: "The Azure Button",	id: "AzureButtonModule",	questions: ["What were T and the other displayed cards?", "What was M?", "What were the arrows?"] },
	{ original: "Bakery",	name: "Bakery",	id: "bakery",	questions: ["Какая выпечка присутствовала?"] },
	{ original: "Bamboozling Button",	name: "Bamboozling Button",	id: "bamboozlingButton",	questions: ["Какого цвета была кнопка на каждом этапе?", "Какие надписи были на кнопке на каждом этапе?", "Какие сообщения были на экране на каждом этапе и какого цвета?"] },
	{ original: "Bar Charts",	name: "Bar Charts",	id: "GSBarCharts",	questions: ["Какая была высота, цвет и надпись у каждого столбца?", "Какая была категория?", "Какая была единица измерения?"] },
	{ original: "Barcode Cipher",	name: "Barcode Cipher",	id: "BarcodeCipherModule",	questions: ["Какое число было на экране?", "Какой компонент бомбы был представлен каждым штрих кодом?", "Какой был ответ для каждого штрих кода?"] },
	{ original: "Bartending",	name: "Bartending",	id: "BartendingModule",	questions: ["Какие ингредиенты были в какой позиции?"] },
	{ original: "Beans",	name: "Beans",	id: "beans",	questions: ["Каких цветов были съеденные бобы?", "Какие бобы были Wobbly?"] },
	{ original: "Bean Sprouts",	name: "Bean Sprouts",	id: "beanSprouts",	questions: ["Каких цветов были съеденные ростки?", "Где были съеденные бобы?"] },
	{ original: "Big Bean",	name: "Big Bean",	id: "bigBean",	questions: ["Какого цвета был боб и был ли он Wobbly?"] },
	{ original: "Big Circle",	name: "Big Circle",	id: "BigCircle",	questions: ["Which direction was the circle spinning?"] },
	{ original: "Binary Shift",	name: "Binary Shift",	id: "binary_shift",	questions: ["Какие были начальные числа?", "Какое число было выбрано на каждом этапе?"] },
	{ original: "Black Cipher",	name: "Black Cipher",	id: "blackCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Blindfolded Yahtzee",	name: "Blindfolded Yahtzee",	id: "GSBlindfoldedYahtzee",	questions: ["Which rolls did the module claim?"] },
	{ original: "Blind Maze",	name: "Blind Maze",	id: "BlindMaze",	questions: ["Какого цвета были кнопки?"] },
	{ original: "Blinking Notes",	name: "Blinking Notes",	id: "blinkingNotes",	questions: ["Какая песня была проиграна?"] },
	{ original: "Blinkstop",	name: "Blinkstop",	id: "blinkstopModule",	questions: ["Сколько раз мигал светодиод?", "Каким цветом светодиод мигал наименьшее кол-во раз?"] },
	{ original: "Blockbusters",	name: "Blockbusters",	id: "blockbusters",	questions: ["What letters were in the leftmost column at the start?"] },
	{ original: "Blue Arrows",	name: "Blue Arrows",	id: "blueArrowsModule",	questions: ["Какие символы были на экране?"] },
	{ original: "The Blue Button",	name: "The Blue Button",	id: "BlueButtonModule",	questions: ["What were D, E, F, G, H, M, N, P, Q, and X?"] },
	{ original: "Blue Cipher",	name: "Blue Cipher",	id: "blueCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Blue Huffman Cipher",	name: "Blue Huffman Cipher",	id: "BlueHuffmanCipherModule",	questions: ["What was on each screen?"] },
	{ original: "Bob Barks",	name: "Bob Barks",	id: "ksmBobBarks",	questions: ["Какие были названия индикаторов?", "В какой последовательности загорались кнопки?"] },
	{ original: "Boggle",	name: "Boggle",	id: "boggle",	questions: ["Какие исходные буквы были показаны?"] },
	{ original: "Bomb Diffusal",	name: "Bomb Diffusal",	id: "bombDiffusal",	questions: ["Какой был номер лицензии?"] },
	{ original: "Boob Tube",	name: "Boob Tube",	id: "boobTubeModule",	questions: ["Какие слова были показаны?"] },
	{ original: "Book of Mario",	name: "Book of Mario",	id: "BookOfMarioModule",	questions: ["Кто сказал что-то и на каком этапе?", "Какие цитаты были у персонажей?"] },
	{ original: "Boolean Wires",	name: "Boolean Wires",	id: "booleanWires",	questions: ["Какой оператор был ответом на каждом этапе?"] },
	{ original: "Boomtar the Great",	name: "Boomtar the Great",	id: "boomtarTheGreat",	questions: ["Какое было первое и второе правило?"] },
	{ original: "Bordered Keys",	name: "Bordered Keys",	id: "borderedKeys",	questions: ["Какие были цвет рамки, показанное число, цвет клавиши, надпись и цвет надписи при каждом нажатии?"] },
	{ original: "Bottom Gear",	name: "Bottom Gear",	id: "GSBottomGear",	questions: ["Какой твит был в начале?"] },
	{ original: "Boxing",	name: "Boxing",	id: "boxing",	questions: ["Какие участники и замены(имена и фамилии) были показаны?", "Кто имел какую силу удара?"] },
	{ original: "Breakfast Egg",	name: "Breakfast Egg",	id: "breakfastEgg",	questions: ["Какие цвета были показаны на яйце?"] },
	{ original: "Broken Guitar Chords",	name: "Broken Guitar Chords",	id: "BrokenGuitarChordsModule",	questions: ["Какой аккорд был показан?", "Которая струна была сломана?"] },
	{ original: "Brown Cipher",	name: "Brown Cipher",	id: "brownCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "The Bulb",	name: "The Bulb",	id: "TheBulbModule",	questions: ["Was the bulb initially lit?"] },
	{ original: "Burger Alarm",	name: "Burger Alarm",	id: "burgerAlarm",	questions: ["Какие цифры были показаны?", "Какие были номера заказов?"] },
	{ original: "Buttonage",	name: "Buttonage",	id: "buttonageModule",	questions: ["Сколько было каждого цвета и каждой рамки?", "Сколько было специальных кнопок?", "На скольки кнопках было P?"] },
	{ original: "Cacti’s Conundrum",	name: "Cacti’s Conundrum",	id: "CactusPConundrum",	questions: ["Какие цвета были на светодиоде?"] },
	{ original: "Caesar Cycle",	name: "Caesar Cycle",	id: "caesarCycle",	questions: ["Какое было сообщение и ответ?", "What was written on each dial?"] },
	{ original: "Caesar Psycho",	name: "Caesar Psycho",	id: "caesarPsycho",	questions: ["Какие текст и цвет были на верхнем экране на каждом этапе?"] },
	{ original: "Caesar’s Maths",	name: "Caesar’s Maths",	id: "caesarsMaths",	questions: ["What were the colors of each LED?"] },
	{ original: "Calendar",	name: "Calendar",	id: "calendar",	questions: ["What was the holiday?"] },
	{ original: "CA-RPS",	name: "CA-RPS",	id: "caRPS",	questions: ["Какие были начальные цвета?"] },
	{ original: "Cartinese",	name: "Cartinese",	id: "cartinese",	questions: ["Какой текст был проигран каждой кнопкой?", "Какого цвета была каждая кнопка?"] },
	{ original: "Catchphrase",	name: "Catchphrase",	id: "catchphrase",	questions: ["Каких цветов были панели?"] },
	{ original: "Challenge & Contact",	name: "Challenge & Contact",	id: "challengeAndContact",	questions: ["What were the displayed letters?"] },
	{ original: "Character Codes",	name: "Character Codes",	id: "characterCodes",	questions: ["Какие были символы?"] },
	{ original: "Character Shift",	name: "Character Shift",	id: "characterShift",	questions: ["Какие были символы на ползунках?"] },
	{ original: "Character Slots",	name: "Character Slots",	id: "characterSlots",	questions: ["Кто был показан в каждом слоте на каждом этапе?"] },
	{ original: "Cheat Checkout",	name: "Cheat Checkout",	id: "kataCheatCheckout",	questions: ["What was the cryptocurrency?", "What was the site and hack method for each hack?"] },
	{ original: "Cheep Checkout",	name: "Cheep Checkout",	id: "cheepCheckout",	questions: ["Какие птицы присутствовали?"] },
	{ original: "Chinese Counting",	name: "Chinese Counting",	id: "chineseCounting",	questions: ["Каких цветов были светодиоды?"] },
	{ original: "Chinese Remainder Theorem",	name: "Chinese Remainder Theorem",	id: "ChineseRemainderTheoremModule",	questions: ["Какие были уравнения?"] },
	{ original: "↻↺",	name: "↻↺",	id: "clockCounter",	questions: ["Какие стрелки были показаны?"] },
	{ original: "Codenames",	name: "Codenames",	id: "codenames",	questions: ["Какие слова были введены?"] },
	{ original: "Coffee Beans",	name: "Coffee Beans",	id: "coffeeBeans",	questions: ["Какие были движения?"] },
	{ original: "Coffeebucks",	name: "Coffeebucks",	id: "coffeebucks",	questions: ["Какое кофе было подано последним?"] },
	{ original: "Coinage",	name: "Coinage",	id: "Coinage",	questions: ["Какая монета была подкинута?"] },
	{ original: "Color Addition",	name: "Color Addition",	id: "colorAddition",	questions: ["Какие были три числа?"] },
	{ original: "Color Braille",	name: "Color Braille",	id: "ColorBrailleModule",	questions: ["Какого цвета была каждая точка?"] },
	{ original: "Colors Maximization",	name: "Colors Maximization",	id: "colors_maximization",	questions: ["Сколько было кнопок каждого цвета?"] },
	{ original: "Coloured Cubes",	name: "Coloured Cubes",	id: "ColouredCubes",	questions: ["Какие цвета куба и индикатора этапа были на каждом этапе?"] },
	{ original: "Coloured Cylinder",	name: "Coloured Cylinder",	id: "colouredCylinder",	questions: ["Какими цветами мигал цилиндр?"] },
	{ original: "Concentration",	name: "Concentration",	id: "ConcentrationModule",	questions: ["Как карты были выложены в самом начале?"] },
	{ original: "Conditional Buttons",	name: "Conditional Buttons",	id: "conditionalButtons",	questions: ["Какие цвета были на каждой кнопке?"] },
	{ original: "Connected Monitors",	name: "Connected Monitors",	id: "ConnectedMonitorsModule",	questions: ["Какие числа были изначально показаны?", "Каких цветов были индикаторы?"] },
	{ original: "Coordination",	name: "Coordination",	id: "Coordination",	questions: ["What was the label and position of the starting coordinate?"] },
	{ original: "Coral Cipher",	name: "Coral Cipher",	id: "coralCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Cornflower Cipher",	name: "Cornflower Cipher",	id: "cornflowerCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Cosmic",	name: "Cosmic",	id: "CosmicModule",	questions: ["Какое было исходное число?"] },
	{ original: "Crazy Hamburger",	name: "Crazy Hamburger",	id: "GSCrazyHamburger",	questions: ["Какие ингредиенты были показаны?"] },
	{ original: "Crazy Maze",	name: "Crazy Maze",	id: "CrazyMazeModule",	questions: ["Где были начало и цель?"] },
	{ original: "Cream Cipher",	name: "Cream Cipher",	id: "creamCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Crimson Cipher",	name: "Crimson Cipher",	id: "crimsonCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Critters",	name: "Critters",	id: "CrittersModule",	questions: ["Какой был цвет?"] },
	{ original: "Cruel Binary",	name: "Cruel Binary",	id: "CruelBinary",	questions: ["Какое слово было показано?"] },
	{ original: "Cruel Keypads",	name: "Cruel Keypads",	id: "CruelKeypads",	questions: ["What symbols were on the keys in each stage?", "What was the color of the bar in each stage?"] },
	{ original: "The cRule",	name: "The cRule",	id: "the_cRule",	questions: ["Which cells were prefilled at the start?", "Which symbol pair appeared where?"] },
	{ original: "Cryptic Cycle",	name: "Cryptic Cycle",	id: "crypticCycle",	questions: ["Какое было сообщение и ответ?", "What was written on each dial?"] },
	{ original: "Cryptic Keypad",	name: "Cryptic Keypad",	id: "GSCrypticKeypad",	questions: ["Какие символы и стороны света были указаны на клавишах?"] },
	{ original: "Cursed Double-Oh",	name: "Cursed Double-Oh",	id: "CursedDoubleOhModule",	questions: ["Какая была первая цифра начального числа?"] },
	{ original: "Customer Identification",	name: "Customer Identification",	id: "xelCustomerIdentification",	questions: ["Какие посетители были показаны?"] },
	{ original: "The Cyan Button",	name: "The Cyan Button",	id: "CyanButtonModule",	questions: ["Where was the button at each stage?"] },
	{ original: "DACH Maze",	name: "DACH Maze",	id: "DACH",	questions: ["Откуда вы отправились?"] },
	{ original: "Deaf Alley",	name: "Deaf Alley",	id: "deafAlleyModule",	questions: ["Какой символ был сгенерирован?"] },
	{ original: "The Deck of Many Things",	name: "The Deck of Many Things",	id: "deckOfManyThings",	questions: ["What deck did the first card belong to?"] },
	{ original: "Decolour Flash",	name: "Decolour Flash",	id: "DecolourFlashModule",	questions: ["Какие были слова и цвета у каждой цели?"] },
	{ original: "Denial Displays",	name: "Denial Displays",	id: "DenialDisplaysModule",	questions: ["Что изначально было на экранах?"] },
	{ original: "DetoNATO",	name: "DetoNATO",	id: "Detonato",	questions: ["Какое слово было показано на каждом этапе?"] },
	{ original: "Devilish Eggs",	name: "Devilish Eggs",	id: "devilishEggs",	questions: ["Какие повороты были у яиц?", "Какие числа и буквы были указаны на призме?"] },
	{ original: "Dialtones",	name: "Dialtones",	id: "xelDialtones",	questions: ["Какие тональные сигналы были проиграны?"] },
	{ original: "Digisibility",	name: "Digisibility",	id: "digisibility",	questions: ["Какие числа были на кнопках?"] },
	{ original: "Digit String",	name: "Digit String",	id: "digitString",	questions: ["Какая строка цифр была в начале?"] },
	{ original: "Dimension Disruption",	name: "Dimension Disruption",	id: "dimensionDisruption",	questions: ["Какие символы можно было рассмотреть на модуле?"] },
	{ original: "Disordered Keys",	name: "Disordered Keys",	id: "disorderedKeys",	questions: ["Какой информации недоставало и какие раскрытый/нераскрытый цвет клавиши, надпись и цвет надписи были на каждом ключе?"] },
	{ original: "Divided Squares",	name: "Divided Squares",	id: "DividedSquaresModule",	questions: ["What color was shown when the correct square was pressed?"] },
	{ original: "Divisible Numbers",	name: "Divisible Numbers",	id: "divisibleNumbers",	questions: ["Какие числа были на каждом этапе?"] },
	{ original: "DNA Mutation",	name: "DNA Mutation",	id: "DNAMutation",	questions: ["What were the DNA strands’ colors?", "What were the given nucleotides’ letters and colors?"] },
	{ original: "Doofenshmirtz Evil Inc.",	name: "Doofenshmirtz Evil Inc.",	id: "doofenshmirtzEvilIncModule",	questions: ["What jingles played?", "What images were shown?"] },
	{ original: "Double Arrows",	name: "Double Arrows",	id: "doubleArrows",	questions: ["Где была начальная позиция?", "Какие кнопки двигали в каком направлении?"] },
	{ original: "Double Color",	name: "Double Color",	id: "doubleColor",	questions: ["Какой был цвет экрана на каждом этапе?"] },
	{ original: "Double Digits",	name: "Double Digits",	id: "doubleDigitsModule",	questions: ["Какие числа были на экранах?"] },
	{ original: "Double Expert",	name: "Double Expert",	id: "doubleExpert",	questions: ["Какое было начальное ключевое число?"] },
	{ original: "Double Listening",	name: "Double Listening",	id: "doubleListening",	questions: ["Какие звуки были проиграны?"] },
	{ original: "Double Screen",	name: "Double Screen",	id: "doubleScreenModule",	questions: ["Каких цветов были экраны на каждом этапе?"] },
	{ original: "Dr. Doctor",	name: "Dr. Doctor",	id: "DrDoctorModule",	questions: ["Какие болезни и симптомы присутствовали на модуле?"] },
	{ original: "Dreamcipher",	name: "Dreamcipher",	id: "ksmDreamcipher",	questions: ["Какое слово было расшифровано?"] },
	{ original: "The Duck",	name: "The Duck",	id: "theDuck",	questions: ["What was the color of the curtain?", "How was the duck approached?"] },
	{ original: "Dumb Waiters",	name: "Dumb Waiters",	id: "dumbWaiters",	questions: ["Какие игроки присутствовали?"] },
	{ original: "Earthbound",	name: "Earthbound",	id: "EarthboundModule",	questions: ["Какой был фон?", "Какой монстр был показан?"] },
	{ original: "eeB gnillepS",	name: "eeB gnillepS",	id: "eeBgnilleps",	questions: ["Какое слово нужно было прописать?"] },
	{ original: "Eight",	name: "Eight",	id: "eight",	questions: ["Какая была последняя цифра на маленьком экране?", "Какая была позиция у последней сломанной цифры?", "Какие были две итоговые последние цифры?", "Какое было последнее показанное число?"] },
	{ original: "Elder Futhark",	name: "Elder Futhark",	id: "elderFuthark",	questions: ["Какие руны были показаны?"] },
	{ original: "Emoji",	name: "Emoji",	id: "emoji",	questions: ["Какие были эмодзи?"] },
	{ original: "ƎNA Cipher",	name: "ƎNA Cipher",	id: "enaCipher",	questions: ["Какое было ключевое слово, ключ транспозиции и зашифрованное слово?"] },
	{ original: "Encrypted Dice",	name: "Encrypted Dice",	id: "EncryptedDice",	questions: ["Какие числа были на костях на каждом этапе?"] },
	{ original: "Encrypted Equations",	name: "Encrypted Equations",	id: "EncryptedEquationsModule",	questions: ["Какие были основные фигуры у трёх переменных?"] },
	{ original: "Encrypted Hangman",	name: "Encrypted Hangman",	id: "encryptedHangman",	questions: ["Какой модуль был зашифрован и каким методом?"] },
	{ original: "Encrypted Maze",	name: "Encrypted Maze",	id: "encryptedMaze",	questions: ["Какой символ крутился в какую сторону?"] },
	{ original: "Encrypted Morse",	name: "Encrypted Morse",	id: "EncryptedMorse",	questions: ["Какое сообщение было получено и отправлено?"] },
	{ original: "Encryption Bingo",	name: "Encryption Bingo",	id: "encryptionBingo",	questions: ["Какая кодировка была применена первой?"] },
	{ original: "English Entries",	name: "English Entries",	id: "EnglishEntries",	questions: ["What was the displayed quote?"] },
	{ original: "Enigma Cycle",	name: "Enigma Cycle",	id: "enigmaCycle",	questions: ["Какое было сообщение и ответ?", "What was written on each dial?"] },
	{ original: "Entry Number Four",	name: "Entry Number Four",	id: "GSEntryNumberFour",	questions: ["Какие числа были показаны, ожидаемый четвёртый ввод и коэффициент константы?"] },
	{ original: "Entry Number One",	name: "Entry Number One",	id: "GSEntryNumberOne",	questions: ["Какие числа были показаны, ожидаемый первый ввод и коэффициент константы?"] },
	{ original: "Equations X",	name: "Equations X",	id: "equationsXModule",	questions: ["Какой символ был показан?"] },
	{ original: "Error Codes",	name: "Error Codes",	id: "errorCodes",	questions: ["Какой был активный код ошибки?"] },
	{ original: "Etterna",	name: "Etterna",	id: "etterna",	questions: ["На каком бите была введена каждая стрелка?"] },
	{ original: "Exoplanets",	name: "Exoplanets",	id: "exoplanets",	questions: ["Какая была начальная и целевая планета и цифра?"] },
	{ original: "Factoring Maze",	name: "Factoring Maze",	id: "factoringMaze",	questions: ["Какие простые числа были использованы?"] },
	{ original: "Factory Maze",	name: "Factory Maze",	id: "factoryMaze",	questions: ["С какой комнаты вы начали свой путь?"] },
	{ original: "Faerie Fires",	name: "Faerie Fires",	id: "FaerieFiresModule",	questions: ["What were the faeries' colors and pitches?"] },
	{ original: "Fast Playfair Cipher",	name: "Fast Playfair Cipher",	id: "FastPlayfairCipher",	questions: ["What was the last displayed message?"] },
	{ original: "Faulty Buttons",	name: "Faulty Buttons",	id: "GSFaultyButtons",	questions: ["На какую кнопку ссылалась каждая кнопка?"] },
	{ original: "Faulty RGB Maze",	name: "Faulty RGB Maze",	id: "faultyrgbMaze",	questions: ["Где были выход и ключи лабиринта?", "Какой был номер у каждого лабиринта?"] },
	{ original: "Find The Date",	name: "Find The Date",	id: "DateFinder",	questions: ["What were the day, month, and year for each stage?"] },
	{ original: "Five Letter Words",	name: "Five Letter Words",	id: "FiveLetterWords",	questions: ["Какие слова были показаны?"] },
	{ original: "FizzBuzz",	name: "FizzBuzz",	id: "fizzBuzzModule",	questions: ["Какие числа были показаны?"] },
	{ original: "Flags",	name: "Flags",	id: "FlagsModule",	questions: ["Какие были флаги стран, главный флаг и показанное число?"] },
	{ original: "Flashing Arrows",	name: "Flashing Arrows",	id: "flashingArrowsModule",	questions: ["Какое число было показано на экране?", "Какие цвета мигали на соответствующих стрелках?"] },
	{ original: "Flashing Lights",	name: "Flashing Lights",	id: "flashingLights",	questions: ["Сколько раз каждый цвет загорелся на каждом светодиоде"] },
	{ original: "Flavor Text EX",	name: "Flavor Text EX",	id: "FlavorTextCruel",	questions: ["От какого модуля был приведён флейвор текст на каждом этапе?"] },
	{ original: "Flyswatting",	name: "Flyswatting",	id: "flyswatting",	questions: ["Какие мухи присутствовали, но не в решении?"] },
	{ original: "Follow Me",	name: "Follow Me",	id: "FollowMe",	questions: ["Какие направления мигали?"] },
	{ original: "Forest Cipher",	name: "Forest Cipher",	id: "forestCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Forget Any Color",	name: "Forget Any Color",	id: "ForgetAnyColor",	questions: ["Каких цветов были цилиндры на каждом этапе?", "Какая строка была применена на каждом этапе?"] },
	{ original: "Forget Me",	name: "Forget Me",	id: "forgetMe",	questions: ["Какие числа были в какой позиции в начале пазла?"] },
	{ original: "Forget Our Voices",	name: "Forget Our Voices",	id: "forgetOurVoices",	questions: ["What was said by whom each stage?"] },
	{ original: "Forget This",	name: "Forget This",	id: "forgetThis",	questions: ["What was the displayed character in each stage?", "What was the LED color in each stage?"] },
	{ original: "Forget Us Not",	name: "Forget Us Not",	id: "forgetUsNot",	questions: ["Which module was solved for each stage?"] },
	{ original: "Free Parking",	name: "Free Parking",	id: "freeParking",	questions: ["Какой был жетон игрока?"] },
	{ original: "The French Republican Calendar",	name: "The French Republican Calendar",	id: "FrenchRepublicanCalendar",	questions: ["What was the color of the LED?"] },
	{ original: "Functions",	name: "Functions",	id: "qFunctions",	questions: ["Какая последняя цифра была у результата первого запроса?", "Какие числа и буквы были показаны снизу?"] },
	{ original: "The Fuse Box",	name: "The Fuse Box",	id: "FuseBox",	questions: ["What colors flashed?", "What arrows were correct?"] },
	{ original: "Gadgetron Vendor",	name: "Gadgetron Vendor",	id: "lgndGadgetronVendor",	questions: ["Какие оружия были показаны на модуле?"] },
	{ original: "Game of Life Cruel",	name: "Game of Life Cruel",	id: "GameOfLifeCruel",	questions: ["Which color combinations occurred?"] },
	{ original: "Garfield Kart",	name: "Garfield Kart",	id: "garfieldKart",	questions: ["Какое было название трассы?", "Сколько было частей пазла?"] },
	{ original: "The Garnet Thief",	name: "The Garnet Thief",	id: "theGarnetThief",	questions: ["Which faction did each competitor claim to have chosen?"] },
	{ original: "Ghost Movement",	name: "Ghost Movement",	id: "ghostMovement",	questions: ["Где был Pac-Man и призраки?"] },
	{ original: "Giants Cipher",	name: "Giants Cipher",	id: "GiantsCipher",	questions: ["What was the displayed keyword?"] },
	{ original: "Girlfriend",	name: "Girlfriend",	id: "Girlfriend",	questions: ["Какой язык был выбран?"] },
	{ original: "The Glitched Button",	name: "The Glitched Button",	id: "GlitchedButtonModule",	questions: ["What was the cycling bit sequence?"] },
	{ original: "Goofy’s Game",	name: "Goofy’s Game",	id: "goofysgame",	questions: ["Какие числа были показаны в Морзе?"] },
	{ original: "Grand Piano",	name: "Grand Piano",	id: "grandPiano",	questions: ["Какие ноты были даны?"] },
	{ original: "The Gray Button",	name: "The Gray Button",	id: "GrayButtonModule",	questions: ["What were the coordinates on the display?"] },
	{ original: "Gray Cipher",	name: "Gray Cipher",	id: "grayCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "The Great Void",	name: "The Great Void",	id: "greatVoid",	questions: ["What were the digits and colors?"] },
	{ original: "The Green Button",	name: "The Green Button",	id: "GreenButtonModule",	questions: ["What was the submitted word?"] },
	{ original: "Green Cipher",	name: "Green Cipher",	id: "greenCipher",	questions: ["Что было на каждом этапе?"] },
	{ original: "Gridlock",	name: "Gridlock",	id: "GridlockModule",	questions: ["Какой был начальный цвет?", "Где было начало и конец?"] },
	{ original: "Grocery Store",	name: "Grocery Store",	id: "groceryStore",	questions: ["Какой первый товар был показан?"] },
	{ original: "Gryphons",	name: "Gryphons",	id: "gryphons",	questions: ["Какое имя и возраст были у грифона??"] },
	{ original: "Guess Who?",	name: "Guess Who?",	id: "GuessWho",	questions: ["Сколько раз горело YES?"] },
	{ original: "Gyromaze",	name: "Gyromaze",	id: "gyromaze",	questions: ["Каких цветов были светодиоды?"] },
	{ original: "h",	name: "h",	id: "Averageh",	questions: ["Какая буква передавалась модулем?"] },
	{ original: "Halli Galli",	name: "Halli Galli",	id: "halliGalli",	questions: ["Каких фруктов было пять?", "What were the relevant counts?"] },
	{ original: "Hereditary Base Notation",	name: "Hereditary Base Notation",	id: "hereditaryBaseNotationModule",	questions: ["Какое число было на нижнем экране?"] },
	{ original: "The Hexabutton",	name: "The Hexabutton",	id: "hexabutton",	questions: ["What color was the button when held?", "What Morse Code letter was transmitted?"] },
	{ original: "hexOrbits",	name: "hexOrbits",	id: "hexOrbits",	questions: ["What shapes were displayed?"] },
	{ original: "hexOS",	name: "hexOS",	id: "hexOS",	questions: ["Какие буквы или фраза были расшифрованы??", "Какие трёхзначные числа повторялись на экране?", "Какие значения были у ритмов?"] },
	{ original: "Hickory Dickory Dock",	name: "Hickory Dickory Dock",	id: "hickoryDickoryDockModule",	questions: ["What times were shown when the clock struck?"] },
	{ original: "Hidden Colors",	name: "Hidden Colors",	id: "lgndHiddenColors",	questions: ["Какой цвет был у главного светодиода?"] },
	{ original: "The Hidden Value",	name: "The Hidden Value",	id: "theHiddenValue",	questions: ["What numbers and colors were displayed?"] },
	{ original: "The High Score",	name: "The High Score",	id: "ksmHighScore",	questions: ["What was the player’s position and score?"] },
	{ original: "Hill Cycle",	name: "Hill Cycle",	id: "hillCycle",	questions: ["Какое было сообщение и ответ?", "What was written on each dial?"] },
	{ original: "Hogwarts",	name: "Hogwarts",	id: "HogwartsModule",	questions: ["Для каких из домов был решён каждый модуль?"] },
	{ original: "Hold Ups",	name: "Hold Ups",	id: "KritHoldUps",	questions: ["Какое было имя у каждой показанной тени?"] },
	{ original: "Holographic Memory",	name: "Holographic Memory",	id: "holographicMemory",	questions: ["Which side did each symbol appear?"] },
	{ original: "Homophones",	name: "Homophones",	id: "homophones",	questions: ["Какие фразы были показаны?"] },
	{ original: "Horrible Memory",	name: "Horrible Memory",	id: "horribleMemory",	questions: ["Какие позиции, надписи и цвета были у нажатых кнопок на каждом этапе?", "What digit was displayed in each stage?"] },
	{ original: "Human Resources",	name: "Human Resources",	id: "HumanResourcesModule",	questions: ["Кто был уволен и нанят?", "Какие описания были показаны в красном и зелёном?"] },
	{ original: "Hunting",	name: "Hunting",	id: "hunting",	questions: ["На каких этапах вначале были символы столбца или строки?"] },
	{ original: "HyperForget",	name: "HyperForget",	id: "HyperForget",	questions: ["What were the rotations?"] },
	{ original: "The Hyperlink",	name: "The Hyperlink",	id: "hyperlink",	questions: ["What was the hyperlink?", "Which module was referenced?"] },
	{ original: "Identification Crisis",	name: "Identification Crisis",	id: "identificationCrisis",	questions: ["Какие фигуры и опозновательные модули использованы на модуле?"] },
	{ original: "Identity Parade",	name: "Identity Parade",	id: "identityParade",	questions: ["Какие цвета волос, строения тела и одеяния присутствовали?"] },
	{ original: "Indigo Cipher",	name: "Indigo Cipher",	id: "indigoCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Infinite Loop",	name: "Infinite Loop",	id: "InfiniteLoop",	questions: ["Какое слово было выбрано?"] },
	{ original: "Ingredients",	name: "Ingredients",	id: "ingredients",	questions: ["Какие ингредиенты были указаны и какие были использованы?"] },
	{ original: "Inner Connections",	name: "Inner Connections",	id: "InnerConnectionsModule",	questions: ["Какого цвета был светодиод?", "Какая цифра была передана при помощи Морзе?"] },
	{ original: "Interpunct",	name: "Interpunct",	id: "interpunct",	questions: ["Какой символ был показан на каждом этапе?"] },
	{ original: "IPA",	name: "IPA",	id: "ipa",	questions: ["Какой звук был проигран?"] },
	{ original: "The iPhone",	name: "The iPhone",	id: "iPhone",	questions: ["Какой был пинкод?"] },
	{ original: "Jenga",	name: "Jenga",	id: "jenga",	questions: ["Какие символы были на первом правильно вытянутом блоке?"] },
	{ original: "The Jewel Vault",	name: "The Jewel Vault",	id: "jewelVault",	questions: ["Какие числа были у колёс A–D?"] },
	{ original: "Jumble Cycle",	name: "Jumble Cycle",	id: "jumbleCycle",	questions: ["Какое было сообщение и ответ?", "What was written on each dial?"] },
	{ original: "The Kanye Encounter",	name: "The Kanye Encounter",	id: "TheKanyeEncounter",	questions: ["What food items were shown?"] },
	{ original: "KayMazey Talk",	name: "KayMazey Talk",	id: "KMazeyTalk",	questions: ["What were the starting and goal words?"] },
	{ original: "Keypad Combinations",	name: "Keypad Combinations",	id: "keypadCombinations",	questions: ["Какие были числа которые не являлись частью решения?"] },
	{ original: "Keypad Magnified",	name: "Keypad Magnified",	id: "keypadMagnified",	questions: ["Какая позиция была у светодиода?"] },
	{ original: "Keypad Maze",	name: "Keypad Maze",	id: "KeypadMaze",	questions: ["Где были жёлтые клетки?"] },
	{ original: "Keypad Sequence",	name: "Keypad Sequence",	id: "keypadSeq",	questions: ["Какие символы были на клавишах?"] },
	{ original: "Keywords",	name: "Keywords",	id: "xtrkeywords",	questions: ["Какие буквы были на экране?"] },
	{ original: "The Klaxon",	name: "The Klaxon",	id: "klaxon",	questions: ["What was the first module to set off the klaxon?"] },
	{ original: "Know Your Way",	name: "Know Your Way",	id: "KnowYourWay",	questions: ["Куда указывала стрелка?", "Какой светодиод горел зелёным?"] },
	{ original: "Kooky Keypad",	name: "Kooky Keypad",	id: "kookyKeypadModule",	questions: ["Каких цветов были светодиоды?"] },
	{ original: "Kugelblitz",	name: "Kugelblitz",	id: "kugelblitz",	questions: ["Which particles were present during each stage?", "What were the particles’ values during each stage?"] },
	{ original: "Kuro",	name: "Kuro",	id: "Kuro",	questions: ["Какое было настроение у Kuro?"] },
	{ original: "The Labyrinth",	name: "The Labyrinth",	id: "labyrinth",	questions: ["Where were the portals, and which layers were they on?"] },
	{ original: "Ladder Lottery",	name: "Ladder Lottery",	id: "ladderLottery",	questions: ["Какая лампочка горела?"] },
	{ original: "Ladders",	name: "Ladders",	id: "ladders",	questions: ["Какие были цвета на второй лестнице?", "Какой цвет отсутствовал на третьей лестнице?"] },
	{ original: "Langton’s Anteater",	name: "Langton’s Anteater",	id: "GSLangtonsAnteater",	questions: ["Какое было исходное состояние поля?"] },
	{ original: "LED Encryption",	name: "LED Encryption",	id: "LEDEnc",	questions: ["Which letters were present at each stage"] },
	{ original: "LED Math",	name: "LED Math",	id: "lgndLEDMath",	questions: ["Какие цвета были у светодиодов?"] },
	{ original: "LEDs",	name: "LEDs",	id: "leds",	questions: ["Какой был исходный цвет у изменённого светодиода?"] },
	{ original: "LEGOs",	name: "LEGOs",	id: "LEGOModule",	questions: ["Каких размеров и какого цвета была каждая деталь?"] },
	{ original: "Lempel-Ziv Cipher",	name: "Lempel-Ziv Cipher",	id: "LempelZivCipherModule",	questions: ["What was on each screen?"] },
	{ original: "Letter Math",	name: "Letter Math",	id: "letterMath",	questions: ["Какие буквы были на экране?"] },
	{ original: "Light Bulbs",	name: "Light Bulbs",	id: "LightBulbs",	questions: ["Каких цветов были лампочки?"] },
	{ original: "Lime Arrows",	name: "Lime Arrows",	id: "limeArrowsModule",	questions: ["What was the starting coordinate?"] },
	{ original: "Linq",	name: "Linq",	id: "Linq",	questions: ["Какие были функции?"] },
	{ original: "Lion’s Share",	name: "Lion’s Share",	id: "LionsShareModule",	questions: ["Какой год был показан?", "Какие львы были изначально, но потом убраны?"] },
	{ original: "Literal Maze",	name: "Literal Maze",	id: "literalMaze",	questions: ["Which letter was in each position?"] },
	{ original: "Logical Buttons",	name: "Logical Buttons",	id: "logicalButtonsModule",	questions: ["Какие цвета и надписи были у кнопок на каждом этапе?", "Какая была финальная операция на каждом этапе?"] },
	{ original: "Lombax Cubes",	name: "Lombax Cubes",	id: "lgndLombaxCubes",	questions: ["Какие буквы были на кнопке?"] },
	{ original: "The London Underground",	name: "The London Underground",	id: "londonUnderground",	questions: ["What were the departure and destination stations?"] },
	{ original: "Long Words",	name: "Long Words",	id: "LongWords",	questions: ["Какое слово было на верхнем экране?"] },
	{ original: "Mad Memory",	name: "Mad Memory",	id: "MadMemory",	questions: ["Что было на экране на каждом этапе?"] },
	{ original: "Magenta Cipher",	name: "Magenta Cipher",	id: "magentaCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Mahjong",	name: "Mahjong",	id: "MahjongModule",	questions: ["Какие были две первые сопоставленные пары?"] },
	{ original: "Main Page",	name: "Main Page",	id: "mainpage",	questions: ["Какие цвета и фразы присутствовали И отсутствовали на модуле?", "Откуда были взяты Homestar, фон и эффекты кнопок?"] },
	{ original: "M&Ms",	name: "M&Ms",	id: "MandMs",	questions: ["What were the labels on the buttons and their colors?"] },
	{ original: "M&Ns",	name: "M&Ns",	id: "MandNs",	questions: ["What were the colors of the labels on the buttons?", "What was the label of the correct button?"] },
	{ original: "Maritime Flags",	name: "Maritime Flags",	id: "MaritimeFlagsModule",	questions: ["Какой пеленг был передан?", "Какой позывной был передан?"] },
	{ original: "Maritime Semaphore",	name: "Maritime Semaphore",	id: "MaritimeSemaphoreModule",	questions: ["Где была фиктивная конфигурация?", "Какие буквы были переданы?"] },
	{ original: "The Maroon Button",	name: "The Maroon Button",	id: "MaroonButtonModule",	questions: ["What was A?"] },
	{ original: "Maroon Cipher",	name: "Maroon Cipher",	id: "maroonCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Mashematics",	name: "Mashematics",	id: "mashematics",	questions: ["Какие числа были в уравнении?"] },
	{ original: "Master Tapes",	name: "Master Tapes",	id: "masterTape",	questions: ["Какая песня была проиграна?"] },
	{ original: "Match Refereeing",	name: "Match Refereeing",	id: "matchRefereeing",	questions: ["Какие планеты присутствовали на каждом этапе?"] },
	{ original: "Math ’em",	name: "Math ’em",	id: "mathem",	questions: ["Где была какая плитка до перемешивания?"] },
	{ original: "The Matrix",	name: "The Matrix",	id: "matrix",	questions: ["Which word was part of the latest access code used?"] },
	{ original: "Maze³",	name: "Maze³",	id: "maze3",	questions: ["Какой цвет был у начальной стороны?"] },
	{ original: "Maze Identification",	name: "Maze Identification",	id: "GSMazeIdentification",	questions: ["Какое было зерно?", "Какая функция была у каждой кнопки?"] },
	{ original: "Maze Scrambler",	name: "Maze Scrambler",	id: "MazeScrambler",	questions: ["Где была начальная позиция?", "Где была цель?", "Где были обозначения лабиринта?"] },
	{ original: "Mazeseeker",	name: "Mazeseeker",	id: "GSMazeseeker",	questions: ["Сколько стен окружало каждую клетку?", "Где были начальная и целевая позиции?"] },
	{ original: "Maze Swap",	name: "Maze Swap",	id: "mazeSwap",	questions: ["Где были начальная и целевая позиции?"] },
	{ original: "Memorable Buttons",	name: "Memorable Buttons",	id: "memorableButtons",	questions: ["Какие символы были на правильных кнопках?"] },
	{ original: "Memory Wires",	name: "Memory Wires",	id: "memoryWires",	questions: ["Какие цвета были у проводов?", "Какие цифры были показаны?"] },
	{ original: "Metamorse",	name: "Metamorse",	id: "metamorse",	questions: ["Какая буквы была извлечена?"] },
	{ original: "Metapuzzle",	name: "Metapuzzle",	id: "metapuzzle",	questions: ["Какой был финальный ответ?"] },
	{ original: "Minsk Metro",	name: "Minsk Metro",	id: "minskMetro",	questions: ["What was the starting station?"] },
	{ original: "Mirror",	name: "Mirror",	id: "mirror",	questions: ["Какое второе слово было написано оригинальным призраком?"] },
	{ original: "The Missing Letter",	name: "The Missing Letter",	id: "theMissingLetter",	questions: ["What letter was missing?"] },
	{ original: "Mister Softee",	name: "Mister Softee",	id: "misterSoftee",	questions: ["Где был the SpongeBob Bar?", "Какие сладости присутствовали?"] },
	{ original: "Mixometer",	name: "Mixometer",	id: "mixometer",	questions: ["Где была кнопка отправки?"] },
	{ original: "Module Listening",	name: "Module Listening",	id: "moduleListening",	questions: ["Какие звуки присутствовали?", "Какой звук издавала каждая кнопка?"] },
	{ original: "Module Maneuvers",	name: "Module Maneuvers",	id: "moduleManeuvers",	questions: ["What was the goal location?"] },
	{ original: "Module Movements",	name: "Module Movements",	id: "moduleMovements",	questions: ["Какой модуль был показан на каждом этапе?"] },
	{ original: "Money Game",	name: "Money Game",	id: "MoneyGame",	questions: ["Какие были фразы?"] },
	{ original: "The Moon",	name: "The Moon",	id: "moon",	questions: ["Which sets were initially lit/unlit?"] },
	{ original: "More Code",	name: "More Code",	id: "MoreCode",	questions: ["Какое слово передавалось модулем?"] },
	{ original: "Morse-A-Maze",	name: "Morse-A-Maze",	id: "MorseAMaze",	questions: ["Где были начальная и целевые позиции?", "Какое было кодовое слово?"] },
	{ original: "Morse Buttons",	name: "Morse Buttons",	id: "morseButtons",	questions: ["Какие символы и цвета мигали на каждой кнопке?"] },
	{ original: "Morsematics",	name: "Morsematics",	id: "MorseV2",	questions: ["Какие буквы были получены?"] },
	{ original: "Morse War",	name: "Morse War",	id: "MorseWar",	questions: ["Какое было состояние светодиодов?", "Какой код был передан?"] },
	{ original: ".--/---/..-.",	name: ".--/---/..-.",	id: "morseWoF",	questions: ["What were the display words?"] },
	{ original: "M-Seq",	name: "M-Seq",	id: "mSeq",	questions: ["Какие цифры были получены?", "Какое число было финальным в итерационном процессе?"] },
	{ original: "Mssngv Wls",	name: "Mssngv Wls",	id: "MssngvWls",	questions: ["Какая гласная отсутствовала?"] },
	{ original: "The Multiverse Hotline",	name: "The Multiverse Hotline",	id: "MultiverseHotline",	questions: ["What was the universe origin and its initial number?"] },
	{ original: "Mystery Module",	name: "Mystery Module",	id: "mysterymodule",	questions: ["Какой модуль был спрятан?", "Какой модуль требовалось решить первым?"] },
	{ original: "Mystic Square",	name: "Mystic Square",	id: "MysticSquareModule",	questions: ["Где находился череп?"] },
	{ original: "Name Codes",	name: "Name Codes",	id: "nameCodes",	questions: ["Какие индексы были слева и справа?"] },
	{ original: "Naming Conventions",	name: "Naming Conventions",	id: "NamingConventions",	questions: ["Какая была надпись на первой кнопке?"] },
	{ original: "N&Ns",	name: "N&Ns",	id: "NandNs",	questions: ["What were the labels in stage 2 and 3?", "What was the missing color in stage 3?"] },
	{ original: "Navigation Determination",	name: "Navigation Determination",	id: "NavigationDeterminationModule",	questions: ["Какой цвет и надпись были у лабиринта?"] },
	{ original: "Navinums",	name: "Navinums",	id: "navinums",	questions: ["Какие направления были нажаты?", "Какая была исходная цифра посередине?"] },
	{ original: "The Navy Button",	name: "The Navy Button",	id: "NavyButtonModule",	questions: ["Which Greek letters appeared?", "What were the coordinates and value of the given?"] },
	{ original: "The Necronomicon",	name: "The Necronomicon",	id: "necronomicon",	questions: ["What was the chapter number of each page?"] },
	{ original: "Negativity",	name: "Negativity",	id: "Negativity",	questions: ["Какая величина была отправления (в десятеричной и сбалансированной троичной системе)?"] },
	{ original: "Neptune",	name: "Neptune",	id: "neptune",	questions: ["Which star was displayed?"] },
	{ original: "Next In Line",	name: "Next In Line",	id: "NextInLine",	questions: ["Какого цвета был первый провод?"] },
	{ original: "Nim",	name: "Nim",	id: "nim",	questions: ["How many matches were in each row?"] },
	{ original: "Noise Identification",	name: "Noise Identification",	id: "noiseIdentification",	questions: ["What was the first displayed noise type?"] },
	{ original: "❖",	name: "❖",	id: "nonverbalSimon",	questions: ["Какие были вспышки?"] },
	{ original: "Not Colored Squares",	name: "Not Colored Squares",	id: "NotColoredSquaresModule",	questions: ["Какую позицию вы нажали первой?"] },
	{ original: "Not Colored Switches",	name: "Not Colored Switches",	id: "NotColoredSwitchesModule",	questions: ["Какое слово было зашифровано?"] },
	{ original: "Not Colour Flash",	name: "Not Colour Flash",	id: "notColourFlash",	questions: ["What were the displayed word and colour sequences?"] },
	{ original: "Not Connection Check",	name: "Not Connection Check",	id: "notConnectionCheck",	questions: ["Какие символы были переданы вспышками?", "Какие значения были у каждой кнопки?"] },
	{ original: "Not Coordinates",	name: "Not Coordinates",	id: "notCoordinates",	questions: ["Какие были вершины у квадрата?"] },
	{ original: "Not Double-Oh",	name: "Not Double-Oh",	id: "NotDoubleOhModule",	questions: ["Какие позиции были показаны на втором этапе?"] },
	{ original: "Not Maze",	name: "Not Maze",	id: "NotMaze",	questions: ["Какая была начальная дистанция?"] },
	{ original: "Not Morse Code",	name: "Not Morse Code",	id: "NotMorseCode",	questions: ["Какую последовательность слов вы отправили?"] },
	{ original: "Not Morsematics",	name: "Not Morsematics",	id: "notMorsematics",	questions: ["Какое слово было передано?"] },
	{ original: "Not Murder",	name: "Not Murder",	id: "notMurder",	questions: ["Какое было исходное положение подозреваемых?", "Какое исходное оружие было у какого подозреваемого?"] },
	{ original: "Not Number Pad",	name: "Not Number Pad",	id: "notNumberPad",	questions: ["Какое число мигало на каждом этапе?"] },
	{ original: "Not Password",	name: "Not Password",	id: "NotPassword",	questions: ["Какая буква отсутствовала?"] },
	{ original: "Not Perspective Pegs",	name: "Not Perspective Pegs",	id: "NotPerspectivePegsModule",	questions: ["Какая была позиция, ракурс и цвет каждой вспышки?"] },
	{ original: "Not Piano Keys",	name: "Not Piano Keys",	id: "notPianoKeys",	questions: ["Какие символы были показаны?"] },
	{ original: "Not Red Arrows",	name: "Not Red Arrows",	id: "notRedArrowsModule",	questions: ["Какое было начальное число?"] },
	{ original: "Not Simaze",	name: "Not Simaze",	id: "NotSimaze",	questions: ["Какой был лабиринт?", "Какая была начальная и конечная позиции?"] },
	{ original: "Not Text Field",	name: "Not Text Field",	id: "notTextField",	questions: ["Какая буква появилась 9 раз в начале?", "Какие буквы были нажаты на первом этапе?"] },
	{ original: "Not The Bulb",	name: "Not The Bulb",	id: "notTheBulb",	questions: ["Какое слово было передано модулем?"] },
	{ original: "Not The Plunger Button",	name: "Not The Plunger Button",	id: "notPlungerButtonModule",	questions: ["Какими цветами мигал фон?"] },
	{ original: "Not The Screw",	name: "Not The Screw",	id: "notTheScrew",	questions: ["Какая была начальная позиция?"] },
	{ original: "Not Who’s on First",	name: "Not Who’s on First",	id: "NotWhosOnFirst",	questions: ["Какие кнопки в какой позиции вы нажали; ссылаясь на какие кнопки?", "Какая величина была вычислена во втором этапе?"] },
	{ original: "Not Word Search",	name: "Not Word Search",	id: "notWordSearch",	questions: ["Какие согласные отсутствовали?", "Какая первая верная буква была нажата?"] },
	{ original: "Not X01",	name: "Not X01",	id: "notX01",	questions: ["Какие величины были у секторов?"] },
	{ original: "Not X-Ray",	name: "Not X-Ray",	id: "NotXRayModule",	questions: ["В какой таблице вы находились?", "Какие кнопки отвечали за какое направление?", "Какой был цвет сканера?"] },
	{ original: "Numbered Buttons",	name: "Numbered Buttons",	id: "numberedButtonsModule",	questions: ["Какие правильные числа были нажаты?"] },
	{ original: "The Number Game",	name: "The Number Game",	id: "TheNumberGame",	questions: ["What was the maximum number?"] },
	{ original: "Numbers",	name: "Numbers",	id: "Numbers",	questions: ["Какое двухзначное число было дано?"] },
	{ original: "Numpath",	name: "Numpath",	id: "numpath",	questions: ["Какое было число и его цвет?"] },
	{ original: "The Octadecayotton",	name: "The Octadecayotton",	id: "TheOctadecayotton",	questions: ["What was the starting sphere?", "What were the subtransformations in each transformation?"] },
	{ original: "Odd One Out",	name: "Odd One Out",	id: "OddOneOutModule",	questions: ["Какие правильные кнопки были нажаты?"] },
	{ original: "Off Keys",	name: "Off Keys",	id: "offKeys",	questions: ["What were the displayed runes?", "Which keys played at an incorrect pitch?"] },
	{ original: "Off-White Cipher",	name: "Off-White Cipher",	id: "offWhiteCipher",	questions: ["What was on each display?"] },
	{ original: "Old AI",	name: "Old AI",	id: "SCP079",	questions: ["What was the group/sub-group of the displayed numbers?"] },
	{ original: "Old Fogey",	name: "Old Fogey",	id: "oldFogey",	questions: ["Какой был начальный цвет у индикатора?"] },
	{ original: "One Links To All",	name: "One Links To All",	id: "oneLinksToAllModule",	questions: ["Какие статьи были указаны в начале?"] },
	{ original: "Orange Cipher",	name: "Orange Cipher",	id: "orangeCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Ordered Keys",	name: "Ordered Keys",	id: "orderedKeys",	questions: ["Какие были надписи, их цвета и цвета клавиш на каждом этапе?"] },
	{ original: "Order Picking",	name: "Order Picking",	id: "OrderPickingModule",	questions: ["Какой был ID заказа, ID продукта и паллет в каждом заказе?"] },
	{ original: "Orientation Hypercube",	name: "Orientation Hypercube",	id: "OrientationHypercube",	questions: ["Какая была начальная позиция наблюдателя?", "Какой был начальный цвет каждой стороны?"] },
	{ original: "Painting Cube",	name: "Painting Cube",	id: "paintingCube",	questions: ["What color was missing?"] },
	{ original: "Palindromes",	name: "Palindromes",	id: "palindromes",	questions: ["Что было в X, Y, Z и на экране?"] },
	{ original: "Papa’s Pizzeria",	name: "Papa’s Pizzeria",	id: "papasPizzeria",	questions: ["What was the order code?"] },
	{ original: "Parity",	name: "Parity",	id: "parity",	questions: ["Что было показано на экране?"] },
	{ original: "Partial Derivatives",	name: "Partial Derivatives",	id: "partialDerivatives",	questions: ["Из каких членов состояла функция?", "Какой был цвет светодиода на каждом этапе?"] },
	{ original: "Passport Control",	name: "Passport Control",	id: "passportControl",	questions: ["Какая была дата истечения паспорта у каждого пассажира?"] },
	{ original: "Password Destroyer",	name: "Password Destroyer",	id: "pwDestroyer",	questions: ["Какая была начальная величина, фактор инкремента, TFA₁, TFA₂ и 2FAST™, и также процент решённых модулей который использовался в финальных вычислениях?"] },
	{ original: "Pattern Recognition",	name: "Pattern Recognition",	id: "patternRecognition",	questions: ["What was the repeating pattern?"] },
	{ original: "The Pentabutton",	name: "The Pentabutton",	id: "GSPentabutton",	questions: ["What was the base colour?"] },
	{ original: "Periodic Words",	name: "Periodic Words",	id: "periodicWordsRB",	questions: ["Какое слово было показано на каждом этапе?"] },
	{ original: "Phosphorescence",	name: "Phosphorescence",	id: "Phosphorescence",	questions: ["Какие кнопки были нажаты и какое было смещение?"] },
	{ original: "Pickup Identification",	name: "Pickup Identification",	id: "PickupIdentification",	questions: ["Какие предметы были показаны?"] },
	{ original: "Pictionary",	name: "Pictionary",	id: "pictionaryModule",	questions: ["Какой был код?"] },
	{ original: "Pie",	name: "Pie",	id: "pieModule",	questions: ["Какие цифры были показаны?"] },
	{ original: "Pie Flash",	name: "Pie Flash",	id: "pieFlash",	questions: ["Какие числа были показаны?"] },
	{ original: "Pigpen Cycle",	name: "Pigpen Cycle",	id: "pigpenCycle",	questions: ["Какое было сообщение и ответ?", "What was written on each dial?"] },
	{ original: "The Pink Button",	name: "The Pink Button",	id: "PinkButtonModule",	questions: ["What were the displayed words and their colors?"] },
	{ original: "Pinpoint",	name: "Pinpoint",	id: "pinpoint",	questions: ["What were the given point coordinates and distances?"] },
	{ original: "Pixel Cipher",	name: "Pixel Cipher",	id: "pixelcipher",	questions: ["Какое было ключевое слово?"] },
	{ original: "Placeholder Talk",	name: "Placeholder Talk",	id: "placeholderTalk",	questions: ["Какая была первая фраза?", "Какая величина была у второй фразы??"] },
	{ original: "Placement Roulette",	name: "Placement Roulette",	id: "PlacementRouletteModule",	questions: ["Какие персонажи, трассы и транспортные средства присутствовали?"] },
	{ original: "Planets",	name: "Planets",	id: "planets",	questions: ["Какая планета была показана?", "What was the color for each strip?"] },
	{ original: "Playfair Cycle",	name: "Playfair Cycle",	id: "playfairCycle",	questions: ["Какое было сообщение и ответ?", "What was written on each dial?"] },
	{ original: "Pointless Machines",	name: "Pointless Machines",	id: "PointlessMachines",	questions: ["Какие цвета мигали?"] },
	{ original: "Pokémon Sprite Cipher",	name: "Pokémon Sprite Cipher",	id: "PokemonSpriteCipherModule",	questions: ["What was on each screen?"] },
	{ original: "Polygons",	name: "Polygons",	id: "polygons",	questions: ["Какие фигуры присутствовали?"] },
	{ original: "Polyhedral Maze",	name: "Polyhedral Maze",	id: "PolyhedralMazeModule",	questions: ["Где была начальная позиция?"] },
	{ original: "Prime Encryption",	name: "Prime Encryption",	id: "primeEncryption",	questions: ["Какое число было показано?"] },
	{ original: "Prison Break",	name: "Prison Break",	id: "prisonBreak",	questions: ["Where did the prisoner and defuser start?"] },
	{ original: "Procedural Maze",	name: "Procedural Maze",	id: "ProceduralMaze",	questions: ["Какое было изначальное зерно?"] },
	{ original: "...?",	name: "...?",	id: "punctuationMarks",	questions: ["Какое число было показано?"] },
	{ original: "The Purple Button",	name: "The Purple Button",	id: "PurpleButtonModule",	questions: ["What were the numbers in the cyclic sequence?"] },
	{ original: "Puzzle Identification",	name: "Puzzle Identification",	id: "GSPuzzleIdentification",	questions: ["Из какой игры был каждый пазл?", "Какой был номер и название каждого пазла?"] },
	{ original: "Puzzling Hexabuttons",	name: "Puzzling Hexabuttons",	id: "puzzlingHexabuttons",	questions: ["What letters were shown during submission?"] },
	{ original: "Q & A",	name: "Q & A",	id: "q&a",	questions: ["What questions were asked?"] },
	{ original: "Quadrants",	name: "Quadrants",	id: "Quadrants",	questions: ["What was on each button in each stage?"] },
	{ original: "Quantum Passwords",	name: "Quantum Passwords",	id: "quantumPasswords",	questions: ["Какие слова были использованы?"] },
	{ original: "Quantum Ternary Converter",	name: "Quantum Ternary Converter",	id: "quTern",	questions: ["Какие были числа?"] },
	{ original: "Quaver",	name: "Quaver",	id: "Quaver",	questions: ["Какой был ответ к каждой последовательности?"] },
	{ original: "Question Mark",	name: "Question Mark",	id: "Questionmark",	questions: ["Какие символы мигали?"] },
	{ original: "Quick Arithmetic",	name: "Quick Arithmetic",	id: "QuickArithmetic",	questions: ["Какие были цифры и цвета в обеих последовательностях?"] },
	{ original: "Quintuples",	name: "Quintuples",	id: "quintuples",	questions: ["Какие были числа и цвета в каждом слоте?", "Сколько было чисел каждого цвета?"] },
	{ original: "Quiplash",	name: "Quiplash",	id: "QLModule",	questions: ["Какое число было показано?"] },
	{ original: "Quiz Buzz",	name: "Quiz Buzz",	id: "quizBuzz",	questions: ["Какое число было изначально на экране?"] },
	{ original: "Qwirkle",	name: "Qwirkle",	id: "qwirkle",	questions: ["Какие плитки вы положили?"] },
	{ original: "Raiding Temples",	name: "Raiding Temples",	id: "raidingTemples",	questions: ["Сколько драгоценностей было в начальном общем схроне?"] },
	{ original: "Rainbow Arrows",	name: "Rainbow Arrows",	id: "ksmRainbowArrows",	questions: ["Какое число было на экране?"] },
	{ original: "Recursive Password",	name: "Recursive Password",	id: "RecursivePassword",	questions: ["Какие были обрывки слов?", "Какой был пароль?"] },
	{ original: "Red Button’t",	name: "Red Button’t",	id: "redbuttont",	questions: ["Какое слово было показано?"] },
	{ original: "Red Cipher",	name: "Red Cipher",	id: "redCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Red Herring",	name: "Red Herring",	id: "RedHerring",	questions: ["Какой цвет мигал первым?"] },
	{ original: "Reformed Role Reversal",	name: "Reformed Role Reversal",	id: "ReformedRoleReversal",	questions: ["Что было указано в финальном условии?", "What were the wire colors?"] },
	{ original: "ReGret-B Filtering",	name: "ReGret-B Filtering",	id: "regretbFiltering",	questions: ["Какие вычисления были использованы?"] },
	{ original: "Regular Crazy Talk",	name: "Regular Crazy Talk",	id: "RegularCrazyTalkModule",	questions: ["Какое число на экране соответствовало верной фразе?", "Какое обрамление было у верной фразы?"] },
	{ original: "Reordered Keys",	name: "Reordered Keys",	id: "reorderedKeys",	questions: ["What were the labels, their colors, and the colors of the keys initially in each stage?"] },
	{ original: "Retirement",	name: "Retirement",	id: "retirement",	questions: ["Какие дома предлагались, но не были выбраны Бобом?"] },
	{ original: "Reverse Morse",	name: "Reverse Morse",	id: "reverseMorse",	questions: ["Какие символы были в каждом сообщении?"] },
	{ original: "Reverse Polish Notation",	name: "Reverse Polish Notation",	id: "revPolNot",	questions: ["Какие символы использовались на каждом этапе?"] },
	{ original: "RGB Encryption",	name: "RGB Encryption",	id: "RGBEncryption",	questions: ["What were the Morse code and color sequences?"] },
	{ original: "RGB Maze",	name: "RGB Maze",	id: "rgbMaze",	questions: ["Где был выход и ключи лабиринта?", "Какой номер был у каждого лабиринта?"] },
	{ original: "RGB Sequences",	name: "RGB Sequences",	id: "RGBSequences",	questions: ["Какие цвета были на каждой кнопке?"] },
	{ original: "RNG Crystal",	name: "RNG Crystal",	id: "rngCrystal",	questions: ["Where were the taps?"] },
	{ original: "Robo-Scanner",	name: "Robo-Scanner",	id: "roboScannerModule",	questions: ["Где была пустая ячейка?"] },
	{ original: "Robot Programming",	name: "Robot Programming",	id: "robotProgramming",	questions: ["Каких форм и цветов были роботы?"] },
	{ original: "Roger",	name: "Roger",	id: "roger",	questions: ["Какое 4-хзначное число было дано?"] },
	{ original: "Role Reversal",	name: "Role Reversal",	id: "roleReversal",	questions: ["Какой номер условия обезвредил модуль?", "Какого цвета были внутренние провода?"] },
	{ original: "RPS Judging",	name: "RPS Judging",	id: "RPSJudging",	questions: ["Which rounds did each team win/lose/tie?"] },
	{ original: "The Rule",	name: "The Rule",	id: "theRule",	questions: ["What was the rule number?"] },
	{ original: "Rule of Three",	name: "Rule of Three",	id: "RuleOfThreeModule",	questions: ["Какие позиции были у каждой сферы на каждой оси на каждом этапе?", "Какие координаты были у вершин?"] },
	{ original: "Safety Square",	name: "Safety Square",	id: "safetySquare",	questions: ["Какие цифры были показаны?", "Какое было специальное правило?"] },
	{ original: "The Samsung",	name: "The Samsung",	id: "theSamsung",	questions: ["Where was each app?"] },
	{ original: "Saturn",	name: "Saturn",	id: "saturn",	questions: ["Где была цель?"] },
	{ original: "Sbemail Songs",	name: "Sbemail Songs",	id: "sbemailsongs",	questions: ["Какие песни были показаны на каждом этапе?"] },
	{ original: "Scavenger Hunt",	name: "Scavenger Hunt",	id: "scavengerHunt",	questions: ["Какая плитка была правильно выбрана на первом этапе?", "Где была красная, зелёная и синяя плитка на первом этапе?"] },
	{ original: "Schlag den Bomb",	name: "Schlag den Bomb",	id: "qSchlagDenBomb",	questions: ["Какие были имена участников и их счёт?"] },
	{ original: "Scramboozled Eggain",	name: "Scramboozled Eggain",	id: "ScramboozledEggainModule",	questions: ["Какие слова были зашифрованы?"] },
	{ original: "Scrutiny Squares",	name: "Scrutiny Squares",	id: "scrutinySquares",	questions: ["Какое свойство первого квадрата было изменено?"] },
	{ original: "Semamorse",	name: "Semamorse",	id: "semamorse",	questions: ["Какие буквы Морзе, буквы семафора и какой цвет были использованы в начальном значении?"] },
	{ original: "The Sequencyclopedia",	name: "The Sequencyclopedia",	id: "TheSequencyclopedia",	questions: ["What sequence was used?"] },
	{ original: "S.E.T. Theory",	name: "S.E.T. Theory",	id: "SetTheory",	questions: ["Какие уравнения были показаны на каждом этапе?"] },
	{ original: "Shapes And Bombs",	name: "Shapes And Bombs",	id: "ShapesBombs",	questions: ["Какая была начальная буква?"] },
	{ original: "Shifted Maze",	name: "Shifted Maze",	id: "shiftedMaze",	questions: ["Каких цветов были маркеры?"] },
	{ original: "Shifting Maze",	name: "Shifting Maze",	id: "MazeShifting",	questions: ["Какое было зерно?"] },
	{ original: "Shogi Identification",	name: "Shogi Identification",	id: "shogiIdentification",	questions: ["Какая фигура была показана?"] },
	{ original: "Sign Language",	name: "Sign Language",	id: "signLanguage",	questions: ["Какое слово было расшифровано?"] },
	{ original: "Silo Authorization",	name: "Silo Authorization",	id: "siloAuthorization",	questions: ["Какой был тип сообщения, зашифрованное сообщение и полученные код авторизации?"] },
	{ original: "Simon Said",	name: "Simon Said",	id: "simonSaidModule",	questions: ["Какая была финальная последовательность нажатий?"] },
	{ original: "Simon Samples",	name: "Simon Samples",	id: "simonSamples",	questions: ["Какие сэмплы были на каждом этапе?"] },
	{ original: "Simon Scrambles",	name: "Simon Scrambles",	id: "simonScrambles",	questions: ["Какая последовательность цветов мигала?"] },
	{ original: "Simon Selects",	name: "Simon Selects",	id: "simonSelectsModule",	questions: ["Какие цвета мигали на каждом этапе?"] },
	{ original: "Simon Sends",	name: "Simon Sends",	id: "SimonSendsModule",	questions: ["Какая красная, зелёная и синяя буква была получена?"] },
	{ original: "Simon Serves",	name: "Simon Serves",	id: "simonServes",	questions: ["Кто горел на каждой подаче?", "Что не подавалось гостям на каждой подаче?"] },
	{ original: "Simon Shapes",	name: "Simon Shapes",	id: "SimonShapesModule",	questions: ["Какая фигура была введена в конце?"] },
	{ original: "Simon Shouts",	name: "Simon Shouts",	id: "SimonShoutsModule",	questions: ["Какие буквы горели на каждой кнопке?"] },
	{ original: "Simon Shrieks",	name: "Simon Shrieks",	id: "SimonShrieksModule",	questions: ["Сколько пробелов по часовой стрелке было между каждой вспышкой в финальной последовательности?"] },
	{ original: "Simon Shuffles",	name: "Simon Shuffles",	id: "GSSimonShuffles",	questions: ["Which buttons flashed at each stage?"] },
	{ original: "Simon Signals",	name: "Simon Signals",	id: "SimonSignalsModule",	questions: ["Какие были цвета, формы и число направлений у каждой стрелки?"] },
	{ original: "Simon Simons",	name: "Simon Simons",	id: "simonSimons",	questions: ["Which buttons flashed?"] },
	{ original: "Simon Sings",	name: "Simon Sings",	id: "SimonSingsModule",	questions: ["Какие цвета клавиш горели на каждом этапе?"] },
	{ original: "Simon Smiles",	name: "Simon Smiles",	id: "SimonSmiles",	questions: ["Какой звук был проигран каждой нажатой кнопкой?"] },
	{ original: "Simon Smothers",	name: "Simon Smothers",	id: "simonSmothers",	questions: ["Какие цвета и направления горели на каждом этапе?"] },
	{ original: "Simon Sounds",	name: "Simon Sounds",	id: "simonSounds",	questions: ["Какая кнопка семпла звучала на каждом этапе?"] },
	{ original: "Simon’s Star",	name: "Simon’s Star",	id: "simonsStar",	questions: ["Какие цвета горели?"] },
	{ original: "Simon Stacks",	name: "Simon Stacks",	id: "simonstacks",	questions: ["Какие цвета горели на каждом этапе?"] },
	{ original: "Simon Stops",	name: "Simon Stops",	id: "simonStops",	questions: ["Какие цвета горели в последовательности?"] },
	{ original: "Simon Stores",	name: "Simon Stores",	id: "simonStores",	questions: ["Какие цвета горели в финальной последовательности?"] },
	{ original: "Simon Subdivides",	name: "Simon Subdivides",	id: "simonSubdivides",	questions: ["Каких цветов были клетки которые разделились?"] },
	{ original: "Simon Supports",	name: "Simon Supports",	id: "simonSupports",	questions: ["Какие были 3 темы рассуждений?"] },
	{ original: "Simon Swizzles",	name: "Simon Swizzles",	id: "simonSwizzles",	questions: ["Где были ON и OFF?", "Какое двоичное число было спрятано?"] },
	{ original: "Simply Simon",	name: "Simply Simon",	id: "simplysimon",	questions: ["Which colors flashed in each stage?"] },
	{ original: "Simultaneous Simons",	name: "Simultaneous Simons",	id: "simultaneousSimons",	questions: ["Какие цвета горели на каждом Саймоне?"] },
	{ original: "Skewers",	name: "Skewers",	id: "Skewers",	questions: ["Каких цветов были драгоценности?"] },
	{ original: "Skyrim",	name: "Skyrim",	id: "skyrim",	questions: ["Какие расы, оружия, враги, города и крики дракона можно было выбрать, но не являлись решением?"] },
	{ original: "Slow Math",	name: "Slow Math",	id: "SlowMathModule",	questions: ["Какая была последняя тройка букв?"] },
	{ original: "Small Circle",	name: "Small Circle",	id: "smallCircle",	questions: ["На сколько сместилась последовательность?", "Какой сегмент звучал иначе в начале?", "Какие цвета были в решении?"] },
	{ original: "Small Talk",	name: "Small Talk",	id: "SmallTalk",	questions: ["What were the display words?"] },
	{ original: "Smash, Marry, Kill",	name: "Smash, Marry, Kill",	id: "smashmarrykill",	questions: ["В какой категории был каждый модуль?"] },
	{ original: "Snooker",	name: "Snooker",	id: "snooker",	questions: ["Сколько изначально было красных шаров?"] },
	{ original: "Snowflakes",	name: "Snowflakes",	id: "snowflakes",	questions: ["Какие снежинки были показаны?"] },
	{ original: "Sonic & Knuckles",	name: "Sonic & Knuckles",	id: "sonicKnuckles",	questions: ["Which monitor and badnik were shown?"] },
	{ original: "Sonic the Hedgehog",	name: "Sonic the Hedgehog",	id: "sonic",	questions: ["Which sound was played by each screen?", "What were the pictures?"] },
	{ original: "Space Traders",	name: "Space Traders",	id: "space_traders",	questions: ["Какой был максимальный налог за каждое судно?"] },
	{ original: "The Sphere",	name: "The Sphere",	id: "sphere",	questions: ["What were the flashed colors?"] },
	{ original: "Spongebob Birthday Identification",	name: "Spongebob Birthday Identification",	id: "spongebobBirthdayIdentification",	questions: ["Какие имена были введены?"] },
	{ original: "Stability",	name: "Stability",	id: "stabilityModule",	questions: ["Какими цветами горели светодиоды?", "Какой был идентификационный номер?"] },
	{ original: "Stable Time Signatures",	name: "Stable Time Signatures",	id: "StableTimeSignatures",	questions: ["What time signatures played?"] },
	{ original: "Stacked Sequences",	name: "Stacked Sequences",	id: "stackedSequences",	questions: ["Какие длины были у последовательностей?"] },
	{ original: "Stars",	name: "Stars",	id: "stars",	questions: ["Какая цифра была по центру?"] },
	{ original: "Starstruck",	name: "Starstruck",	id: "starstruck",	questions: ["Какие звёзды были показаны?"] },
	{ original: "State of Aggregation",	name: "State of Aggregation",	id: "stateOfAggregation",	questions: ["Какой элемент был показан?"] },
	{ original: "Stellar",	name: "Stellar",	id: "stellar",	questions: ["Какие были буквы?"] },
	{ original: "Stroop’s Test",	name: "Stroop’s Test",	id: "stroopsTest",	questions: ["What were the submitted slides?"] },
	{ original: "Stupid Slots",	name: "Stupid Slots",	id: "stupidSlots",	questions: ["Какие значения были у каждой стрелки?"] },
	{ original: "Subbly Jubbly",	name: "Subbly Jubbly",	id: "subblyJubbly",	questions: ["Какие были замены?"] },
	{ original: "Subscribe to Pewdiepie",	name: "Subscribe to Pewdiepie",	id: "subscribeToPewdiepie",	questions: ["Сколько подписчиков было у Pewdiepie и T-Series?"] },
	{ original: "Subway",	name: "Subway",	id: "subway",	questions: ["Какой хлеб просил покупатель?", "Чего не просил покупатель?"] },
	{ original: "Sugar Skulls",	name: "Sugar Skulls",	id: "sugarSkulls",	questions: ["Какие черепа были показаны?"] },
	{ original: "Suits and Colours",	name: "Suits and Colours",	id: "GSSuitsAndColours",	questions: ["Какие цвета и масти были в каждой клетке?"] },
	{ original: "Superparsing",	name: "Superparsing",	id: "superparsing",	questions: ["Какое слово было показано?"] },
	{ original: "SUSadmin",	name: "SUSadmin",	id: "susadmin",	questions: ["Какие протоколы безопасности были установлены?", "What was the version number?"] },
	{ original: "The Switch",	name: "The Switch",	id: "BigSwitch",	questions: ["What color were the LEDs?"] },
	{ original: "Switching Maze",	name: "Switching Maze",	id: "MazeSwitching",	questions: ["Какое было зерно?", "Какой был цвет начального лабиринта?"] },
	{ original: "Symbol Cycle",	name: "Symbol Cycle",	id: "SymbolCycleModule",	questions: ["Сколько повторяющихся символов было на каждом экране?"] },
	{ original: "Symbolic Coordinates",	name: "Symbolic Coordinates",	id: "symbolicCoordinates",	questions: ["Какие символы присутствовали на каждом этапе?"] },
	{ original: "Symbolic Tasha",	name: "Symbolic Tasha",	id: "symbolicTasha",	questions: ["Какие символы были на кнопках?", "Какие кнопки горели?"] },
	{ original: "Synapse Says",	name: "Synapse Says",	id: "synapseSays",	questions: ["What number was displayed at each stage?", "What positions were the colors in at each stage?", "What colors flashed at each stage?"] },
	{ original: "SYNC-125 [3]",	name: "SYNC-125 [3]",	id: "sync125_3",	questions: ["Что было на экране на каждом этапе?"] },
	{ original: "Synonyms",	name: "Synonyms",	id: "synonyms",	questions: ["Какое число было показано?"] },
	{ original: "Sysadmin",	name: "Sysadmin",	id: "sysadmin",	questions: ["Какой код ошибки вы исправили?"] },
	{ original: "TAC",	name: "TAC",	id: "TACModule",	questions: ["Which cards were swapped?", "Which cards were in your hand?"] },
	{ original: "Tap Code",	name: "Tap Code",	id: "tapCode",	questions: ["Какое слово было получено?"] },
	{ original: "Tasha Squeals",	name: "Tasha Squeals",	id: "tashaSqueals",	questions: ["Какие цвета горели?"] },
	{ original: "Tasque Managing",	name: "Tasque Managing",	id: "tasqueManaging",	questions: ["Где была начальная позиция?"] },
	{ original: "The Tea Set",	name: "The Tea Set",	id: "GSTeaSet",	questions: ["In what order were the ingredients displayed?"] },
	{ original: "Technical Keypad",	name: "Technical Keypad",	id: "TechnicalKeypad",	questions: ["Какие цифры были показаны?"] },
	{ original: "Ten-Button Color Code",	name: "Ten-Button Color Code",	id: "TenButtonColorCode",	questions: ["Какой был начальный цвет каждой кнопки на каждом этапе?"] },
	{ original: "Tenpins",	name: "Tenpins",	id: "tenpins",	questions: ["Какие были сплиты?"] },
	{ original: "Tetriamonds",	name: "Tetriamonds",	id: "tetriamonds",	questions: ["Какая была последовательность пульсирующих цветов?"] },
	{ original: "Thinking Wires",	name: "Thinking Wires",	id: "thinkingWiresModule",	questions: ["Какой первый провод нужно было перерезать?", "Какой был цвет второго верного перерезанного провода?", "Какое число было на экране?"] },
	{ original: "Thirty Dollar Module",	name: "Thirty Dollar Module",	id: "ThirtyDollarModule",	questions: ["Какие звуки были проиграны?"] },
	{ original: "Time Signatures",	name: "Time Signatures",	id: "timeSignatures",	questions: ["Какие сигнатуры были проиграны?"] },
	{ original: "Timezone",	name: "Timezone",	id: "timezone",	questions: ["Какой был город отбытия и прибытия?"] },
	{ original: "Tip Toe",	name: "Tip Toe",	id: "TipToe",	questions: ["Какие квадраты были безопасны в ряду 9 и 10?"] },
	{ original: "Topsy Turvy",	name: "Topsy Turvy",	id: "topsyTurvy",	questions: ["Какое слово было изначально показано?"] },
	{ original: "Touch Transmission",	name: "Touch Transmission",	id: "touchTransmission",	questions: ["Какое слово было передано?", "В каком порядке читался шрифт Брайля?"] },
	{ original: "Toxic Crystals",	name: "Toxic Crystals",	id: "ToxicCrystals",	questions: ["What letter was written on the casing when solving?"] },
	{ original: "Transmitted Morse",	name: "Transmitted Morse",	id: "transmittedMorseModule",	questions: ["Какие сообщения были получены?"] },
	{ original: "Triamonds",	name: "Triamonds",	id: "triamonds",	questions: ["Какая была последовательность пульсирующих цветов?"] },
	{ original: "Tribal Council",	name: "Tribal Council",	id: "TribalCouncil",	questions: ["Какие имена были на северо-востоке и юго-западе?"] },
	{ original: "Tricky Tetris Pieces",	name: "Tricky Tetris Pieces",	id: "TrickyTetrisPieces",	questions: ["What was the the shape of the first piece you pressed?", "What was the second color palette that the pieces converted to?"] },
	{ original: "Triple Term",	name: "Triple Term",	id: "tripleTermModule",	questions: ["Какие были пароли?"] },
	{ original: "Twodoku",	name: "Twodoku",	id: "TwodokuModule",	questions: ["Where were the digits, symbols, and highlights?"] },
	{ original: "UFO Satellites",	name: "UFO Satellites",	id: "UfoSatellites",	questions: ["Which numbers were present?"] },
	{ original: "Ultimate Cipher",	name: "Ultimate Cipher",	id: "ultimateCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Ultimate Cycle",	name: "Ultimate Cycle",	id: "ultimateCycle",	questions: ["Какое было сообщение и ответ?", "What was written on each dial?"] },
	{ original: "The Ultracube",	name: "The Ultracube",	id: "TheUltracubeModule",	questions: ["What were the rotations?"] },
	{ original: "UltraStores",	name: "UltraStores",	id: "UltraStores",	questions: ["Какие были повороты?"] },
	{ original: "Uncolour Flash",	name: "Uncolour Flash",	id: "uncolourFlash",	questions: ["What were the initial “YES” and “NO” sequences?"] },
	{ original: "Undertunneling",	name: "Undertunneling",	id: "undertunneling",	questions: ["What was the position in the maze after completing the first phase?"] },
	{ original: "Unfair Cipher",	name: "Unfair Cipher",	id: "unfairCipher",	questions: ["Какие инструкции были зашифрованы модулем?"] },
	{ original: "Unfair’s Cruel Revenge",	name: "Unfair’s Cruel Revenge",	id: "unfairsRevengeCruel",	questions: ["What were the decrypted instructions?"] },
	{ original: "Unfair’s Revenge",	name: "Unfair’s Revenge",	id: "unfairsRevenge",	questions: ["Какие инструкции были расшифрованы?"] },
	{ original: "Unicode",	name: "Unicode",	id: "UnicodeModule",	questions: ["Какие коды были введены?"] },
	{ original: "UNO!",	name: "UNO!",	id: "UNO",	questions: ["Какая была начальная карта?"] },
	{ original: "Unordered Keys",	name: "Unordered Keys",	id: "unorderedKeys",	questions: ["Какие были надписи, их цвета и цвета клавиш на каждом этапе?"] },
	{ original: "Unown Cipher",	name: "Unown Cipher",	id: "UnownCipher",	questions: ["Какие буквы были введены?"] },
	{ original: "Unpleasant Squares",	name: "Unpleasant Squares",	id: "unpleasantSquares",	questions: ["What color was each square?"] },
	{ original: "Updog",	name: "Updog",	id: "Updog",	questions: ["Какое слово было показано?", "Какие цвета мигали?"] },
	{ original: "USA Cycle",	name: "USA Cycle",	id: "USACycle",	questions: ["Какие штаты были показаны?"] },
	{ original: "V",	name: "V",	id: "V",	questions: ["Какие слова были показаны?"] },
	{ original: "Valves",	name: "Valves",	id: "valves",	questions: ["Какое было начальное состояние?"] },
	{ original: "Varicolour Flash",	name: "Varicolour Flash",	id: "varicolourFlash",	questions: ["Какие слова и каких цветов были на каждой цели?"] },
	{ original: "Variety",	name: "Variety",	id: "VarietyModule",	questions: ["Каких цветов были светодиоды?", "Чему было равно n на цветных ручках и лампочках?", "Какие цифры были показаны на цифровом экране?", "Какие слова можно было составить на экране с буквами?", "Какие максимальные значения были у таймеров?"] },
	{ original: "Vcrcs",	name: "Vcrcs",	id: "VCRCS",	questions: ["Какое слово было показано?"] },
	{ original: "Vectors",	name: "Vectors",	id: "vectorsModule",	questions: ["Какие были цвета векторов?"] },
	{ original: "Vexillology",	name: "Vexillology",	id: "vexillology",	questions: ["Какие были цвета на флагштоке?"] },
	{ original: "Violet Cipher",	name: "Violet Cipher",	id: "violetCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Walking Cube",	name: "Walking Cube",	id: "WalkingCubeModule",	questions: ["По каким клеткам прошёлся куб?"] },
	{ original: "Warning Signs",	name: "Warning Signs",	id: "warningSigns",	questions: ["Какой знак был показан?"] },
	{ original: "WASD",	name: "WASD",	id: "wasdModule",	questions: ["Какое место было показано?"] },
	{ original: "Watching Paint Dry",	name: "Watching Paint Dry",	id: "watchingPaintDry",	questions: ["Сколько было мазков кистью на модуле?"] },
	{ original: "Wavetapping",	name: "Wavetapping",	id: "Wavetapping",	questions: ["Какой был верный узор на каждом этапе?"] },
	{ original: "The Weakest Link",	name: "The Weakest Link",	id: "TheWeakestLink",	questions: ["Who was eliminated?", "Who joined you in the Money Phase?", "What were the other contestants’ skills and correct answer ratios?"] },
	{ original: "What’s on Second",	name: "What’s on Second",	id: "WhatsOnSecond",	questions: ["Какой текст и какого цвета был на экране на каждом этапе?"] },
	{ original: "White Arrows",	name: "White Arrows",	id: "WhiteArrows",	questions: ["Какие стрелки были не белыми?"] },
	{ original: "White Cipher",	name: "White Cipher",	id: "whiteCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "WhoOF",	name: "WhoOF",	id: "whoOF",	questions: ["Что было на экране на каждом этапе?"] },
	{ original: "Who’s on Gas",	name: "Who’s on Gas",	id: "whosOnGas",	questions: ["What was displayed in the first phase of each stage?"] },
	{ original: "Who’s on Morse",	name: "Who’s on Morse",	id: "whosOnMorseModule",	questions: ["What word was transmitted in each stage?"] },
	{ original: "The Wire",	name: "The Wire",	id: "wire",	questions: ["What were the colors of the dials?", "What was the displayed number?"] },
	{ original: "Wire Ordering",	name: "Wire Ordering",	id: "kataWireOrdering",	questions: ["Какие цвета и числа были на экранах?", "Какие цвета были на проводах?"] },
	{ original: "Wolf, Goat, and Cabbage",	name: "Wolf, Goat, and Cabbage",	id: "wolfGoatCabbageModule",	questions: ["Какие существа присутствовали?", "Какого размера была лодка?"] },
	{ original: "Word Count",	name: "Word Count",	id: "wordCount",	questions: ["What was the displayed number?"] },
	{ original: "Wumbo",	name: "Wumbo",	id: "wumbo",	questions: ["Какое было число?"] },
	{ original: "The Xenocryst",	name: "The Xenocryst",	id: "GSXenocryst",	questions: ["What was the color of each flash?"] },
	{ original: "XmORse Code",	name: "XmORse Code",	id: "xmorse",	questions: ["Какие буквы были показаны?", "Какое слово было расшифровано?"] },
	{ original: "xobekuJ ehT",	name: "xobekuJ ehT",	id: "xobekuj",	questions: ["Какая песня была проиграна?"] },
	{ original: "X-Ring",	name: "X-Ring",	id: "xring",	questions: ["Какие символы были просканированы?"] },
	{ original: "X-Rotor",	name: "X-Rotor",	id: "xrotor",	questions: ["Which symbols were scanned?"] },
	{ original: "XY-Ray",	name: "XY-Ray",	id: "xyRay",	questions: ["Какие фигуры были просканированы?"] },
	{ original: "The Yellow Button",	name: "The Yellow Button",	id: "YellowButtonModule",	questions: ["What were the colors?"] },
	{ original: "Yellow Button’t",	name: "Yellow Button’t",	id: "yellowbuttont",	questions: ["Какое было имя файла?"] },
	{ original: "Yellow Cipher",	name: "Yellow Cipher",	id: "yellowCipher",	questions: ["Что было на каждом экране?"] },
	{ original: "Yellow Huffman Cipher",	name: "Yellow Huffman Cipher",	id: "YellowHuffmanCipherModule",	questions: ["What was on each screen?"] },
	{ original: "Zero, Zero",	name: "Zero, Zero",	id: "zeroZero",	questions: ["Какой цвет и сколько вершин было у каждой звезды?", "Какие цветные квадраты присутствовали?"] },
	{ original: "Zoni",	name: "Zoni",	id: "lgndZoni",	questions: ["Какие слова были расшифрованы?"] },
	{ original: "Épelle-moi Ça",	name: "Épelle-moi Ça",	id: "epelleMoiCa",	questions: ["Какое слово нужно было прописать?"] },
];