let SouvenirModuleData = [
	{ name: "...?",	id: "punctuationMarks",	questions: ["What was the displayed number?"] },
	{ name: "100 Levels of Defusal",	id: "100LevelsOfDefusal",	questions: ["What were the displayed letters?"] },
	{ name: "1000 Words",	id: "OneThousandWords",	questions: ["What were the words shown?"] },
	{ name: "1D Chess",	id: "1DChess",	questions: ["What were your and Rustmate’s moves?"] },
	{ name: "3 LEDs",	id: "threeLEDsModule",	questions: ["What was the initial state of the LEDs?"] },
	{ name: "3D Maze",	id: "spwiz3DMaze",	questions: ["What were the markings?","What was the cardinal direction?"] },
	{ name: "3D Tap Code",	id: "3DTapCodeModule",	questions: ["What was the received word?"] },
	{ name: "3D Tunnels",	id: "3dTunnels",	questions: ["What were the goal symbols?"] },
	{ name: "3N+1",	id: "threeNPlusOne",	questions: ["What number was initially displayed?"] },
	{ name: "64",	id: "64",	questions: ["What was the displayed number?"] },
	{ name: "7",	id: "7",	questions: ["What were the LED colors for each stage?","What was each channel’s initial value?"] },
	{ name: "9-Ball",	id: "GSNineBall",	questions: ["What were the numbers on each ball?"] },
	{ name: "A Letter",	id: "LetterModule",	questions: ["What was the initially displayed letter?"] },
	{ name: "A Square",	id: "ASquareModule",	questions: ["What were the index colors?","What were the submitted colors?"] },
	{ name: "Abyss",	id: "GSAbyss",	questions: ["What were the characters displayed?"] },
	{ name: "Accumulation",	id: "accumulation",	questions: ["What were the background and border colors on each stage?"] },
	{ name: "Adventure Game",	id: "spwizAdventureGame",	questions: ["Which correct items did you use?","Which enemy were you fighting?"] },
	{ name: "Affine Cycle",	id: "affineCycle",	questions: ["What were the message and response?"] },
	{ name: "Alfa-Bravo",	id: "alfa_bravo",	questions: ["What final letter was pressed?","What letters were to the left and right of the final one?","What was the last digit on the small display?"] },
	{ name: "Algebra",	id: "algebra",	questions: ["What were the first two equations?"] },
	{ name: "Algorithmia",	id: "algorithmia",	questions: ["What were the starting and goal positions?","What color was the bulb?","Which numbers were present in the seed?"] },
	{ name: "Alpha-Bits",	id: "alphaBits",	questions: ["What characters were displayed on each screen?"] },
	{ name: "Alphabet Numbers",	id: "alphabetNumbers",	questions: ["What were the numbers on the buttons in each stage?"] },
	{ name: "Alphabet Tiles",	id: "AlphabetTiles",	questions: ["What were the letters shown during each cycle?","What was the missing letter?"] },
	{ name: "Alphabetical Ruling",	id: "alphabeticalRuling",	questions: ["What were the letters and numbers displayed in each stage?"] },
	{ name: "The Arena",	id: "TheArena",	questions: ["What was the maximum weapon damage of the attack phase?","What enemies were present in the defend phase?","What numbers were present in the grab phase?"] },
	{ name: "Arithmelogic",	id: "arithmelogic",	questions: ["What was the symbol on the submit button?","What were the numbers selectable on the screens?"] },
	{ name: "ASCII Maze",	id: "asciiMaze",	questions: ["What characters were displayed?"] },
	{ name: "The Azure Button",	id: "AzureButtonModule",	questions: ["What were T and the other displayed cards?","What was M?","What were the arrows?"] },
	{ name: "Bakery",	id: "bakery",	questions: ["Which menu items were present?"] },
	{ name: "Bamboozled Again",	id: "bamboozledAgain",	questions: ["What were the text and color of each correct button?","What were the decrypted text and color of each displayed message?"] },
	{ name: "Bamboozling Button",	id: "bamboozlingButton",	questions: ["What color was the button in each stage?","What were the labels on the button in each stage?","What were the displays and their colors in each stage?"] },
	{ name: "Barcode Cipher",	id: "BarcodeCipherModule",	questions: ["What was the screen number?","What was the edgework represented by each barcode?","What was the answer for each barcode?"] },
	{ name: "Bartending",	id: "BartendingModule",	questions: ["Which ingredient was in which position?"] },
	{ name: "Bean Sprouts",	id: "beanSprouts",	questions: ["What colors were the eaten sprouts?","Where were the eaten beans?"] },
	{ name: "Beans",	id: "beans",	questions: ["What color were the eaten beans?"] },
	{ name: "Big Bean",	id: "bigBean",	questions: ["What color was the bean?"] },
	{ name: "Big Circle",	id: "BigCircle",	questions: ["Which colors were in the solution?"] },
	{ name: "Binary",	id: "Binary",	questions: ["What word was displayed?"] },
	{ name: "Binary LEDs",	id: "BinaryLeds",	questions: ["At which numeric value did you cut the correct wire?"] },
	{ name: "Binary Shift",	id: "binary_shift",	questions: ["What were the initial numbers?","What number was selected at each stage?"] },
	{ name: "Bitmaps",	id: "BitmapsModule",	questions: ["How many pixels were black/white in each quadrant?"] },
	{ name: "Black Cipher",	id: "blackCipher",	questions: ["What was on each screen?"] },
	{ name: "Blind Maze",	id: "BlindMaze",	questions: ["What colors were the buttons?","Which maze did you solve the module on?"] },
	{ name: "Blinkstop",	id: "blinkstopModule",	questions: ["How many times did the LED flash?","Which color did the LED flash the least?"] },
	{ name: "Blockbusters",	id: "blockbusters",	questions: ["What was the last letter pressed?"] },
	{ name: "Blue Arrows",	id: "blueArrowsModule",	questions: ["What were the letters on the screen?"] },
	{ name: "The Blue Button",	id: "BlueButtonModule",	questions: ["What were D, E, F, G, H, M, N, P, Q, and X?"] },
	{ name: "Blue Cipher",	id: "blueCipher",	questions: ["What was on each screen?"] },
	{ name: "Bob Barks",	id: "ksmBobBarks",	questions: ["What were the indicator labels?","Which buttons flashed in sequence?"] },
	{ name: "Boggle",	id: "boggle",	questions: ["Which letters were initially visible?"] },
	{ name: "Bomb Diffusal",	id: "bombDiffusal",	questions: ["What was the license number?"] },
	{ name: "Book of Mario",	id: "BookOfMarioModule",	questions: ["Who said something in each stage?","What was each character’s quote?"] },
	{ name: "Boolean Wires",	id: "booleanWires",	questions: ["Which operators were submitted in each stage?"] },
	{ name: "Boomtar the Great",	id: "boomtarTheGreat",	questions: ["What were the first and second rules?"] },
	{ name: "Boxing",	id: "boxing",	questions: ["Which contestants and substitutes (first and last names) were shown?","Who had which punch strength rating?"] },
	{ name: "Braille",	id: "BrailleModule",	questions: ["What was the solution word?"] },
	{ name: "Breakfast Egg",	id: "breakfastEgg",	questions: ["Which colors appeared on the egg?"] },
	{ name: "Broken Buttons",	id: "BrokenButtonsModule",	questions: ["What were the correct buttons you pressed?"] },
	{ name: "Broken Guitar Chords",	id: "BrokenGuitarChordsModule",	questions: ["What was the displayed chord?","Which string was broken?"] },
	{ name: "Brown Cipher",	id: "brownCipher",	questions: ["What was on each screen?"] },
	{ name: "Brush Strokes",	id: "brushStrokes",	questions: ["What was the color of the middle contact point?"] },
	{ name: "The Bulb",	id: "TheBulbModule",	questions: ["What were the correct button presses?"] },
	{ name: "Burger Alarm",	id: "burgerAlarm",	questions: ["What were the displayed digits?","What were the order numbers?"] },
	{ name: "Burglar Alarm",	id: "burglarAlarm",	questions: ["What were the displayed digits?"] },
	{ name: "The Button",	id: "BigButton",	questions: ["What color did the light glow?"] },
	{ name: "Button Sequence",	id: "buttonSequencesModule",	questions: ["How many times did each color occur?"] },
	{ name: "Caesar Cycle",	id: "caesarCycle",	questions: ["What were the message and response?"] },
	{ name: "Caesar Psycho",	id: "caesarPsycho",	questions: ["What text and color were on the top display in each stage?"] },
	{ name: "Calendar",	id: "calendar",	questions: ["What was the color of the LED?"] },
	{ name: "Cartinese",	id: "cartinese",	questions: ["What lyrics were played by each button?","What color was each button?"] },
	{ name: "Catchphrase",	id: "catchphrase",	questions: ["What were the colours of the panels?"] },
	{ name: "Challenge & Contact",	id: "challengeAndContact",	questions: ["What were the submitted answers?"] },
	{ name: "Character Codes",	id: "characterCodes",	questions: ["What were the characters?"] },
	{ name: "Character Shift",	id: "characterShift",	questions: ["What were the characters on the sliders?"] },
	{ name: "Character Slots",	id: "characterSlots",	questions: ["Who was displayed in each slot for each stage?"] },
	{ name: "Cheap Checkout",	id: "CheapCheckoutModule",	questions: ["What were the paid amounts?"] },
	{ name: "Cheep Checkout",	id: "cheepCheckout",	questions: ["Which birds were present?"] },
	{ name: "Chess",	id: "ChessModule",	questions: ["What were the coordinates?"] },
	{ name: "Chinese Counting",	id: "chineseCounting",	questions: ["What colors were the LEDs?"] },
	{ name: "Chord Qualities",	id: "ChordQualities",	questions: ["What was the given chord quality?","What notes were in the given chord?"] },
	{ name: "The Code",	id: "theCodeModule",	questions: ["What was the displayed number?"] },
	{ name: "Codenames",	id: "codenames",	questions: ["Which words were submitted?"] },
	{ name: "Coffeebucks",	id: "coffeebucks",	questions: ["What was the last served coffee?"] },
	{ name: "Coinage",	id: "Coinage",	questions: ["Which coin was flipped?"] },
	{ name: "Color Addition",	id: "colorAddition",	questions: ["What were the three numbers?"] },
	{ name: "Color Braille",	id: "ColorBrailleModule",	questions: ["What was the mangling applied?","What were the red, green, and blue words?"] },
	{ name: "Color Decoding",	id: "Color Decoding",	questions: ["What were the indicator patterns and colors in each stage?"] },
	{ name: "Color Morse",	id: "ColorMorseModule",	questions: ["What were the colors of the LEDs?","What characters were flashed by the LEDs?"] },
	{ name: "Colored Keys",	id: "lgndColoredKeys",	questions: ["What was the displayed word and its color?","What were the colors and letters on each key?"] },
	{ name: "Colored Squares",	id: "ColoredSquaresModule",	questions: ["What was the first color group?"] },
	{ name: "Colored Switches",	id: "ColoredSwitchesModule",	questions: ["What was the initial position of the switches?","What was the switches’ position when the LEDs came on?"] },
	{ name: "Colors Maximization",	id: "colors_maximization",	questions: ["What was the submitted score?","What colors were submitted?","How many buttons were there of each color?"] },
	{ name: "Colour Flash",	id: "ColourFlash",	questions: ["What was the color of the last word in the sequence?"] },
	{ name: "Coloured Cubes",	id: "ColouredCubes",	questions: ["What were the colours of the cubes and stage lights in each stage?"] },
	{ name: "Connection Check",	id: "graphModule",	questions: ["What number pairs were present?"] },
	{ name: "Coordinates",	id: "CoordinatesModule",	questions: ["What was the grid size?","What was the solution you selected first?"] },
	{ name: "Coral Cipher",	id: "coralCipher",	questions: ["What was on each screen?"] },
	{ name: "Corners",	id: "CornersModule",	questions: ["What were the colors of the corners?"] },
	{ name: "Cornflower Cipher",	id: "cornflowerCipher",	questions: ["What was on each screen?"] },
	{ name: "Cosmic",	id: "CosmicModule",	questions: ["What was the number initially shown?"] },
	{ name: "Crazy Hamburger",	id: "GSCrazyHamburger",	questions: ["What were the displayed ingredients?"] },
	{ name: "Crazy Maze",	id: "CrazyMazeModule",	questions: ["What were the starting and goal positions?"] },
	{ name: "Cream Cipher",	id: "creamCipher",	questions: ["What was on each screen?"] },
	{ name: "Creation",	id: "CreationModule",	questions: ["What were the weather conditions on each day?"] },
	{ name: "Crimson Cipher",	id: "crimsonCipher",	questions: ["What was on each screen?"] },
	{ name: "Critters",	id: "CrittersModule",	questions: ["What was the alteration color?"] },
	{ name: "Cruel Binary",	id: "CruelBinary",	questions: ["What was the displayed word?"] },
	{ name: "Cruel Keypads",	id: "CruelKeypads",	questions: ["What were the displayed symbols and what was the color of the bar in each stage?"] },
	{ name: "The cRule",	id: "the_cRule",	questions: ["Which cells were prefilled at the start?","Which symbol pair appeared where?"] },
	{ name: "Cryptic Cycle",	id: "crypticCycle",	questions: ["What were the message and response?"] },
	{ name: "Cryptic Keypad",	id: "GSCrypticKeypad",	questions: ["What were the labels and cardinal directions of each key?"] },
	{ name: "The Cube",	id: "cube",	questions: ["What were the cube rotations?"] },
	{ name: "Cursed Double-Oh",	id: "CursedDoubleOhModule",	questions: ["What was the first digit of the initial number?"] },
	{ name: "Customer Identification",	id: "xelCustomerIdentification",	questions: ["Which customers were displayed?"] },
	{ name: "The Cyan Button",	id: "CyanButtonModule",	questions: ["Where was the button at each stage?"] },
	{ name: "DACH Maze",	id: "DACH",	questions: ["Which region did you depart from?"] },
	{ name: "Deaf Alley",	id: "deafAlleyModule",	questions: ["What was the shape generated?"] },
	{ name: "The Deck of Many Things",	id: "deckOfManyThings",	questions: ["What deck did the first card belong to?"] },
	{ name: "Decolored Squares",	id: "DecoloredSquaresModule",	questions: ["What were the colors defining the starting row and column?"] },
	{ name: "Decolour Flash",	id: "DecolourFlashModule",	questions: ["What were the words and colours of each goal?"] },
	{ name: "Denial Displays",	id: "DenialDisplaysModule",	questions: ["What was initially on the displays?"] },
	{ name: "Devilish Eggs",	id: "devilishEggs",	questions: ["What were the rotations?","What were the numbers and letters shown on the prism?"] },
	{ name: "Diffusion",	id: "diffusion",	questions: ["What concentrations were displayed in each compartment?"] },
	{ name: "Digisibility",	id: "digisibility",	questions: ["What were the numbers on the buttons?"] },
	{ name: "Digit String",	id: "digitString",	questions: ["What was the displayed digit string?"] },
	{ name: "Dimension Disruption",	id: "dimensionDisruption",	questions: ["What were the visible characters?"] },
	{ name: "Directional Button",	id: "directionalButton",	questions: ["How many times did you press the button in each stage?"] },
	{ name: "Discolored Squares",	id: "DiscoloredSquaresModule",	questions: ["What was the remembered position for each color?"] },
	{ name: "Divisible Numbers",	id: "divisibleNumbers",	questions: ["What were the correct button presses?","What were the numbers in each stage?"] },
	{ name: "Double Arrows",	id: "doubleArrows",	questions: ["What was the starting position?","Which buttons moved in which directions in the grid?"] },
	{ name: "Double Color",	id: "doubleColor",	questions: ["What was the screen color in each stage?"] },
	{ name: "Double Digits",	id: "doubleDigitsModule",	questions: ["What were the most recent numbers on the displays?"] },
	{ name: "Double Expert",	id: "doubleExpert",	questions: ["What was the starting key number?","What was the submitted word?"] },
	{ name: "Double Listening",	id: "doubleListening",	questions: ["What sounds played?"] },
	{ name: "Double Screen",	id: "doubleScreenModule",	questions: ["What colors were the screens on each stage?"] },
	{ name: "Double-Oh",	id: "DoubleOhModule",	questions: ["Which button was the submit button?"] },
	{ name: "Dr. Doctor",	id: "DrDoctorModule",	questions: ["Which diseases and symptoms were listed?"] },
	{ name: "Dreamcipher",	id: "ksmDreamcipher",	questions: ["What was the decrypted word?"] },
	{ name: "The Duck",	id: "theDuck",	questions: ["What was the color of the curtain?","How was the duck approached?"] },
	{ name: "Dumb Waiters",	id: "dumbWaiters",	questions: ["Which players were present?"] },
	{ name: "Earthbound",	id: "EarthboundModule",	questions: ["What was the background number?","Which monster was shown?"] },
	{ name: "eeB gnillepS",	id: "eeBgnilleps",	questions: ["What word was asked to be spelled?"] },
	{ name: "Eight",	id: "eight",	questions: ["What was the last digit on the small display?","What was the position of the last broken digit?","What were the last resulting digits?","What was the last displayed number?"] },
	{ name: "Elder Futhark",	id: "elderFuthark",	questions: ["What were the runes shown?"] },
	{ name: "Encrypted Dice",	id: "EncryptedDice",	questions: ["Which numbers were rolled in each stage?"] },
	{ name: "Encrypted Equations",	id: "EncryptedEquationsModule",	questions: ["What were the main shapes of the three operands?"] },
	{ name: "Encrypted Hangman",	id: "encryptedHangman",	questions: ["What was the encrypted module name and encryption method?"] },
	{ name: "Encrypted Maze",	id: "encryptedMaze",	questions: ["Which symbol was spinning which way?"] },
	{ name: "Encrypted Morse",	id: "EncryptedMorse",	questions: ["What were the received call and sent response?"] },
	{ name: "Encryption Bingo",	id: "encryptionBingo",	questions: ["What was the first encoding used?"] },
	{ name: "Enigma Cycle",	id: "enigmaCycle",	questions: ["What were the message and response?"] },
	{ name: "Entry Number Four",	id: "GSEntryNumberFour",	questions: ["What were the numbers shown, the expected fourth entry and the constant coefficient?"] },
	{ name: "Entry Number One",	id: "GSEntryNumberOne",	questions: ["What were the numbers shown, the expected first entry and the constant coefficient?"] },
	{ name: "Equations X",	id: "equationsXModule",	questions: ["What was the displayed symbol?"] },
	{ name: "Etterna",	id: "etterna",	questions: ["What beat was the input for each arrow?"] },
	{ name: "Exoplanets",	id: "exoplanets",	questions: ["What were the starting and final target planet and digit?"] },
	{ name: "Factoring Maze",	id: "factoringMaze",	questions: ["What were the prime numbers used?"] },
	{ name: "Factory Maze",	id: "factoryMaze",	questions: ["What room did you start in?"] },
	{ name: "Fast Math",	id: "fastMath",	questions: ["What was the last pair of letters?"] },
	{ name: "Faulty Buttons",	id: "GSFaultyButtons",	questions: ["Which button did each button refer to?"] },
	{ name: "Faulty RGB Maze",	id: "faultyrgbMaze",	questions: ["Where were the exit and keys of the maze?","What was the maze number for each maze?"] },
	{ name: "Find the Date",	id: "DateFinder",	questions: ["What were the day, month, and year for each stage?"] },
	{ name: "Five Letter Words",	id: "FiveLetterWords",	questions: ["What were the displayed words?"] },
	{ name: "FizzBuzz",	id: "fizzBuzzModule",	questions: ["What were the displayed numbers?"] },
	{ name: "Flags",	id: "FlagsModule",	questions: ["What were the country flags, the main flag, and the displayed number?"] },
	{ name: "Flashing Arrows",	id: "flashingArrowsModule",	questions: ["What was the number shown on the display?","What were the relevant arrow’s colors?"] },
	{ name: "Flashing Lights",	id: "flashingLights",	questions: ["How many times did each LED flash each color?"] },
	{ name: "Flavor Text",	id: "FlavorText",	questions: ["Which module’s flavor text was presented?"] },
	{ name: "Flavor Text EX",	id: "FlavorTextCruel",	questions: ["Which module’s flavor text was presented in each stage?"] },
	{ name: "Flyswatting",	id: "flyswatting",	questions: ["Which flies were present, but not in the solution?"] },
	{ name: "Follow Me",	id: "FollowMe",	questions: ["What were the flashing directions?"] },
	{ name: "Forest Cipher",	id: "forestCipher",	questions: ["What was on each screen?"] },
	{ name: "Forget Any Color",	id: "ForgetAnyColor",	questions: ["What colors were the cylinders in each stage?","Which figure was used in each stage?"] },
	{ name: "Forget Everything",	id: "HexiEvilFMN",	questions: ["What were the displayed digits in stage one?"] },
	{ name: "Forget Me",	id: "forgetMe",	questions: ["What numbers were in which positions in the initial puzzle?"] },
	{ name: "Forget Me Not",	id: "MemoryV2",	questions: ["What were the displayed digits in each stage?"] },
	{ name: "Forget Me Now",	id: "ForgetMeNow",	questions: ["What were the displayed digits?"] },
	{ name: "Forget The Colors",	id: "ForgetTheColors",	questions: ["What were the large display, gear and the sine number’s last digit in each stage?","Which edgework-based rule was applied in each stage?"] },
	{ name: "Forget This",	id: "forgetThis",	questions: ["What were the displayed digit and color in each stage?"] },
	{ name: "Forget’s Ultimate Showdown",	id: "ForgetsUltimateShowdownModule",	questions: ["What was the initial number?","What was the bottom number?","What was the answer?","What were the encryption methods used?"] },
	{ name: "Free Parking",	id: "freeParking",	questions: ["What was the player token?"] },
	{ name: "Functions",	id: "qFunctions",	questions: ["What was the last digit of the first query result?","What were the numbers and letter shown at the bottom?"] },
	{ name: "The Fuse Box",	id: "FuseBox",	questions: ["What colors flashed?","What arrows were correct?"] },
	{ name: "Gadgetron Vendor",	id: "lgndGadgetronVendor",	questions: ["What were the displayed weapons?"] },
	{ name: "Game Of Life Cruel",	id: "GameOfLifeCruel",	questions: ["Which color combinations occurred?"] },
	{ name: "The Gamepad",	id: "TheGamepadModule",	questions: ["What were the numbers?"] },
	{ name: "The Garnet Thief",	id: "theGarnetThief",	questions: ["Which faction did each competitor claim to have chosen?"] },
	{ name: "Girlfriend",	id: "Girlfriend",	questions: ["What was the chosen language?"] },
	{ name: "The Glitched Button",	id: "GlitchedButtonModule",	questions: ["What was the cycling bit sequence?"] },
	{ name: "The Gray Button",	id: "GrayButtonModule",	questions: ["What were the coordinates on the display?"] },
	{ name: "Gray Cipher",	id: "grayCipher",	questions: ["What was on each screen?"] },
	{ name: "The Great Void",	id: "greatVoid",	questions: ["What were the digits and colors?"] },
	{ name: "Green Arrows",	id: "greenArrowsModule",	questions: ["What was the last number on the display?"] },
	{ name: "The Green Button",	id: "GreenButtonModule",	questions: ["What was the submitted word?"] },
	{ name: "Green Cipher",	id: "greenCipher",	questions: ["What was on each screen?"] },
	{ name: "Gridlock",	id: "GridlockModule",	questions: ["What was the starting color?","What were the starting and ending locations?"] },
	{ name: "Grocery Store",	id: "groceryStore",	questions: ["What was the first item shown?"] },
	{ name: "Gryphons",	id: "gryphons",	questions: ["What were the gryphon’s name and age?"] },
	{ name: "Guess Who?",	id: "GuessWho",	questions: ["Who was the person recalled?"] },
	{ name: "h",	id: "Averageh",	questions: ["What was the transmitted letter?"] },
	{ name: "Hereditary Base Notation",	id: "hereditaryBaseNotationModule",	questions: ["What was the number on the bottom display?"] },
	{ name: "The Hexabutton",	id: "hexabutton",	questions: ["What label was printed on the button?"] },
	{ name: "Hexamaze",	id: "HexamazeModule",	questions: ["What was the color of the pawn?"] },
	{ name: "hexOS",	id: "hexOS",	questions: ["What were the deciphered letters or phrase?","What were the 3-digit numbers cycled by the screen?","What were the rhythm values?"] },
	{ name: "Hidden Colors",	id: "lgndHiddenColors",	questions: ["What was the main LED’s color?"] },
	{ name: "The High Score",	id: "ksmHighScore",	questions: ["What was the player’s position and score?"] },
	{ name: "Hill Cycle",	id: "hillCycle",	questions: ["What were the message and response?"] },
	{ name: "Hinges",	id: "hinges",	questions: ["What were the initially present hinges?"] },
	{ name: "Hogwarts",	id: "HogwartsModule",	questions: ["Which House was each module solved for?"] },
	{ name: "Hold Ups",	id: "KritHoldUps",	questions: ["What was the name of each shadow shown?"] },
	{ name: "Homophones",	id: "homophones",	questions: ["What were the displayed phrases?"] },
	{ name: "Horrible Memory",	id: "horribleMemory",	questions: ["What were the positions, labels, and colors of the buttons pressed in each stage?"] },
	{ name: "Human Resources",	id: "HumanResourcesModule",	questions: ["Which employees were hired and fired?","Which descriptors were shown in red and green?"] },
	{ name: "Hunting",	id: "hunting",	questions: ["Which stages had the column or row symbol first?"] },
	{ name: "The Hypercube",	id: "TheHypercubeModule",	questions: ["What were the rotations?"] },
	{ name: "The Hyperlink",	id: "hyperlink",	questions: ["What was the hyperlink?","Which module was referenced?"] },
	{ name: "Ice Cream",	id: "iceCreamModule",	questions: ["Who were the customers?","Which flavors were on offer to each customer?"] },
	{ name: "Identification Crisis",	id: "identificationCrisis",	questions: ["What were the shapes and identification modules used?"] },
	{ name: "Identity Parade",	id: "identityParade",	questions: ["What were the hair colors, builds and attires listed on the module?"] },
	{ name: "The Impostor",	id: "impostor",	questions: ["Which module was being imitated?"] },
	{ name: "Indigo Cipher",	id: "indigoCipher",	questions: ["What was on each screen?"] },
	{ name: "Infinite Loop",	id: "InfiniteLoop",	questions: ["What was the selected word?"] },
	{ name: "Ingredients",	id: "ingredients",	questions: ["Which ingredients were listed and which were used?"] },
	{ name: "Inner Connections",	id: "InnerConnectionsModule",	questions: ["What color was the LED?","What was the digit flashed in Morse?"] },
	{ name: "Interpunct",	id: "interpunct",	questions: ["What was the symbol displayed in each stage?"] },
	{ name: "IPA",	id: "ipa",	questions: ["What was the correct symbol?"] },
	{ name: "The iPhone",	id: "iPhone",	questions: ["What was the PIN?"] },
	{ name: "Jenga",	id: "jenga",	questions: ["What symbols were on the first correctly pulled block?"] },
	{ name: "The Jewel Vault",	id: "jewelVault",	questions: ["What number were wheels A–D?"] },
	{ name: "Jumble Cycle",	id: "jumbleCycle",	questions: ["What were the message and response?"] },
	{ name: "Juxtacolored Squares",	id: "JuxtacoloredSquaresModule",	questions: ["What was each square’s color?"] },
	{ name: "Kanji",	id: "KanjiModule",	questions: ["What was the displayed word in each stage?"] },
	{ name: "The Kanye Encounter",	id: "TheKanyeEncounter",	questions: ["What food items were shown?"] },
	{ name: "Keypad Combinations",	id: "keypadCombinations",	questions: ["What were the numbers, but not part of the answer?"] },
	{ name: "Keypad Magnified",	id: "keypadMagnified",	questions: ["What was the position of the LED?"] },
	{ name: "Keywords",	id: "xtrkeywords",	questions: ["What were the letters on the display?"] },
	{ name: "Know Your Way",	id: "KnowYourWay",	questions: ["Which way was the arrow pointing?","Which LED was green?"] },
	{ name: "Kudosudoku",	id: "KudosudokuModule",	questions: ["Which squares were initially pre-filled?"] },
	{ name: "The Labyrinth",	id: "labyrinth",	questions: ["Where were the portals, and which layers were they on?"] },
	{ name: "Ladder Lottery",	id: "ladderLottery",	questions: ["Which light was on?"] },
	{ name: "Ladders",	id: "ladders",	questions: ["Which colors were present on the second ladder?","What color was missing on the third ladder?"] },
	{ name: "Langton’s Anteater",	id: "GSLangtonsAnteater",	questions: ["What was the initial state of the grid?"] },
	{ name: "Lasers",	id: "lasers",	questions: ["What number was on each hatch?"] },
	{ name: "LED Encryption",	id: "LEDEnc",	questions: ["What were the correct button presses?"] },
	{ name: "LED Math",	id: "lgndLEDMath",	questions: ["What were the LED colors?"] },
	{ name: "LEDs",	id: "leds",	questions: ["What was the initial color of the changed LED?"] },
	{ name: "LEGOs",	id: "LEGOModule",	questions: ["What were the dimensions of each color piece?"] },
	{ name: "Letter Math",	id: "letterMath",	questions: ["What were the letters on the display?"] },
	{ name: "Light Bulbs",	id: "LightBulbs",	questions: ["What were the colors of the bulbs?"] },
	{ name: "Linq",	id: "Linq",	questions: ["What were the functions?"] },
	{ name: "Lion’s Share",	id: "LionsShareModule",	questions: ["Which year was displayed?","Which lions were present but removed?"] },
	{ name: "Listening",	id: "Listening",	questions: ["What sound played?"] },
	{ name: "Logic Gates",	id: "logicGates",	questions: ["What were the logic gates?"] },
	{ name: "Logical Buttons",	id: "logicalButtonsModule",	questions: ["What were the colors and labels of each button in each stage?","What were the final operators in each stage?"] },
	{ name: "Lombax Cubes",	id: "lgndLombaxCubes",	questions: ["What were the letters on the button?"] },
	{ name: "The London Underground",	id: "londonUnderground",	questions: ["What were the departure and destination stations?"] },
	{ name: "Long Words",	id: "LongWords",	questions: ["What was the word on the top display?"] },
	{ name: "M&Ms",	id: "MandMs",	questions: ["What were the labels on the buttons and their colors?"] },
	{ name: "M&Ns",	id: "MandNs",	questions: ["What were the colors of the labels on the buttons?","What was the label of the correct button?"] },
	{ name: "M-Seq",	id: "mSeq",	questions: ["What were the obtained digits?","What was the final number from the iteration process?"] },
	{ name: "Mad Memory",	id: "MadMemory",	questions: ["What was on the display in each stage?"] },
	{ name: "Mafia",	id: "MafiaModule",	questions: ["Who was a player, but not the Godfather?"] },
	{ name: "Magenta Cipher",	id: "magentaCipher",	questions: ["What was on each screen?"] },
	{ name: "Mahjong",	id: "MahjongModule",	questions: ["What were the first two matched pairs?","What was the bottom-left tile?"] },
	{ name: "Main Page",	id: "mainpage",	questions: ["Which color and message did the bubble (not) display?","Which main page did Homestar, the background, or any of the buttons’ effects come from?"] },
	{ name: "Maritime Flags",	id: "MaritimeFlagsModule",	questions: ["What bearing was signaled?","What callsign was signaled?"] },
	{ name: "Maroon Cipher",	id: "maroonCipher",	questions: ["What was on each screen?"] },
	{ name: "Mashematics",	id: "mashematics",	questions: ["What were the numbers in the equation?","What was the answer?"] },
	{ name: "Master Tapes",	id: "masterTape",	questions: ["Which song was played?"] },
	{ name: "Match Refereeing",	id: "matchRefereeing",	questions: ["Which planets were present in each stage?"] },
	{ name: "Math ’em",	id: "mathem",	questions: ["What were the color and design of each tile before the shuffle?"] },
	{ name: "The Matrix",	id: "matrix",	questions: ["Which word was part of the latest access code?","What was the glitched word?"] },
	{ name: "Maze",	id: "Maze",	questions: ["What was the starting position?"] },
	{ name: "Maze Identification",	id: "GSMazeIdentification",	questions: ["What was the seed?","What function did each button have?"] },
	{ name: "Maze Scrambler",	id: "MazeScrambler",	questions: ["What was the starting position?","What was the goal position?","Which positions were the maze markings?"] },
	{ name: "Mazematics",	id: "mazematics",	questions: ["What were the initial and goal values?"] },
	{ name: "Mazeseeker",	id: "GSMazeseeker",	questions: ["How many walls surrounded each cell?","What were the starting and goal positions?"] },
	{ name: "Maze³",	id: "maze3",	questions: ["What was the color of the starting face?"] },
	{ name: "Mega Man 2",	id: "megaMan2",	questions: ["What were the robot master and weapon shown?"] },
	{ name: "Melody Sequencer",	id: "melodySequencer",	questions: ["Which part was in which slot at the start?"] },
	{ name: "Memorable Buttons",	id: "memorableButtons",	questions: ["What were the symbols on the correct buttons?"] },
	{ name: "Memory",	id: "Memory",	questions: ["What was the display in each stage?","What were the positions and labels of the buttons you pressed?"] },
	{ name: "Memory Wires",	id: "memoryWires",	questions: ["What were the wire colours?","What were the displayed digits?"] },
	{ name: "Metamorse",	id: "metamorse",	questions: ["What was the extracted letter?"] },
	{ name: "Metapuzzle",	id: "metapuzzle",	questions: ["What was the final answer?"] },
	{ name: "Microcontroller",	id: "Microcontroller",	questions: ["The LEDs lit up in which order?"] },
	{ name: "Minesweeper",	id: "MinesweeperModule",	questions: ["What was the color of the starting cell?"] },
	{ name: "Mirror",	id: "mirror",	questions: ["What was the second word written by the original ghost?"] },
	{ name: "Mister Softee",	id: "misterSoftee",	questions: ["Where was the SpongeBob Bar?","Which treats were present?"] },
	{ name: "Modern Cipher",	id: "modernCipher",	questions: ["What were the decrypted words?"] },
	{ name: "Module Listening",	id: "moduleListening",	questions: ["What sounds played?","What sounds did each button play?"] },
	{ name: "Module Maze",	id: "ModuleMaze",	questions: ["What was the starting icon?"] },
	{ name: "Module Movements",	id: "moduleMovements",	questions: ["What module was shown for each stage?"] },
	{ name: "Monsplode Trading Cards",	id: "monsplodeCards",	questions: ["What were the names and print versions of the three cards in your hand and the card on offer before the final trade/keep?"] },
	{ name: "Monsplode, Fight!",	id: "monsplodeFight",	questions: ["Which creature was displayed?","Which moves were selectable?"] },
	{ name: "The Moon",	id: "moon",	questions: ["Which sets were initially lit/unlit?"] },
	{ name: "More Code",	id: "MoreCode",	questions: ["What was the flashing word?"] },
	{ name: "Morse Buttons",	id: "morseButtons",	questions: ["What were the characters and colors flashed by each button?"] },
	{ name: "Morse War",	id: "MorseWar",	questions: ["What were the LEDs?","What code was transmitted?"] },
	{ name: "Morse-A-Maze",	id: "MorseAMaze",	questions: ["What were the starting and ending location?","What was the morse code word played?"] },
	{ name: "Morsematics",	id: "MorseV2",	questions: ["What were the received letters?"] },
	{ name: "Mouse in the Maze",	id: "MouseInTheMaze",	questions: ["What color was the torus?","Which color sphere was the goal?"] },
	{ name: "Multicolored Switches",	id: "R4YMultiColoredSwitches",	questions: ["What were the colors of the LEDs in both cycles?"] },
	{ name: "Murder",	id: "murder",	questions: ["Which were the suspects and weapons?","Where was the body found?"] },
	{ name: "Mystery Module",	id: "mysterymodule",	questions: ["Which module was hidden?","Which module was the first requested to be solved?"] },
	{ name: "Mystic Square",	id: "MysticSquareModule",	questions: ["What was the position of the skull?"] },
	{ name: "N&Ms",	id: "NandMs",	questions: ["What was the label of the correct button?"] },
	{ name: "Name Codes",	id: "nameCodes",	questions: ["What were the left and right indices?"] },
	{ name: "Navigation Determination",	id: "NavigationDeterminationModule",	questions: ["What were the color and label of the maze?"] },
	{ name: "Navinums",	id: "navinums",	questions: ["Which directional buttons were pressed?","What was the initial middle digit?"] },
	{ name: "The Navy Button",	id: "NavyButtonModule",	questions: ["Which Greek letters appeared?","What were the coordinates and value of the given?"] },
	{ name: "The Necronomicon",	id: "necronomicon",	questions: ["What was the chapter number of each page?"] },
	{ name: "Negativity",	id: "Negativity",	questions: ["What was the submitted value (in base 10 and in balanced ternary)?"] },
	{ name: "Neutralization",	id: "neutralization",	questions: ["What was the acid’s color/volume?"] },
	{ name: "Not Colored Squares",	id: "NotColoredSquaresModule",	questions: ["What position did you initially press?"] },
	{ name: "Not Colored Switches",	id: "NotColoredSwitchesModule",	questions: ["What was the encrypted word?"] },
	{ name: "Not Connection Check",	id: "notConnectionCheck",	questions: ["What were the flashing symbols?","What were the button values?"] },
	{ name: "Not Coordinates",	id: "notCoordinates",	questions: ["What were the vertices of the square?"] },
	{ name: "Not Keypad",	id: "NotKeypad",	questions: ["Which colours flashed in the final sequence?","Which symbols were on the buttons that flashed in the final sequence?"] },
	{ name: "Not Maze",	id: "NotMaze",	questions: ["What was the starting distance?"] },
	{ name: "Not Morse Code",	id: "NotMorseCode",	questions: ["What was the sequence of words you submitted?"] },
	{ name: "Not Morsematics",	id: "notMorsematics",	questions: ["What was the transmitted word?"] },
	{ name: "Not Murder",	id: "notMurder",	questions: ["What room were the suspects in initially?","What weapons did the suspects possess initially?"] },
	{ name: "Not Number Pad",	id: "notNumberPad",	questions: ["Which numbers flashed at each stage?"] },
	{ name: "Not Perspective Pegs",	id: "NotPerspectivePegsModule",	questions: ["What were the positions, perspectives, and colors of each flash?"] },
	{ name: "Not Piano Keys",	id: "notPianoKeys",	questions: ["What were the displayed symbols?"] },
	{ name: "Not Simaze",	id: "NotSimaze",	questions: ["Which maze was used?","What were the starting and goal positions?"] },
	{ name: "Not Text Field",	id: "notTextField",	questions: ["Which letter appeared 9 times at the start?","Which letters were pressed in the first stage?"] },
	{ name: "Not The Bulb",	id: "notTheBulb",	questions: ["What was the transmitted word?"] },
	{ name: "Not the Button",	id: "NotButton",	questions: ["What color did the light glow?"] },
	{ name: "Not The Screw",	id: "notTheScrew",	questions: ["What was the initial position?"] },
	{ name: "Not Who’s on First",	id: "NotWhosOnFirst",	questions: ["What were the positions and labels of the correct buttons you pressed and the reference buttons?","What was the calculated number in the second stage?"] },
	{ name: "Not Word Search",	id: "notWordSearch",	questions: ["Which consonants were missing?","What was the first correctly pressed letter?"] },
	{ name: "Not X-Ray",	id: "NotXRayModule",	questions: ["What table were we in?","Which button went which direction?","What was the scanner color?"] },
	{ name: "Not X01",	id: "notX01",	questions: ["What were the sector values?"] },
	{ name: "Numbered Buttons",	id: "numberedButtonsModule",	questions: ["Which numbers were correctly pressed?"] },
	{ name: "Numbers",	id: "Numbers",	questions: ["What two-digit number was given?"] },
	{ name: "Numpath",	id: "numpath",	questions: ["What was the number and its color?"] },
	{ name: "Object Shows",	id: "objectShows",	questions: ["What contestants were shown?"] },
	{ name: "The Octadecayotton",	id: "TheOctadecayotton",	questions: ["What was the starting sphere?","What were the subrotations in each rotation?"] },
	{ name: "Odd One Out",	id: "OddOneOutModule",	questions: ["What were the correct button presses?"] },
	{ name: "Old AI",	id: "SCP079",	questions: ["Which condition did the displayed numbers follow?"] },
	{ name: "Old Fogey",	id: "oldFogey",	questions: ["What was the initial color of the status light?"] },
	{ name: "Only Connect",	id: "OnlyConnectModule",	questions: ["What were the positions of the Egyptian hieroglyphs?"] },
	{ name: "Orange Arrows",	id: "orangeArrowsModule",	questions: ["What were the first three arrows on the display in each stage?"] },
	{ name: "Orange Cipher",	id: "orangeCipher",	questions: ["What was on each screen?"] },
	{ name: "Order Picking",	id: "OrderPickingModule",	questions: ["What were the order ID, product ID and pallet for each order?"] },
	{ name: "Ordered Keys",	id: "orderedKeys",	questions: ["What were the labels, their colors, and the colors of the keys in each stage?"] },
	{ name: "Orientation Cube",	id: "OrientationCube",	questions: ["What was the observer’s initial position?"] },
	{ name: "Orientation Hypercube",	id: "OrientationHypercube",	questions: ["What was the observer’s initial position?","What was the initial colour of each face?"] },
	{ name: "Palindromes",	id: "palindromes",	questions: ["What number was X, Y, Z, and the screen display?"] },
	{ name: "Parity",	id: "parity",	questions: ["What was shown on the display?"] },
	{ name: "Partial Derivatives",	id: "partialDerivatives",	questions: ["What were the terms of the function?","What were the LED colors in each stage?"] },
	{ name: "Passport Control",	id: "passportControl",	questions: ["What were the passport expiration years of each passenger?"] },
	{ name: "Password Destroyer",	id: "pwDestroyer",	questions: ["What were the starting value, increase factor, TFA₁, TFA₂ and 2FAST™ values, and the percentage of solved modules used in the final calculation?"] },
	{ name: "Pattern Cube",	id: "PatternCubeModule",	questions: ["Which symbol was highlighted?"] },
	{ name: "Periodic Words",	id: "periodicWordsRB",	questions: ["What was the displayed word in each stage?"] },
	{ name: "Perspective Pegs",	id: "spwizPerspectivePegs",	questions: ["What was the initial color sequence?"] },
	{ name: "Phosphorescence",	id: "Phosphorescence",	questions: ["What were the button presses and the offset?"] },
	{ name: "Pictionary",	id: "pictionaryModule",	questions: ["What was the code?"] },
	{ name: "Pie",	id: "pieModule",	questions: ["What were the digits shown?"] },
	{ name: "Pie Flash",	id: "pieFlash",	questions: ["What numbers were displayed?"] },
	{ name: "Pigpen Cycle",	id: "pigpenCycle",	questions: ["What were the message and response?"] },
	{ name: "The Pink Button",	id: "PinkButtonModule",	questions: ["What were the displayed words and their colors?"] },
	{ name: "Pixel Cipher",	id: "pixelcipher",	questions: ["What was the keyword?"] },
	{ name: "Placeholder Talk",	id: "placeholderTalk",	questions: ["What was the entire first phrase?","What was the calculated value for second phrase?"] },
	{ name: "Placement Roulette",	id: "PlacementRouletteModule",	questions: ["What were the character, drift type, track, track type, vehicle, and vehicle type listed?"] },
	{ name: "Planets",	id: "planets",	questions: ["What was the planet shown?","What was the correct color for each strip?"] },
	{ name: "Playfair Cycle",	id: "playfairCycle",	questions: ["What were the message and response?"] },
	{ name: "Poetry",	id: "poetry",	questions: ["What were the answers you pressed in each stage?"] },
	{ name: "Polyhedral Maze",	id: "PolyhedralMazeModule",	questions: ["What was the starting position?"] },
	{ name: "Prime Encryption",	id: "primeEncryption",	questions: ["What was the displayed number?"] },
	{ name: "Probing",	id: "Probing",	questions: ["What were the missing frequencies in each wire?"] },
	{ name: "Procedural Maze",	id: "ProceduralMaze",	questions: ["What was the initial seed?"] },
	{ name: "Purple Arrows",	id: "purpleArrowsModule",	questions: ["What was the target word?"] },
	{ name: "The Purple Button",	id: "PurpleButtonModule",	questions: ["What were the numbers in the cyclic sequence?"] },
	{ name: "Puzzle Identification",	id: "GSPuzzleIdentification",	questions: ["What game did each puzzle come from?","What was the name and number of each puzzle?"] },
	{ name: "Quaver",	id: "Quaver",	questions: ["What was each sequence’s answer?"] },
	{ name: "Question Mark",	id: "Questionmark",	questions: ["What were the flashing symbols?"] },
	{ name: "Quick Arithmetic",	id: "QuickArithmetic",	questions: ["What were the digits and colors in both sequences?"] },
	{ name: "Quintuples",	id: "quintuples",	questions: ["What were the numbers and colors in every slot?","How many numbers were there of each color?"] },
	{ name: "Quiz Buzz",	id: "quizBuzz",	questions: ["What was the number initially on the display?"] },
	{ name: "Qwirkle",	id: "qwirkle",	questions: ["Which tiles did you place?"] },
	{ name: "Raiding Temples",	id: "raidingTemples",	questions: ["How many jewels were initially in the common pool?"] },
	{ name: "Railway Cargo Loading",	id: "RailwayCargoLoading",	questions: ["What were the coupled cars?","Which freight table rules applied?"] },
	{ name: "Rainbow Arrows",	id: "ksmRainbowArrows",	questions: ["What was the displayed number?"] },
	{ name: "Recolored Switches",	id: "R4YRecoloredSwitches",	questions: ["What were the LED colors?"] },
	{ name: "Recursive Password",	id: "RecursivePassword",	questions: ["What were the incomplete words?","What was the password?"] },
	{ name: "Red Arrows",	id: "redArrowsModule",	questions: ["What was the starting number?"] },
	{ name: "Red Cipher",	id: "redCipher",	questions: ["What was on each screen?"] },
	{ name: "Red Herring",	id: "RedHerring",	questions: ["What was the first color flashed?"] },
	{ name: "Reformed Role Reversal",	id: "ReformedRoleReversal",	questions: ["What did the solving condition state?","What were the final wires?"] },
	{ name: "Regular Crazy Talk",	id: "RegularCrazyTalkModule",	questions: ["What was the displayed digit that corresponded to the solution phrase?","What was the embellishment of the solution phrase?"] },
	{ name: "Retirement",	id: "retirement",	questions: ["Which houses were on offer, but not chosen by Bob?"] },
	{ name: "Reverse Morse",	id: "reverseMorse",	questions: ["What were the characters in each message?"] },
	{ name: "Reverse Polish Notation",	id: "revPolNot",	questions: ["What characters were used in each round?"] },
	{ name: "RGB Maze",	id: "rgbMaze",	questions: ["Where were the exit and keys of the maze?","What was the maze number for each maze?"] },
	{ name: "RGB Sequences",	id: "RGBSequences",	questions: ["What were the colors of each button?"] },
	{ name: "Rhythms",	id: "MusicRhythms",	questions: ["What was the color?"] },
	{ name: "Robo-Scanner",	id: "roboScannerModule",	questions: ["Where was the empty cell?"] },
	{ name: "Robot Programming",	id: "robotProgramming",	questions: ["What was the name of each robot?"] },
	{ name: "Roger",	id: "roger",	questions: ["What four-digit number was given?"] },
	{ name: "Role Reversal",	id: "roleReversal",	questions: ["What was the condition digit that solved the module?","What colors were the internal wires?"] },
	{ name: "The Rule",	id: "theRule",	questions: ["What was the rule number?"] },
	{ name: "Rule of Three",	id: "RuleOfThreeModule",	questions: ["What were the positions of each sphere on each axis in each cycle?","What were the coordinates of the vertices?"] },
	{ name: "S.E.T. Theory",	id: "SetTheory",	questions: ["What equations were displayed in each stage?"] },
	{ name: "Safety Square",	id: "safetySquare",	questions: ["What were the displayed digits?","What was the special rule?"] },
	{ name: "The Samsung",	id: "theSamsung",	questions: ["Where was each app?"] },
	{ name: "Sbemail Songs",	id: "sbemailsongs",	questions: ["What were the displayed songs in each stage?"] },
	{ name: "Scavenger Hunt",	id: "scavengerHunt",	questions: ["Which tile was correctly submitted in the first stage?","Where were the red, green, and blue tiles in the first stage?"] },
	{ name: "Schlag den Bomb",	id: "qSchlagDenBomb",	questions: ["What were the contestant’s name and both scores?"] },
	{ name: "Scramboozled Eggain",	id: "ScramboozledEggainModule",	questions: ["What were the encrypted words?"] },
	{ name: "Scripting",	id: "KritScripts",	questions: ["What was the data type of the variable?"] },
	{ name: "Scrutiny Squares",	id: "scrutinySquares",	questions: ["What was the modified property of the first displayed square?"] },
	{ name: "Sea Shells",	id: "SeaShells",	questions: ["What were the phrases?"] },
	{ name: "Semamorse",	id: "semamorse",	questions: ["What were Morse and semaphore letters and color used for the starting value?"] },
	{ name: "The Sequencyclopedia",	id: "TheSequencyclopedia",	questions: ["What sequence was used?"] },
	{ name: "Shape Shift",	id: "shapeshift",	questions: ["What was the initial shape?"] },
	{ name: "Shapes And Bombs",	id: "ShapesBombs",	questions: ["What was the initial letter?"] },
	{ name: "Shifted Maze",	id: "shiftedMaze",	questions: ["What were the colors of the markers?"] },
	{ name: "Shifting Maze",	id: "MazeShifting",	questions: ["What was the seed?"] },
	{ name: "Shogi Identification",	id: "shogiIdentification",	questions: ["What was the displayed piece?"] },
	{ name: "Sign Language",	id: "signLanguage",	questions: ["What was the deciphered word?"] },
	{ name: "Silly Slots",	id: "SillySlots",	questions: ["What were the slots in each stage?"] },
	{ name: "Silo Authorization",	id: "siloAuthorization",	questions: ["What were the message type, encrypted message, and received authorization code?"] },
	{ name: "Simon Said",	id: "simonSaidModule",	questions: ["What was the final sequence of presses?"] },
	{ name: "Simon Samples",	id: "simonSamples",	questions: ["What were the call samples in each stage?"] },
	{ name: "Simon Says",	id: "Simon",	questions: ["Which colors flashed in the final sequence?"] },
	{ name: "Simon Scrambles",	id: "simonScrambles",	questions: ["What was the flashing color sequence?"] },
	{ name: "Simon Screams",	id: "SimonScreamsModule",	questions: ["What flashing color was used in each stage?","Which rules applied in which stage(s)?"] },
	{ name: "Simon Selects",	id: "simonSelectsModule",	questions: ["Which colors flashed in each stage?"] },
	{ name: "Simon Sends",	id: "SimonSendsModule",	questions: ["What were the red, green, and blue received letters?"] },
	{ name: "Simon Serves",	id: "simonServes",	questions: ["Who flashed in each course?","Which items were not served in each course?"] },
	{ name: "Simon Shapes",	id: "SimonShapesModule",	questions: ["What was the shape submitted at the end?"] },
	{ name: "Simon Shouts",	id: "SimonShoutsModule",	questions: ["What letters flashed on each button?"] },
	{ name: "Simon Shrieks",	id: "SimonShrieksModule",	questions: ["How many spaces clockwise from the arrow was each flash in the final sequence?"] },
	{ name: "Simon Signals",	id: "SimonSignalsModule",	questions: ["What were the colors, shapes and number of directions of each arrow?"] },
	{ name: "Simon Simons",	id: "simonSimons",	questions: ["Which buttons flashed in each stage?"] },
	{ name: "Simon Sings",	id: "SimonSingsModule",	questions: ["Which keys’ colors flashed in each stage?"] },
	{ name: "Simon Smiles",	id: "SimonSmiles",	questions: ["What sounds did each button press play?"] },
	{ name: "Simon Smothers",	id: "simonSmothers",	questions: ["Which colors and directions flashed in each stage?"] },
	{ name: "Simon Sounds",	id: "simonSounds",	questions: ["Which sample buttons sounded in each stage?"] },
	{ name: "Simon Speaks",	id: "SimonSpeaksModule",	questions: ["What were the relevant attributes of the flashing bubbles?"] },
	{ name: "Simon Stacks",	id: "simonstacks",	questions: ["Which colors flashed in each stage?"] },
	{ name: "Simon Stages",	id: "simonStages",	questions: ["Which colors flashed in each stage?","What color was the indicator in each stage?"] },
	{ name: "Simon States",	id: "SimonV2",	questions: ["Which color(s) flashed in the first three stages?"] },
	{ name: "Simon Stops",	id: "simonStops",	questions: ["Which colors flashed in the output sequence?"] },
	{ name: "Simon Stores",	id: "simonStores",	questions: ["Which colors flashed in the final sequence?","What were the numerical answers in each stage?"] },
	{ name: "Simon Subdivides",	id: "simonSubdivides",	questions: ["What colors were the cells that subdivided?"] },
	{ name: "Simon Supports",	id: "simonSupports",	questions: ["What were the 3 topics?"] },
	{ name: "Simon’s Star",	id: "simonsStar",	questions: ["Which colors flashed in each stage?"] },
	{ name: "Simultaneous Simons",	id: "simultaneousSimons",	questions: ["Which colors flashed on each of the Simons?"] },
	{ name: "Skewed Slots",	id: "SkewedSlotsModule",	questions: ["What were the original numbers?"] },
	{ name: "Skyrim",	id: "skyrim",	questions: ["Which races, weapons, enemies, cities, and dragon shouts were selectable, but not the solution?"] },
	{ name: "Slow Math",	id: "SlowMathModule",	questions: ["What was the last triplet of letters?"] },
	{ name: "Small Circle",	id: "smallCircle",	questions: ["How much did the sequence shift by?","Which wedge made the different noise in the beginning?","Which colors were in the solution?"] },
	{ name: "Snooker",	id: "snooker",	questions: ["How many reds were there initially?"] },
	{ name: "Snowflakes",	id: "snowflakes",	questions: ["What were the displayed snowflakes?"] },
	{ name: "Sonic & Knuckles",	id: "sonicKnuckles",	questions: ["Which monitor and badnik were shown?","What was the sound not featured in the chosen zone?"] },
	{ name: "Sonic The Hedgehog",	id: "sonic",	questions: ["Which sound was played by each screen?","What were the pictures?"] },
	{ name: "Sorting",	id: "sorting",	questions: ["Which positions were involved in the final swap?"] },
	{ name: "Souvenir",	id: "SouvenirModule",	questions: ["What was the first module the other Souvenir asked a question about?"] },
	{ name: "Space Traders",	id: "space_traders",	questions: ["What was the maximum tax amount per vessel?"] },
	{ name: "Spelling Bee",	id: "spellingBee",	questions: ["What word was asked to be spelled?"] },
	{ name: "The Sphere",	id: "sphere",	questions: ["What were the flashed colors?"] },
	{ name: "Splitting The Loot",	id: "SplittingTheLootModule",	questions: ["Which bag was initially colored?"] },
	{ name: "Spongebob Birthday Identification",	id: "spongebobBirthdayIdentification",	questions: ["What were the submitted names?"] },
	{ name: "Stability",	id: "stabilityModule",	questions: ["What were the lit LEDs’ colors?","What was the identification number?"] },
	{ name: "Stable Time Signatures",	id: "StableTimeSignatures",	questions: ["What time signatures played?"] },
	{ name: "Stacked Sequences",	id: "stackedSequences",	questions: ["What were the lengths of the sequences?"] },
	{ name: "Stars",	id: "stars",	questions: ["What was the digit in the center?"] },
	{ name: "State of Aggregation",	id: "stateOfAggregation",	questions: ["What element was shown?"] },
	{ name: "Stellar",	id: "stellar",	questions: ["What were the letters?"] },
	{ name: "Stupid Slots",	id: "stupidSlots",	questions: ["What were the values of each arrow?"] },
	{ name: "Subscribe to Pewdiepie",	id: "subscribeToPewdiepie",	questions: ["How many subscribers do Pewdiepie and T-Series have?"] },
	{ name: "Subway",	id: "subway",	questions: ["Which bread did the customer ask for?","Which item was not asked for?"] },
	{ name: "Sugar Skulls",	id: "sugarSkulls",	questions: ["What skulls were shown?"] },
	{ name: "Superparsing",	id: "superparsing",	questions: ["What was the displayed word?"] },
	{ name: "The Switch",	id: "BigSwitch",	questions: ["What color were the LEDs?"] },
	{ name: "Switches",	id: "switchModule",	questions: ["What was the initial position of the switches?"] },
	{ name: "Switching Maze",	id: "MazeSwitching",	questions: ["What was the seed?","What was the starting maze color?"] },
	{ name: "Symbol Cycle",	id: "SymbolCycleModule",	questions: ["How many symbols were cycling on each screen?"] },
	{ name: "Symbolic Coordinates",	id: "symbolicCoordinates",	questions: ["Which symbols were present on each stage?"] },
	{ name: "Symbolic Tasha",	id: "symbolicTasha",	questions: ["What symbols were on the buttons?","Which buttons flashed?"] },
	{ name: "SYNC-125 [3]",	id: "sync125_3",	questions: ["What was displayed on the screen in each stage?"] },
	{ name: "Synonyms",	id: "synonyms",	questions: ["Which number was displayed?"] },
	{ name: "Sysadmin",	id: "sysadmin",	questions: ["What error code did you fix?"] },
	{ name: "Tap Code",	id: "tapCode",	questions: ["What was the received word?"] },
	{ name: "Tasha Squeals",	id: "tashaSqueals",	questions: ["What were the flashed colors?"] },
	{ name: "Tasque Managing",	id: "tasqueManaging",	questions: ["What was the starting position?"] },
	{ name: "The Tea Set",	id: "GSTeaSet",	questions: ["In what order were the ingredients displayed?"] },
	{ name: "Technical Keypad",	id: "TechnicalKeypad",	questions: ["What were the displayed digits?"] },
	{ name: "Ten-Button Color Code",	id: "TenButtonColorCode",	questions: ["What were the buttons’ initial colors in each stage?"] },
	{ name: "Tenpins",	id: "tenpins",	questions: ["What were the splits?"] },
	{ name: "Tetriamonds",	id: "tetriamonds",	questions: ["What was the pulsing colour sequence?"] },
	{ name: "Text Field",	id: "TextField",	questions: ["What was the displayed letter?"] },
	{ name: "Thinking Wires",	id: "thinkingWiresModule",	questions: ["Which was the first wire needing to be cut?","What color was the second valid wire to cut?","What was the display number?"] },
	{ name: "Third Base",	id: "ThirdBase",	questions: ["What were the display words?"] },
	{ name: "Tic Tac Toe",	id: "TicTacToeModule",	questions: ["What was the initial state of the field?"] },
	{ name: "Time Signatures",	id: "timeSignatures",	questions: ["What time signatures played?"] },
	{ name: "Timezone",	id: "timezone",	questions: ["What were the departure and destination city?"] },
	{ name: "Tip Toe",	id: "TipToe",	questions: ["Which squares were safe in rows 9 and 10?"] },
	{ name: "Topsy Turvy",	id: "topsyTurvy",	questions: ["What was the word initially shown?"] },
	{ name: "Touch Transmission",	id: "touchTransmission",	questions: ["What was the transmitted word?","In what order was the Braille read?"] },
	{ name: "Trajectory",	id: "Trajectory",	questions: ["What functions did each button perform?"] },
	{ name: "Transmitted Morse",	id: "transmittedMorseModule",	questions: ["What were the received messages?"] },
	{ name: "Triamonds",	id: "triamonds",	questions: ["What was the pulsing colour sequence?"] },
	{ name: "Triple Term",	id: "tripleTermModule",	questions: ["What were the passwords?"] },
	{ name: "Turtle Robot",	id: "turtleRobot",	questions: ["What were the commented out code lines?"] },
	{ name: "Two Bits",	id: "TwoBits",	questions: ["What were the correct three query responses?"] },
	{ name: "Ultimate Cipher",	id: "ultimateCipher",	questions: ["What was on each screen?"] },
	{ name: "Ultimate Cycle",	id: "ultimateCycle",	questions: ["What were the message and response?"] },
	{ name: "The Ultracube",	id: "TheUltracubeModule",	questions: ["What were the rotations?"] },
	{ name: "UltraStores",	id: "UltraStores",	questions: ["What were the rotations?"] },
	{ name: "Uncolored Squares",	id: "UncoloredSquaresModule",	questions: ["What were the colors used in the first stage?"] },
	{ name: "Uncolored Switches",	id: "R4YUncoloredSwitches",	questions: ["What was the initial switch state?","What were the LED colors?"] },
	{ name: "Unfair Cipher",	id: "unfairCipher",	questions: ["What were the received instructions?"] },
	{ name: "Unfair’s Revenge",	id: "unfairsRevenge",	questions: ["What were the decrypted instructions?"] },
	{ name: "Unicode",	id: "UnicodeModule",	questions: ["What were the submitted codes?"] },
	{ name: "UNO!",	id: "UNO",	questions: ["What was the starting card?"] },
	{ name: "Unown Cipher",	id: "UnownCipher",	questions: ["What were the submitted letters?"] },
	{ name: "USA Cycle",	id: "USACycle",	questions: ["Which states were displayed?"] },
	{ name: "USA Maze",	id: "USA",	questions: ["Which state did you depart from?"] },
	{ name: "V",	id: "V",	questions: ["Which words were shown?"] },
	{ name: "Valves",	id: "valves",	questions: ["What was the initial state?"] },
	{ name: "Varicolored Squares",	id: "VaricoloredSquaresModule",	questions: ["What was the initially pressed color?"] },
	{ name: "Varicolour Flash",	id: "varicolourFlash",	questions: ["What were the words and colours of each goal?"] },
	{ name: "Vcrcs",	id: "VCRCS",	questions: ["What was the displayed word?"] },
	{ name: "Vectors",	id: "vectorsModule",	questions: ["What were the colors of the vectors?"] },
	{ name: "Vexillology",	id: "vexillology",	questions: ["What were the flagpole colors?"] },
	{ name: "Violet Cipher",	id: "violetCipher",	questions: ["What was on each screen?"] },
	{ name: "Visual Impairment",	id: "visual_impairment",	questions: ["What were the desired colors?"] },
	{ name: "Warning Signs",	id: "warningSigns",	questions: ["What was the displayed sign?"] },
	{ name: "WASD",	id: "wasdModule",	questions: ["What was the displayed location?"] },
	{ name: "Wavetapping",	id: "Wavetapping",	questions: ["What was the correct pattern in each stage?","What was the color in the first two stages?"] },
	{ name: "The Weakest Link",	id: "TheWeakestLink",	questions: ["Who was eliminated?","Who joined you in the Money Phase?","What were the other contestants’ skills and correct answer ratios?"] },
	{ name: "What’s on Second",	id: "WhatsOnSecond",	questions: ["What were the display text and color in each stage?"] },
	{ name: "White Cipher",	id: "whiteCipher",	questions: ["What was on each screen?"] },
	{ name: "WhoOF",	id: "whoOF",	questions: ["What was on the display in each stage?"] },
	{ name: "Who’s on First",	id: "WhosOnFirst",	questions: ["What were the display words?"] },
	{ name: "Who’s On Morse",	id: "whosOnMorseModule",	questions: ["What word was transmitted in each stage?"] },
	{ name: "The Wire",	id: "wire",	questions: ["What were the colors of the dials?","What was the displayed number?"] },
	{ name: "Wire Ordering",	id: "kataWireOrdering",	questions: ["What were the colors and numbers on the displays?","What were the colors of the wires?"] },
	{ name: "Wire Sequence",	id: "WireSequence",	questions: ["How many wires of each color were there?"] },
	{ name: "Wolf, Goat, and Cabbage",	id: "wolfGoatCabbageModule",	questions: ["Which creatures were present?","What size was the boat?"] },
	{ name: "Working Title",	id: "workingTitle",	questions: ["What was the label shown?"] },
	{ name: "The Xenocryst",	id: "GSXenocryst",	questions: ["What was the color of each flash?"] },
	{ name: "XmORse Code",	id: "xmorse",	questions: ["What were the displayed letters?","What word did you decrypt?"] },
	{ name: "xobekuJ ehT",	id: "xobekuj",	questions: ["What song was played?"] },
	{ name: "Yahtzee",	id: "YahtzeeModule",	questions: ["What was the first roll?"] },
	{ name: "Yellow Arrows",	id: "yellowArrowsModule",	questions: ["What was the starting row letter?"] },
	{ name: "The Yellow Button",	id: "YellowButtonModule",	questions: ["What were the colors?"] },
	{ name: "Yellow Cipher",	id: "yellowCipher",	questions: ["What was on each screen?"] },
	{ name: "Zero, Zero",	id: "zeroZero",	questions: ["What were the colors and number of points on each star?","Where were the colored squares?"] },
	{ name: "Zoni",	id: "lgndZoni",	questions: ["What were the deciphered words?"] },
	{ name: "Ángel Hernández",	id: "AngelHernandezModule",	questions: ["What letter was shown by the raised buttons in each stage?"] },
	{ name: "Épelle-moi Ça",	id: "epelleMoiCa",	questions: ["What word was asked to be spelled?"] },
	{ name: "ƎNA Cipher",	id: "enaCipher",	questions: ["What were the keyword, the transposition key and the encrypted word?"] },
	{ name: "❖",	id: "nonverbalSimon",	questions: ["What were the flashes?"] },
];