let SouvenirModuleData = [
	{ original: ".--/---/..-.",	name: "--..-_--_..-_--..-_.-.._...-",	id: "morseWoF",	questions: ["ディスプレーの単語は？"] },
	{ original: "...?",	name: "...？",	id: "punctuationMarks",	questions: ["表示された数字は？"] },
	{ original: "↻↺",	name: "↻↺",	id: "clockCounter",	questions: ["表示された矢印は？"] },
	{ original: "❖",	name: "❖",	id: "nonverbalSimon",	questions: ["点滅は何だった？"] },
	{ original: "0",	name: "0",	id: "0",	questions: ["スタートの数字は？"] },
	{ original: "The 1, 2, 3 Game",	name: "123ゲーム",	id: "TheOneTwoThreeGame",	questions: ["対戦相手のアバターと名前は？"] },
	{ original: "100 Levels of Defusal",	name: "解除レベル100",	id: "100LevelsOfDefusal",	questions: ["ディスプレーの文字は？"] },
	{ original: "1000 Words",	name: "1000単語",	id: "OneThousandWords",	questions: ["表示された単語は？"] },
	{ original: "1D Chess",	name: "1Dチェス",	id: "1DChess",	questions: ["あなたとRustmateの動きはどうだった？"] },
	{ original: "21",	name: "21",	id: "TwennyWan",	questions: ["表示された数字は？"] },
	{ original: "3 LEDs",	name: "3つのLED",	id: "threeLEDsModule",	questions: ["LEDの初期配置は？"] },
	{ original: "3D Maze",	name: "3D迷路",	id: "spwiz3DMaze",	questions: ["迷路の文字は？", "ゴールの方向はどこ？"] },
	{ original: "3D Tap Code",	name: "3Dタップ・コード",	id: "3DTapCodeModule",	questions: ["受信した単語は？"] },
	{ original: "3D Tunnels",	name: "3Dトンネル",	id: "3dTunnels",	questions: ["ゴールの目印は？"] },
	{ original: "3N+1",	name: "3N+1",	id: "threeNPlusOne",	questions: ["最初に表示されていた数字は？"] },
	{ original: "4D Tunnels",	name: "4Dトンネル",	id: "4dTunnels",	questions: ["ゴールの目印は？"] },
	{ original: "64",	name: "64",	id: "64",	questions: ["表示された数字は？"] },
	{ original: "7",	name: "7",	id: "7",	questions: ["初期のLEDの状態は？", "初期値の各チャネルは？"] },
	{ original: "9-Ball",	name: "9ボール",	id: "GSNineBall",	questions: ["各ボールの数字は？"] },
	{ original: "A Letter",	name: "英字",	id: "LetterModule",	questions: ["最初に表示されていた英字は？"] },
	{ original: "A Message",	name: "Aメッセージ",	id: "AMessage",	questions: ["受信したメッセージは？"] },
	{ original: "A Square",	name: "正方型",	id: "ASquareModule",	questions: ["一致した色は？", "送信した色は？"] },
	{ original: "Abyss",	name: "アビス",	id: "GSAbyss",	questions: ["表示されていた文字は？"] },
	{ original: "Accumulation",	name: "蓄積",	id: "accumulation",	questions: ["各ステージの背景の色は？", "境界線の色は？"] },
	{ original: "Adventure Game",	name: "アドベンチャーゲーム",	id: "spwizAdventureGame",	questions: ["存在したアイテムは？"] },
	{ original: "Affine Cycle",	name: "アフィンサイクル",	id: "affineCycle",	questions: ["ダイヤルが指していた方向は？", "ダイヤルに書かれていた英字は？"] },
	{ original: "Alcoholic Rampage",	name: "アルコール中毒",	id: "alcoholicRampageModule",	questions: ["表示された傭兵は？"] },
	{ original: "Alfa-Bravo",	name: "アルファブラボー",	id: "alfa_bravo",	questions: ["最後にどの文字を押した？", "押した文字の左右にあった文字は？", "小さなディスプレーの最後の数字は？"] },
	{ original: "Algebra",	name: "方程式",	id: "algebra",	questions: ["1~2番目の方程式は？"] },
	{ original: "Algorithmia",	name: "アルゴリズム",	id: "algorithmia",	questions: ["スタートとゴールの位置は？", "色付き電球の色は？", "シード内にあった数字は？"] },
	{ original: "Alpha-Bits",	name: "アルファビッツ",	id: "alphaBits",	questions: ["各画面に表示されている文字は？"] },
	{ original: "Alphabet Numbers",	name: "アルファベット番号",	id: "alphabetNumbers",	questions: ["各ステージでボタンに記されていた番号は？"] },
	{ original: "Alphabet Tiles",	name: "アルファベットタイル",	id: "AlphabetTiles",	questions: ["各サイクルで何の文字が表示されていた？", "欠けていた英字は？"] },
	{ original: "Alphabetical Ruling",	name: "アルファベットルール",	id: "alphabeticalRuling",	questions: ["各ステージで表示された文字と数字は？"] },
	{ original: "Amusement Parks",	name: "遊園地",	id: "amusementParks",	questions: ["利用可能なアトラクションは？"] },
	{ original: "Ángel Hernández",	name: "アンヘル・エルナンデス",	id: "AngelHernandezModule",	questions: ["各ステージで点字で表示されていた英字は？"] },
	{ original: "The Arena",	name: "アリーナ",	id: "TheArena",	questions: ["攻撃フェーズで最大のダメージを与えられる武器は？", "防御フェーズで存在していた敵は？", "奪取フェーズで存在していた数字は？"] },
	{ original: "Arithmelogic",	name: "計算論理",	id: "arithmelogic",	questions: ["送信ボタンに記された記号は？"] },
	{ original: "Arithmetic Cipher",	name: "算術暗号",	id: "ArithmeticCipherModule",	questions: ["各ディスプレーの文字は？"] },
	{ original: "ASCII Maze",	name: "アスキー迷路",	id: "asciiMaze",	questions: ["表示された文字は？"] },
	{ original: "Audio Morse",	name: "音声モールス",	id: "lgndAudioMorse",	questions: ["モールス信号は？"] },
	{ original: "The Azure Button",	name: "空色ボタン",	id: "AzureButtonModule",	questions: ["Tとその他の表示されたカードは？", "Mは？", "矢印のシーケンスは？"] },
	{ original: "Bakery",	name: "クッキー屋",	id: "bakery",	questions: ["存在したメニュー商品はどれ？"] },
	{ original: "Bamboozled Again",	name: "再錯綜",	id: "bamboozledAgain",	questions: ["それぞれの正しいボタンの色とテキストは？", "表示された各メッセージを解読した時のテキストと色は？"] },
	{ original: "Bamboozling Button",	name: "錯綜ボタン",	id: "bamboozlingButton",	questions: ["各ステージのボタンの色は？", "各ステージのボタンのラベルは？", "各ステージのディスプレーとその色は？"] },
	{ original: "Bar Charts",	name: "棒グラフ",	id: "GSBarCharts",	questions: ["バーの長さ、色、ラベルは？", "カテゴリは？", "単位は？"] },
	{ original: "Barcode Cipher",	name: "バーコード暗号",	id: "BarcodeCipherModule",	questions: ["画面上の数字は？", "各バーコードが示すエッジワークは？", "各バーコードの回答は？"] },
	{ original: "Bartending",	name: "バーテンディング",	id: "BartendingModule",	questions: ["どの材料がどの位置にあった？"] },
	{ original: "Bean Sprouts",	name: "もやし",	id: "beanSprouts",	questions: ["食べたもやしの色は？", "食べた豆の位置は？"] },
	{ original: "Beans",	name: "豆",	id: "beans",	questions: ["食べた豆の色は？", "どの豆が揺れていた？"] },
	{ original: "Big Bean",	name: "大きい豆",	id: "bigBean",	questions: ["豆の色と揺れの状態は？"] },
	{ original: "Big Circle",	name: "ビッグサークル",	id: "BigCircle",	questions: ["円の回転方向は？"] },
	{ original: "Binary",	name: "二進法LED",	id: "Binary",	questions: ["表示された単語は？"] },
	{ original: "Binary Shift",	name: "二進数シフト",	id: "binary_shift",	questions: ["初期値は？", "各ステージで選択した数字は？"] },
	{ original: "Bitmaps",	name: "ビットマップ",	id: "BitmapsModule",	questions: ["各区域の黒/白ピクセルはいくつ？"] },
	{ original: "Black Cipher",	name: "黒色暗号",	id: "blackCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Blind Maze",	name: "ブラインド迷路",	id: "BlindMaze",	questions: ["ボタンの色は？"] },
	{ original: "Blindfolded Yahtzee",	name: "目隠しヤッツィー",	id: "GSBlindfoldedYahtzee",	questions: ["モジュールが主張したロールは？"] },
	{ original: "Blinking Notes",	name: "点滅音符",	id: "blinkingNotes",	questions: ["再生された楽曲は？"] },
	{ original: "Blinkstop",	name: "瞬きの停止",	id: "blinkstopModule",	questions: ["LEDは何回点滅した？", "最も少なく点滅した色は？"] },
	{ original: "Blockbusters",	name: "ブロックバスター",	id: "blockbusters",	questions: ["開始時、左端の列にあった英字は？"] },
	{ original: "Blue Arrows",	name: "青色矢印",	id: "blueArrowsModule",	questions: ["ディスプレーに表示された文字は？"] },
	{ original: "The Blue Button",	name: "青色ボタン",	id: "BlueButtonModule",	questions: ["D、E、F、G、H、M、N、P、Q、Xの中身は？"] },
	{ original: "Blue Cipher",	name: "青色暗号",	id: "blueCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Blue Huffman Cipher",	name: "青色ハフマン暗号",	id: "BlueHuffmanCipherModule",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Bob Barks",	name: "ボブの咆哮",	id: "ksmBobBarks",	questions: ["インジケーターのラベルは？", "配置の中で点滅しているボタンはどれ？"] },
	{ original: "Boggle",	name: "ボグル",	id: "boggle",	questions: ["初めに表示された文字は？"] },
	{ original: "Bomb Diffusal",	name: "爆弾拡散",	id: "bombDiffusal",	questions: ["ライセンス番号は？"] },
	{ original: "Bone Apple Tea",	name: "ボーンアップルティー",	id: "boneAppleTea",	questions: ["フレーズは？"] },
	{ original: "Boob Tube",	name: "ブーブチューブ",	id: "boobTubeModule",	questions: ["単語は？"] },
	{ original: "Book of Mario",	name: "ブック・オブ・マリオ",	id: "BookOfMarioModule",	questions: ["各ステージで発言していたのは？", "各キャラクターの引用文は？"] },
	{ original: "Boolean Wires",	name: "論理ワイヤ",	id: "booleanWires",	questions: ["Which letters were displayed in each stage?"] },
	{ original: "Boomtar the Great",	name: "偉大なるブームター",	id: "boomtarTheGreat",	questions: ["一番目のルールと二番目のルールは？"] },
	{ original: "Bordered Keys",	name: "境界音板",	id: "borderedKeys",	questions: ["各音板を押した時点における縁の色、ディスプレーの数字、音板の色、ラベル、ラベルの色は？"] },
	{ original: "Bottom Gear",	name: "ボトムギア",	id: "GSBottomGear",	questions: ["最初に表示されたツイートは？"] },
	{ original: "Boxing",	name: "ボクシング",	id: "boxing",	questions: ["どの出場者と補欠者(姓名)が表示された？", "誰がどのくらいのパンチ力を持っている？"] },
	{ original: "Braille",	name: "点字",	id: "BrailleModule",	questions: ["存在した点字のパターンは？"] },
	{ original: "Breakfast Egg",	name: "目玉焼き",	id: "breakfastEgg",	questions: ["卵に現れた色はどれ？"] },
	{ original: "Broken Guitar Chords",	name: "壊れたギター・コード",	id: "BrokenGuitarChordsModule",	questions: ["表示されたコードは？", "どの弦が壊れていた？"] },
	{ original: "Brown Cipher",	name: "茶色暗号",	id: "brownCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "The Bulb",	name: "ザ・電球",	id: "TheBulbModule",	questions: ["初期状態の電球は点灯していた？"] },
	{ original: "Burger Alarm",	name: "ハンバーガー警報",	id: "burgerAlarm",	questions: ["表示された数字は？", "注文番号は？"] },
	{ original: "Burglar Alarm",	name: "盗難警報",	id: "burglarAlarm",	questions: ["表示された数字は？"] },
	{ original: "The Button",	name: "ボタン",	id: "BigButton",	questions: ["ライトは何色に光った？"] },
	{ original: "Button Sequence",	name: "順番ボタン",	id: "buttonSequencesModule",	questions: ["それぞれの色が何回登場した？"] },
	{ original: "Buttonage",	name: "大量ボタン",	id: "buttonageModule",	questions: ["各色と枠の色はいくつ？", "特殊ボタンはいくつ？", "Pが記されたボタンはいくつ？"] },
	{ original: "CA-RPS",	name: "じゃんけんグリッド",	id: "caRPS",	questions: ["初期状態の色は？"] },
	{ original: "Cacti’s Conundrum",	name: "サボテン難問",	id: "CactusPConundrum",	questions: ["LEDの色は？"] },
	{ original: "Caesar Cycle",	name: "カエサルサイクル",	id: "caesarCycle",	questions: ["ダイヤルが指していた方向は？", "ダイヤルに書かれていた英字は？"] },
	{ original: "Caesar Psycho",	name: "カエサルサイコ",	id: "caesarPsycho",	questions: ["各ステージにおける上のディスプレーのテキストと色は？"] },
	{ original: "Caesar’s Maths",	name: "カエサル数学",	id: "caesarsMaths",	questions: ["各LEDの色は？"] },
	{ original: "Calendar",	name: "カレンダー",	id: "calendar",	questions: ["祝日は？"] },
	{ original: "Cartinese",	name: "カーティ語",	id: "cartinese",	questions: ["各ボタンで再生された歌詞は？", "各ボタンの色は？"] },
	{ original: "Catchphrase",	name: "キャッチフレーズ",	id: "catchphrase",	questions: ["パネルの色は？"] },
	{ original: "Challenge & Contact",	name: "チャレンジ＆コンタクト",	id: "challengeAndContact",	questions: ["ディスプレーの文字は？"] },
	{ original: "Character Codes",	name: "文字コード",	id: "characterCodes",	questions: ["表示された文字は？"] },
	{ original: "Character Shift",	name: "文字シフト",	id: "characterShift",	questions: ["スライダーの文字は？"] },
	{ original: "Character Slots",	name: "キャラクタースロット",	id: "characterSlots",	questions: ["各ステージでそれぞれのスロットに誰が表示されていた？"] },
	{ original: "Cheap Checkout",	name: "安勘定",	id: "CheapCheckoutModule",	questions: ["支払金額は？"] },
	{ original: "Cheat Checkout",	name: "狡勘定",	id: "kataCheatCheckout",	questions: ["仮想通貨は？", "各ハッキングにおけるサイトとハッキングの手法は？"] },
	{ original: "Cheep Checkout",	name: "鳥勘定",	id: "cheepCheckout",	questions: ["どの鳥がいた？"] },
	{ original: "Chess",	name: "チェス",	id: "ChessModule",	questions: ["座標は？"] },
	{ original: "Chinese Counting",	name: "中国の数え方",	id: "chineseCounting",	questions: ["LEDの色は？"] },
	{ original: "Chinese Remainder Theorem",	name: "中国剰余定理",	id: "ChineseRemainderTheoremModule",	questions: ["方程式は？"] },
	{ original: "Chord Qualities",	name: "コードクオリティー",	id: "ChordQualities",	questions: ["与えられたコードの音は？"] },
	{ original: "The Code",	name: "コード",	id: "theCodeModule",	questions: ["表示された数字は？"] },
	{ original: "Codenames",	name: "コードネーム",	id: "codenames",	questions: ["どの言葉を送信した？"] },
	{ original: "Coffee Beans",	name: "コーヒー豆",	id: "coffeeBeans",	questions: ["動き方は？"] },
	{ original: "Coffeebucks",	name: "コーヒーバックス",	id: "coffeebucks",	questions: ["最後の客の好みの砂糖の量、時間帯、ストレスレベル、サイズは？"] },
	{ original: "Coinage",	name: "大量コイン",	id: "Coinage",	questions: ["どのコインが裏返された？"] },
	{ original: "Color Addition",	name: "色の加算",	id: "colorAddition",	questions: ["三つの数字は？"] },
	{ original: "Color Braille",	name: "色付き点字",	id: "ColorBrailleModule",	questions: ["各ドットの色は？"] },
	{ original: "Color Decoding",	name: "色の解読",	id: "Color Decoding",	questions: ["各ステージのインジケーターのパターンと色は？"] },
	{ original: "Color Morse",	name: "カラーモールス",	id: "ColorMorseModule",	questions: ["LEDの色は？", "LEDにより点滅している文字は？"] },
	{ original: "Color One Two",	name: "色の1と2",	id: "colorOneTwo",	questions: ["LEDの色は？"] },
	{ original: "Colored Keys",	name: "色付きキーパッド",	id: "lgndColoredKeys",	questions: ["表示された単語とその色は？", "各キーの色と文字は？"] },
	{ original: "Colored Squares",	name: "色付き格子",	id: "ColoredSquaresModule",	questions: ["最初の色のグループは？"] },
	{ original: "Colored Switches",	name: "色付きスイッチ",	id: "ColoredSwitchesModule",	questions: ["最初のスイッチの位置は？"] },
	{ original: "Colors Maximization",	name: "最大色",	id: "colors_maximization",	questions: ["各色のボタンは何個あった？"] },
	{ original: "Colour Flash",	name: "カラーフラッシュ",	id: "ColourFlash",	questions: ["シーケンスの最後の単語の色は？"] },
	{ original: "Coloured Cubes",	name: "色付きキューブ",	id: "ColouredCubes",	questions: ["各ステージにおけるキューブとステージライトの色は？"] },
	{ original: "Coloured Cylinder",	name: "色付きシリンダー",	id: "colouredCylinder",	questions: ["シリンダーの点滅色は？"] },
	{ original: "Concentration",	name: "集中",	id: "ConcentrationModule",	questions: ["初期配置は？"] },
	{ original: "Conditional Buttons",	name: "条件ボタン",	id: "conditionalButtons",	questions: ["各ボタンの色は？"] },
	{ original: "Connected Monitors",	name: "接続済みモニター",	id: "ConnectedMonitorsModule",	questions: ["最初に表示されていた数字は？", "インジケーターの色は？"] },
	{ original: "Connection Check",	name: "接続確認",	id: "graphModule",	questions: ["どの数字のペアが表示された？"] },
	{ original: "Coordinates",	name: "座標",	id: "CoordinatesModule",	questions: ["グリッドのサイズは？"] },
	{ original: "Coordination",	name: "座標グリッド",	id: "Coordination",	questions: ["開始座標のラベルと位置は？"] },
	{ original: "Coral Cipher",	name: "珊瑚色暗号",	id: "coralCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Corners",	name: "コーナー",	id: "CornersModule",	questions: ["角の色は？"] },
	{ original: "Cornflower Cipher",	name: "矢車菊色暗号",	id: "cornflowerCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Cosmic",	name: "宇宙",	id: "CosmicModule",	questions: ["最初に表示された番号は？"] },
	{ original: "Crazy Hamburger",	name: "クレイジーハンバーガー",	id: "GSCrazyHamburger",	questions: ["表示された材料は？"] },
	{ original: "Crazy Maze",	name: "クレイジー迷路",	id: "CrazyMazeModule",	questions: ["スタートとゴールの位置は？"] },
	{ original: "Cream Cipher",	name: "鳥子色暗号",	id: "creamCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Creation",	name: "クリエーション",	id: "CreationModule",	questions: ["最初の日付の天気状況は？"] },
	{ original: "Crimson Cipher",	name: "紅色暗号",	id: "crimsonCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Critters",	name: "クリッターズ",	id: "CrittersModule",	questions: ["色は？"] },
	{ original: "Cruel Binary",	name: "残忍二進数",	id: "CruelBinary",	questions: ["表示された単語は？"] },
	{ original: "Cruel Keypads",	name: "残忍キーパッド",	id: "CruelKeypads",	questions: ["各ステージのキーにあったシンボルは？", "各ステージのバーの色は？"] },
	{ original: "The cRule",	name: "残忍ルール",	id: "the_cRule",	questions: ["最初に埋められていたセルは？", "どのシンボルがどこに表示されていた？"] },
	{ original: "Cryptic Cycle",	name: "暗号サイクル",	id: "crypticCycle",	questions: ["ダイヤルが指していた方向は？", "ダイヤルに書かれていた英字は？"] },
	{ original: "Cryptic Keypad",	name: "暗号化キーパッド",	id: "GSCrypticKeypad",	questions: ["各キーのラベルと方角は？"] },
	{ original: "The Cube",	name: "キューブ",	id: "cube",	questions: ["キューブの回転は？"] },
	{ original: "Cursed Double-Oh",	name: "呪いのダブル・オー",	id: "CursedDoubleOhModule",	questions: ["最初に表示された数字の十の位は？"] },
	{ original: "Customer Identification",	name: "顧客識別",	id: "xelCustomerIdentification",	questions: ["表示された客は？"] },
	{ original: "The Cyan Button",	name: "シアンボタン",	id: "CyanButtonModule",	questions: ["各ステージでボタンはどこにあった？"] },
	{ original: "DACH Maze",	name: "DACH迷路",	id: "DACH",	questions: ["出発点はどこ？"] },
	{ original: "Deaf Alley",	name: "デフ・アレイ",	id: "deafAlleyModule",	questions: ["生成された形は？"] },
	{ original: "The Deck of Many Things",	name: "多種デッキ",	id: "deckOfManyThings",	questions: ["最初のカードが所属するデッキは？"] },
	{ original: "Decolored Squares",	name: "色抜き格子",	id: "DecoloredSquaresModule",	questions: ["開始した段と列に該当する色は？"] },
	{ original: "Decolour Flash",	name: "デカラーフラッシュ",	id: "DecolourFlashModule",	questions: ["各ゴールの色と単語は？"] },
	{ original: "Denial Displays",	name: "否定的ディスプレー",	id: "DenialDisplaysModule",	questions: ["ディスプレーの初期状態は？"] },
	{ original: "DetoNATO",	name: "デトナト",	id: "Detonato",	questions: ["各ステージで表示された単語は？"] },
	{ original: "Devilish Eggs",	name: "悪魔の卵",	id: "devilishEggs",	questions: ["回転方向は？", "プリズムが示した数字と文字は？"] },
	{ original: "Dialtones",	name: "ダイヤル音声",	id: "xelDialtones",	questions: ["再生されたトーンは？"] },
	{ original: "Digisibility",	name: "除算可能",	id: "digisibility",	questions: ["ボタン上の数字は？"] },
	{ original: "Digit String",	name: "数字列",	id: "digitString",	questions: ["表示された数字文字列は？"] },
	{ original: "Dimension Disruption",	name: "次元破壊",	id: "dimensionDisruption",	questions: ["見えている文字は？"] },
	{ original: "Directional Button",	name: "方向ボタン",	id: "directionalButton",	questions: ["各ステージで何回ボタンを押した？"] },
	{ original: "Discolored Squares",	name: "色変え格子",	id: "DiscoloredSquaresModule",	questions: ["各色の覚えた位置は？"] },
	{ original: "Disordered Keys",	name: "欠陥順番音板",	id: "disorderedKeys",	questions: ["各音板の欠けていた情報と完全/不完全な音板の色、ラベル、ラベルの色は？"] },
	{ original: "Divided Squares",	name: "分割スクエア",	id: "DividedSquaresModule",	questions: ["正しい正方形を押している間の色は？"] },
	{ original: "Divisible Numbers",	name: "割り切れる数字",	id: "divisibleNumbers",	questions: ["各ステージの数字は？"] },
	{ original: "DNA Mutation",	name: "DNA Mutation",	id: "DNAMutation",	questions: ["DNA鎖の色は？", "与えられたヌクレオチドの文字と色は？"] },
	{ original: "Doofenshmirtz Evil Inc.",	name: "悪のドゥーフェンシュマーツ社",	id: "doofenshmirtzEvilIncModule",	questions: ["再生されたジングルは？", "表示された画像は？"] },
	{ original: "Double Arrows",	name: "ダブル矢印",	id: "doubleArrows",	questions: ["開始位置は？"] },
	{ original: "Double Color",	name: "二色",	id: "doubleColor",	questions: ["各ステージの画面の色は？"] },
	{ original: "Double Digits",	name: "二桁",	id: "doubleDigitsModule",	questions: ["ディスプレー上の数字は？"] },
	{ original: "Double Expert",	name: "ダブル・エキスパート",	id: "doubleExpert",	questions: ["初期のキー番号は？"] },
	{ original: "Double Listening",	name: "ダブルリスニング",	id: "doubleListening",	questions: ["再生された音は？"] },
	{ original: "Double Screen",	name: "二画面",	id: "doubleScreenModule",	questions: ["各ステージにおける画面の色は？"] },
	{ original: "Dr. Doctor",	name: "医学博士",	id: "DrDoctorModule",	questions: ["どのような症状や病気が挙げられた？"] },
	{ original: "Dreamcipher",	name: "夢想暗号",	id: "ksmDreamcipher",	questions: ["解読した単語は？"] },
	{ original: "The Duck",	name: "アヒル",	id: "theDuck",	questions: ["カーテンの色は？", "アヒルへの接触方法は？"] },
	{ original: "Dumb Waiters",	name: "小荷物専用昇降機",	id: "dumbWaiters",	questions: ["どのプレイヤーが存在した？"] },
	{ original: "Earthbound",	name: "MOTHER",	id: "EarthboundModule",	questions: ["背景は？", "表示されたモンスターは？"] },
	{ original: "eeB gnillepS",	name: "ービ・グンリペス",	id: "eeBgnilleps",	questions: ["綴るべき単語は？"] },
	{ original: "Eight",	name: "八",	id: "eight",	questions: ["小さなディスプレーの最後の数字は？", "最後に破壊された数字の位置は？", "最後の結果の値は？", "最後に表示された数字は？"] },
	{ original: "Elder Futhark",	name: "エルダー・フサルク",	id: "elderFuthark",	questions: ["表示されたルーンは？"] },
	{ original: "Emoji",	name: "絵文字",	id: "emoji",	questions: ["絵文字は？"] },
	{ original: "Encrypted Dice",	name: "暗号化ダイス",	id: "EncryptedDice",	questions: ["各ステージでどの目が出た？"] },
	{ original: "Encrypted Equations",	name: "暗号化方程式",	id: "EncryptedEquationsModule",	questions: ["3つのオペランドの主な図形は？"] },
	{ original: "Encrypted Hangman",	name: "暗号化ハングマン",	id: "encryptedHangman",	questions: ["暗号化モジュールの名前と暗号化規則は？"] },
	{ original: "Encrypted Maze",	name: "暗号化迷路",	id: "encryptedMaze",	questions: ["どのシンボルがどの方向に回っている？"] },
	{ original: "Encrypted Morse",	name: "暗号化モールス信号",	id: "EncryptedMorse",	questions: ["受信したキーは？"] },
	{ original: "Encryption Bingo",	name: "暗号化ビンゴ",	id: "encryptionBingo",	questions: ["最初に使用された暗号化方式は？"] },
	{ original: "English Entries",	name: "英会話教材",	id: "EnglishEntries",	questions: ["表示されている引用文は？"] },
	{ original: "Enigma Cycle",	name: "エニグマサイクル",	id: "enigmaCycle",	questions: ["ダイヤルが指していた方向は？", "ダイヤルに書かれていた英字は？"] },
	{ original: "Entry Number Four",	name: "エントリーナンバー4",	id: "GSEntryNumberFour",	questions: ["表示された数字は？"] },
	{ original: "Entry Number One",	name: "エントリーナンバー1",	id: "GSEntryNumberOne",	questions: ["表示された数字は？"] },
	{ original: "Épelle-moi Ça",	name: "Épelle-moi Ça",	id: "epelleMoiCa",	questions: ["綴るべき単語は？"] },
	{ original: "Equations X",	name: "方程式X",	id: "equationsXModule",	questions: ["表示されたシンボルは？"] },
	{ original: "Error Codes",	name: "エラーコード",	id: "errorCodes",	questions: ["有効だったエラーコードは？"] },
	{ original: "Etterna",	name: "エテルナ",	id: "etterna",	questions: ["各矢印による入力はどのような拍子だった？"] },
	{ original: "Exoplanets",	name: "太陽系外惑星",	id: "exoplanets",	questions: ["開始時と解除時のターゲット惑星と数字は？"] },
	{ original: "ƎNA Cipher",	name: "エナ暗号",	id: "enaCipher",	questions: ["キーワードと転置キー、暗号化された単語は？"] },
	{ original: "Factoring Maze",	name: "因数迷路",	id: "factoringMaze",	questions: ["どの素数を使用した？"] },
	{ original: "Factory Maze",	name: "工場迷路",	id: "factoryMaze",	questions: ["最初にいた部屋はどこ？"] },
	{ original: "Faerie Fires",	name: "妖精の火",	id: "FaerieFiresModule",	questions: ["妖精の色と音程は？"] },
	{ original: "Fast Math",	name: "速算",	id: "fastMath",	questions: ["最後の英字のペアは？"] },
	{ original: "Fast Playfair Cipher",	name: "速プレイフェア暗号",	id: "FastPlayfairCipher",	questions: ["最後に表示されたメッセージは？"] },
	{ original: "Faulty Buttons",	name: "欠陥ボタン",	id: "GSFaultyButtons",	questions: ["どのボタンがどのボタンを参照していた？"] },
	{ original: "Faulty RGB Maze",	name: "欠陥RGB迷路",	id: "faultyrgbMaze",	questions: ["迷路の出口と鍵は？", "各迷路の数字は？"] },
	{ original: "Find The Date",	name: "曜日の特定",	id: "DateFinder",	questions: ["各ステージの年月日は？"] },
	{ original: "Five Letter Words",	name: "5文字の単語",	id: "FiveLetterWords",	questions: ["表示された単語は？"] },
	{ original: "FizzBuzz",	name: "フィズバズ",	id: "fizzBuzzModule",	questions: ["表示された数字は？"] },
	{ original: "Flags",	name: "国旗",	id: "FlagsModule",	questions: ["国旗、メインの旗、表示された番号は？"] },
	{ original: "Flashing Arrows",	name: "点滅矢印",	id: "flashingArrowsModule",	questions: ["ディスプレーに表示された数は？", "関連する矢印の色は？"] },
	{ original: "Flashing Lights",	name: "点滅ライト",	id: "flashingLights",	questions: ["各色のLEDは何回点滅した？"] },
	{ original: "Flavor Text EX",	name: "フレーバーテキストEX",	id: "FlavorTextCruel",	questions: ["各ステージにおいてどのモジュールのフレーバーテキストが表示されていた？"] },
	{ original: "Flyswatting",	name: "ハエ叩き",	id: "flyswatting",	questions: ["存在していたが、回答ではないハエは？"] },
	{ original: "Follow Me",	name: "フォロー・ミー",	id: "FollowMe",	questions: ["点滅した方向は？"] },
	{ original: "Forest Cipher",	name: "柚葉色暗号",	id: "forestCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Forget Any Color",	name: "全色忘る",	id: "ForgetAnyColor",	questions: ["各ステージのシリンダーの色は？", "各ステージで使われた図は？"] },
	{ original: "Forget Everything",	name: "須く忘る",	id: "HexiEvilFMN",	questions: ["ステージ1で表示された数字は？"] },
	{ original: "Forget Me",	name: "我忘る",	id: "forgetMe",	questions: ["初めのパズルはどの数字がどの位置にあった？"] },
	{ original: "Forget Me Not",	name: "我忘る勿かれ",	id: "MemoryV2",	questions: ["各ステージで表示された数字は？"] },
	{ original: "Forget Me Now",	name: "我忘るる",	id: "ForgetMeNow",	questions: ["表示された数字は？"] },
	{ original: "Forget Our Voices",	name: "Forget Our Voices",	id: "forgetOurVoices",	questions: ["各ステージで発言したのは誰？"] },
	{ original: "Forget The Colors",	name: "色忘る",	id: "ForgetTheColors",	questions: ["各ステージの大きなディスプレー、歯車、sin値の下一桁は？", "各ステージにおいて、どのエッジワークに基づくルールが当てはまった？"] },
	{ original: "Forget This",	name: "之忘る",	id: "forgetThis",	questions: ["各ステージで表示された文字は？", "各ステージのLEDの色は？"] },
	{ original: "Forget Us Not",	name: "我等忘る勿かれ",	id: "forgetUsNot",	questions: ["各ステージで解除されたモジュールは？"] },
	{ original: "Forget’s Ultimate Showdown",	name: "忘る者の究極の対決",	id: "ForgetsUltimateShowdownModule",	questions: ["最初の数字は？", "下部の数字は？", "答えは？", "使用されている暗号方式は？"] },
	{ original: "Free Parking",	name: "無料駐車場",	id: "freeParking",	questions: ["プレイヤーのコマは？"] },
	{ original: "The French Republican Calendar",	name: "The French Republican Calendar",	id: "FrenchRepublicanCalendar",	questions: ["LEDの色は？"] },
	{ original: "Functions",	name: "関数",	id: "qFunctions",	questions: ["最初のクエリの結果の下一桁は？", "下部に表示された数字と英字は？"] },
	{ original: "The Fuse Box",	name: "ヒューズボックス",	id: "FuseBox",	questions: ["点滅した色は？", "どの矢印が正しかった？"] },
	{ original: "Gadgetron Vendor",	name: "ガラクトロン・ベンダー",	id: "lgndGadgetronVendor",	questions: ["表示された武器は？"] },
	{ original: "Game of Life Cruel",	name: "残忍ライフゲーム",	id: "GameOfLifeCruel",	questions: ["どの色の組み合わせが登場した？"] },
	{ original: "The Gamepad",	name: "ゲームパッド",	id: "TheGamepadModule",	questions: ["数字は？"] },
	{ original: "Garfield Kart",	name: "ガーフィールドカート",	id: "garfieldKart",	questions: ["コース名は？", "パズルのピースの数は？"] },
	{ original: "The Garnet Thief",	name: "宝石泥棒",	id: "theGarnetThief",	questions: ["各参加者が選んだと主張している派閥はどれだった？"] },
	{ original: "Ghost Movement",	name: "Ghost Movement",	id: "ghostMovement",	questions: ["パックマンとゴーストの位置は？"] },
	{ original: "Giants Cipher",	name: "Giants Cipher",	id: "GiantsCipher",	questions: ["表示されたキーワードは？"] },
	{ original: "Girlfriend",	name: "Girlfriend",	id: "Girlfriend",	questions: ["選択された言語は？"] },
	{ original: "The Glitched Button",	name: "グリッチボタン",	id: "GlitchedButtonModule",	questions: ["循環しているビットのシーケンスは？"] },
	{ original: "Goofy’s Game",	name: "グーフィーのゲーム",	id: "goofysgame",	questions: ["モールス信号で表示された数字は？"] },
	{ original: "Grand Piano",	name: "グランドピアノ",	id: "grandPiano",	questions: ["与えられた音は？"] },
	{ original: "The Gray Button",	name: "灰色ボタン",	id: "GrayButtonModule",	questions: ["ディスプレー上の座標は？"] },
	{ original: "Gray Cipher",	name: "灰色暗号",	id: "grayCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "The Great Void",	name: "超空洞",	id: "greatVoid",	questions: ["数字と色は？"] },
	{ original: "Green Arrows",	name: "緑色矢印",	id: "greenArrowsModule",	questions: ["ディスプレー上の最後の数字は？"] },
	{ original: "The Green Button",	name: "緑色ボタン",	id: "GreenButtonModule",	questions: ["送信した単語は？"] },
	{ original: "Green Cipher",	name: "緑色暗号",	id: "greenCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Gridlock",	name: "グリッドロック",	id: "GridlockModule",	questions: ["最初の色は？", "開始位置は？"] },
	{ original: "Grocery Store",	name: "食料品店",	id: "groceryStore",	questions: ["最初に表示されたアイテムは？"] },
	{ original: "Gryphons",	name: "グリフォン",	id: "gryphons",	questions: ["グリフォンの名前と年齢は？"] },
	{ original: "Guess Who?",	name: "だーれだ？",	id: "GuessWho",	questions: ["「YES」が表示された色は？"] },
	{ original: "Gyromaze",	name: "ジャイロ迷路",	id: "gyromaze",	questions: ["LEDの色は？"] },
	{ original: "h",	name: "H",	id: "Averageh",	questions: ["送信した英字は？"] },
	{ original: "Halli Galli",	name: "ハリガリ",	id: "halliGalli",	questions: ["5個あった果物は？", "使用した分け方は？"] },
	{ original: "Hereditary Base Notation",	name: "遺伝的基数表記",	id: "hereditaryBaseNotationModule",	questions: ["下部のディスプレーに表示された数字は？"] },
	{ original: "The Hexabutton",	name: "六角形ボタン",	id: "hexabutton",	questions: ["長押し中のボタンの色は？", "送信されたモールス信号の文字は？"] },
	{ original: "Hexamaze",	name: "六角迷路",	id: "HexamazeModule",	questions: ["ポーンの色は？"] },
	{ original: "hexOrbits",	name: "hexOrbits",	id: "hexOrbits",	questions: ["表示された図形は？"] },
	{ original: "hexOS",	name: "HexOS",	id: "hexOS",	questions: ["解読された文字とフレーズは？", "ディスプレーで周期的に表示される3桁の数字は？", "リズムの値は？"] },
	{ original: "Hickory Dickory Dock",	name: "Hickory Dickory Dock",	id: "hickoryDickoryDockModule",	questions: ["時計が鳴った時、示していた時刻は？"] },
	{ original: "Hidden Colors",	name: "隠し色",	id: "lgndHiddenColors",	questions: ["メインのLEDの色は？"] },
	{ original: "The Hidden Value",	name: "隠し値",	id: "theHiddenValue",	questions: ["表示された数字と色は？"] },
	{ original: "The High Score",	name: "ハイスコア",	id: "ksmHighScore",	questions: ["プレイヤーの位置とスコアは？"] },
	{ original: "Hill Cycle",	name: "ヒルサイクル",	id: "hillCycle",	questions: ["ダイヤルが指していた方向は？", "ダイヤルに書かれていた英字は？"] },
	{ original: "Hinges",	name: "蝶番",	id: "hinges",	questions: ["初期状態で存在していた蝶番は？"] },
	{ original: "Hogwarts",	name: "ホグワーツ",	id: "HogwartsModule",	questions: ["各モジュールを解除するための寮はどれ？"] },
	{ original: "Hold Ups",	name: "ホールドアップ",	id: "KritHoldUps",	questions: ["各シャドウの名前は？"] },
	{ original: "Holographic Memory",	name: "ホログラム記憶",	id: "holographicMemory",	questions: ["各シンボルが表示されたのはどちら側？"] },
	{ original: "Homophones",	name: "同音異義語",	id: "homophones",	questions: ["表示されたフレーズは？"] },
	{ original: "Horrible Memory",	name: "恐怖記憶",	id: "horribleMemory",	questions: ["各ステージごとのそれぞれのボタンの色とラベルは？", "各ステージで表示された数字は？"] },
	{ original: "Human Resources",	name: "人事部",	id: "HumanResourcesModule",	questions: ["存在した従業員と応募者は？", "赤と緑で表示されたのはどの識別語？"] },
	{ original: "Hunting",	name: "狩猟",	id: "hunting",	questions: ["表示された絵文字は？"] },
	{ original: "The Hypercube",	name: "超立方体",	id: "TheHypercubeModule",	questions: ["回転方向は？"] },
	{ original: "HyperForget",	name: "超忘る",	id: "HyperForget",	questions: ["回転方向は？"] },
	{ original: "The Hyperlink",	name: "ハイパーリンク",	id: "hyperlink",	questions: ["ハイパーリンクは？", "どのモジュールが参照されている？"] },
	{ original: "Ice Cream",	name: "アイスクリーム",	id: "iceCreamModule",	questions: ["客は誰？", "各客が注文したのはどのフレーバー？"] },
	{ original: "Identification Crisis",	name: "識別危機",	id: "identificationCrisis",	questions: ["使用された図形や識別モジュールは？"] },
	{ original: "Identity Parade",	name: "容疑者特定",	id: "identityParade",	questions: ["モジュールに並べられた髪の色、体格、服装は？"] },
	{ original: "Indigo Cipher",	name: "藍色暗号",	id: "indigoCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Infinite Loop",	name: "無限ループ",	id: "InfiniteLoop",	questions: ["選ばれた言葉は？"] },
	{ original: "Ingredients",	name: "食材",	id: "ingredients",	questions: ["どの食材が記載され、どれを利用した？"] },
	{ original: "Inner Connections",	name: "内部接続",	id: "InnerConnectionsModule",	questions: ["LEDの色は？", "モールス信号で示された数は？"] },
	{ original: "Interpunct",	name: "句読点",	id: "interpunct",	questions: ["各ステージで表示されたシンボルは？"] },
	{ original: "IPA",	name: "IPA",	id: "ipa",	questions: ["正しい記号は？"] },
	{ original: "The iPhone",	name: "アイフォン",	id: "iPhone",	questions: ["PINの値は？"] },
	{ original: "Jenga",	name: "ジェンガ",	id: "jenga",	questions: ["最初に引き抜いたブロックにあったシンボルは？"] },
	{ original: "The Jewel Vault",	name: "宝石金庫",	id: "jewelVault",	questions: ["どのホイールがどのホイールを回転させ、どのホイールが自分で回転した？"] },
	{ original: "Jumble Cycle",	name: "寄せ集めサイクル",	id: "jumbleCycle",	questions: ["ダイヤルが指していた方向は？", "ダイヤルに書かれていた英字は？"] },
	{ original: "Juxtacolored Squares",	name: "色比べ格子",	id: "JuxtacoloredSquaresModule",	questions: ["各マスの色は？"] },
	{ original: "Kanji",	name: "漢字",	id: "KanjiModule",	questions: ["各ステージで表示された単語は？"] },
	{ original: "The Kanye Encounter",	name: "カニエ・ウエストとの遭遇",	id: "TheKanyeEncounter",	questions: ["どの食べ物アイテムが表示された？"] },
	{ original: "KayMazey Talk",	name: "K迷路トーク",	id: "KMazeyTalk",	questions: ["開始位置とゴール位置は？"] },
	{ original: "Keypad Combinations",	name: "キーパッドコンビネーション",	id: "keypadCombinations",	questions: ["答えに含まれない、存在した数字は？"] },
	{ original: "Keypad Magnified",	name: "拡大キーパッド",	id: "keypadMagnified",	questions: ["LEDの位置は？"] },
	{ original: "Keypad Maze",	name: "キーパッド迷路",	id: "KeypadMaze",	questions: ["黄色いセルの位置は？"] },
	{ original: "Keypad Sequence",	name: "順番キーパッド",	id: "keypadSeq",	questions: ["キーに書かれていたシンボルは？"] },
	{ original: "Keywords",	name: "キーワード",	id: "xtrkeywords",	questions: ["ディスプレー上の文字は？"] },
	{ original: "The Klaxon",	name: "クラクション",	id: "klaxon",	questions: ["最初にクラクションが鳴ったモジュールは？"] },
	{ original: "Know Your Way",	name: "方向感覚",	id: "KnowYourWay",	questions: ["矢印が指していたのはどの方向？", "どのLEDが緑色だった？"] },
	{ original: "Kooky Keypad",	name: "狂ったキーパッド",	id: "kookyKeypadModule",	questions: ["LEDの色は？"] },
	{ original: "Kudosudoku",	name: "クド数独",	id: "KudosudokuModule",	questions: ["どの四角が最初に埋まっていた？"] },
	{ original: "Kugelblitz",	name: "クーゲルブリッツ",	id: "kugelblitz",	questions: ["各ステージで存在していた粒子は？", "各ステージの粒子の値は？"] },
	{ original: "Kuro",	name: "Kuro",	id: "Kuro",	questions: ["Kuroの気分は？"] },
	{ original: "The Labyrinth",	name: "迷宮",	id: "labyrinth",	questions: ["どの層で、ポータルがどの位置に表示された？"] },
	{ original: "Ladder Lottery",	name: "あみだくじ",	id: "ladderLottery",	questions: ["どのライトが点灯していた？"] },
	{ original: "Ladders",	name: "梯子",	id: "ladders",	questions: ["2つ目の梯子には何色が現れていた？", "3つ目の梯子は何色が無かった？"] },
	{ original: "Langton’s Anteater",	name: "Langton’s Anteater",	id: "GSLangtonsAnteater",	questions: ["グリッドの初期状態は？"] },
	{ original: "LED Encryption",	name: "暗号化LED",	id: "LEDEnc",	questions: ["各ステージで存在した文字は？"] },
	{ original: "LED Grid",	name: "LEDグリッド",	id: "ledGrid",	questions: ["点灯していないLEDはいくつ？"] },
	{ original: "LED Math",	name: "LED算",	id: "lgndLEDMath",	questions: ["LEDの色は？"] },
	{ original: "LEDs",	name: "LEDセット",	id: "leds",	questions: ["変化したLEDの初めの色は？"] },
	{ original: "LEGOs",	name: "LEGO",	id: "LEGOModule",	questions: ["各色のピースの大きさは？"] },
	{ original: "Lempel-Ziv Cipher",	name: "Lempel-Ziv暗号",	id: "LempelZivCipherModule",	questions: ["各スクリーンの文字は？"] },
	{ original: "Letter Math",	name: "英字数学",	id: "letterMath",	questions: ["ディスプレー上の文字は？"] },
	{ original: "Light Bulbs",	name: "電球セット",	id: "LightBulbs",	questions: ["電球の色は？"] },
	{ original: "Lime Arrows",	name: "Lime Arrows",	id: "limeArrowsModule",	questions: ["初期座標は？"] },
	{ original: "Linq",	name: "リンク",	id: "Linq",	questions: ["機能は？"] },
	{ original: "Lion’s Share",	name: "ライオンの分け前",	id: "LionsShareModule",	questions: ["表示された年は？", "どのライオンが存在したが居なくなった？"] },
	{ original: "Listening",	name: "リスニング",	id: "Listening",	questions: ["再生された音は？"] },
	{ original: "Literal Maze",	name: "Literal Maze",	id: "literalMaze",	questions: ["各位置にある英字は？"] },
	{ original: "Logic Gates",	name: "論理ゲート",	id: "logicGates",	questions: ["論理ゲートA-Dは？"] },
	{ original: "Logical Buttons",	name: "論理ボタン",	id: "logicalButtonsModule",	questions: ["各ステージごとのそれぞれのボタンの色とラベルは？", "各ステージにおける最後のオペレーターは？"] },
	{ original: "Lombax Cubes",	name: "ロンバックスキューブ",	id: "lgndLombaxCubes",	questions: ["ボタンの文字は？"] },
	{ original: "The London Underground",	name: "ロンドン地下鉄",	id: "londonUnderground",	questions: ["出発地と目的地は？"] },
	{ original: "Long Words",	name: "Long Words",	id: "LongWords",	questions: ["上のディスプレーに表示されていた単語は？"] },
	{ original: "M-Seq",	name: "リズム正方型",	id: "mSeq",	questions: ["得られた数字は？", "繰り返し作業による、最終的な数字は？"] },
	{ original: "M&Ms",	name: "MとM",	id: "MandMs",	questions: ["ボタンのラベルと色は？"] },
	{ original: "M&Ns",	name: "MとN",	id: "MandNs",	questions: ["ボタンのラベルの色は？", "正しいボタンのラベルは？"] },
	{ original: "Mad Memory",	name: "狂気記憶",	id: "MadMemory",	questions: ["各ステージにおけるディスプレーは？"] },
	{ original: "Mafia",	name: "マフィア",	id: "MafiaModule",	questions: ["プレイヤーであるがゴッドファーザーではないのは誰？"] },
	{ original: "Magenta Cipher",	name: "マゼンタ暗号",	id: "magentaCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Mahjong",	name: "麻雀パズル",	id: "MahjongModule",	questions: ["左下のタイルは？"] },
	{ original: "Main Page",	name: "Main Page",	id: "mainpage",	questions: ["表示された/されなかった吹き出しの色とメッセージは？", "ホームスター、背景、ボタンの効果はどれ？"] },
	{ original: "Maritime Flags",	name: "海上旗",	id: "MaritimeFlagsModule",	questions: ["どの方角を示していた？", "どのコールサインを送信していた？"] },
	{ original: "Maritime Semaphore",	name: "海上セマフォア信号",	id: "MaritimeSemaphoreModule",	questions: ["ダミーの位置は？", "受信した英字は？"] },
	{ original: "The Maroon Button",	name: "The Maroon Button",	id: "MaroonButtonModule",	questions: ["Aは？"] },
	{ original: "Maroon Cipher",	name: "栗色暗号",	id: "maroonCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Mashematics",	name: "連打算数",	id: "mashematics",	questions: ["方程式内の数字は？"] },
	{ original: "Master Tapes",	name: "マスターテープ",	id: "masterTape",	questions: ["再生された曲は？"] },
	{ original: "Match Refereeing",	name: "Match Refereeing",	id: "matchRefereeing",	questions: ["各ステージにあった惑星は？"] },
	{ original: "Math ’em",	name: "計算神経衰弱",	id: "mathem",	questions: ["シャッフル前の各タイルのデザインと色は？"] },
	{ original: "The Matrix",	name: "マトリックス",	id: "matrix",	questions: ["最後に使用されたアクセスコードの一部だった単語は？"] },
	{ original: "Maze",	name: "迷路",	id: "Maze",	questions: ["開始位置は？"] },
	{ original: "Maze Identification",	name: "Maze Identification",	id: "GSMazeIdentification",	questions: ["Seed値は？", "各ボタンの機能は？"] },
	{ original: "Maze Scrambler",	name: "迷路スクランブラー",	id: "MazeScrambler",	questions: ["開始位置は？", "ゴールの位置は？", "迷路のマークはどの位置にあった？"] },
	{ original: "Maze Swap",	name: "入れ替え迷路",	id: "mazeSwap",	questions: ["スタートとゴールの位置は？"] },
	{ original: "Maze³",	name: "迷路³",	id: "maze3",	questions: ["最初に正面にある色は？"] },
	{ original: "Mazematics",	name: "計算迷路",	id: "mazematics",	questions: ["最初とゴールの値は？"] },
	{ original: "Mazeseeker",	name: "Mazeseeker",	id: "GSMazeseeker",	questions: ["各セルを囲む壁はいくつ？", "スタートとゴールの位置は？"] },
	{ original: "Memorable Buttons",	name: "記憶ボタン",	id: "memorableButtons",	questions: ["正しいボタンのシンボルは？"] },
	{ original: "Memory",	name: "記憶",	id: "Memory",	questions: ["各ステージで表示された数は？"] },
	{ original: "Memory Wires",	name: "記憶ワイヤ",	id: "memoryWires",	questions: ["ワイヤの色は？", "表示された数字は？"] },
	{ original: "Metamorse",	name: "メタモールス",	id: "metamorse",	questions: ["抽出された文字は？"] },
	{ original: "Metapuzzle",	name: "メタパズル",	id: "metapuzzle",	questions: ["最終的な回答は？"] },
	{ original: "Minsk Metro",	name: "Minsk Metro",	id: "minskMetro",	questions: ["開始地点の駅は？"] },
	{ original: "Mirror",	name: "鏡",	id: "mirror",	questions: ["オリジナルのお化けが記した2番目の言葉は？"] },
	{ original: "The Missing Letter",	name: "欠落英字",	id: "theMissingLetter",	questions: ["欠落している英字は？"] },
	{ original: "Mister Softee",	name: "ミスター・ソフティー",	id: "misterSoftee",	questions: ["スポンジ・ボブ・バーはどこ？", "どのおやつがあった？"] },
	{ original: "Mixometer",	name: "Mixometer",	id: "mixometer",	questions: ["送信ボタンの位置は？"] },
	{ original: "Module Listening",	name: "モジュールリスニング",	id: "moduleListening",	questions: ["再生された音は？", "各ボタンが再生した音は？"] },
	{ original: "Module Maneuvers",	name: "Module Maneuvers",	id: "moduleManeuvers",	questions: ["ゴールの位置は？"] },
	{ original: "Module Maze",	name: "モジュール迷路",	id: "ModuleMaze",	questions: ["スタートのアイコンは？"] },
	{ original: "Module Movements",	name: "モジュール追跡",	id: "moduleMovements",	questions: ["各ステージで表示されたモジュールは？"] },
	{ original: "Money Game",	name: "マネーゲーム",	id: "MoneyGame",	questions: ["フレーズは？"] },
	{ original: "Monsplode Trading Cards",	name: "モンスプロード・カードゲーム",	id: "monsplodeCards",	questions: ["最終交換/キープの直前の手札にあった3枚のカードの名前と印刷バージョンは？"] },
	{ original: "Monsplode, Fight!",	name: "モンスプロード・ファイト！",	id: "monsplodeFight",	questions: ["どのクリーチャーが表示された？", "選択可能な技は？"] },
	{ original: "The Moon",	name: "月",	id: "moon",	questions: ["最初に点灯/消灯していたのは？"] },
	{ original: "More Code",	name: "新モールス信号",	id: "MoreCode",	questions: ["点滅している単語は？"] },
	{ original: "Morse Buttons",	name: "モールスボタン",	id: "morseButtons",	questions: ["各ボタンで点滅している文字と色は？"] },
	{ original: "Morse War",	name: "モールス戦争",	id: "MorseWar",	questions: ["LEDの状態は？", "送信した文字は？"] },
	{ original: "Morse-A-Maze",	name: "モールス迷路",	id: "MorseAMaze",	questions: ["最初と最後の位置は？", "再生されているモールス信号は？"] },
	{ original: "Morsematics",	name: "モールスマティック",	id: "MorseV2",	questions: ["受信した文字は？"] },
	{ original: "Mouse In The Maze",	name: "迷路のネズミ",	id: "MouseInTheMaze",	questions: ["輪の色は？"] },
	{ original: "Mssngv Wls",	name: "欠落母音",	id: "MssngvWls",	questions: ["欠落していた母音は？"] },
	{ original: "Multicolored Switches",	name: "色どりスイッチ",	id: "R4YMultiColoredSwitches",	questions: ["両サイクルのLEDの色は？"] },
	{ original: "The Multiverse Hotline",	name: "The Multiverse Hotline",	id: "MultiverseHotline",	questions: ["発信元の宇宙とその初期値は？"] },
	{ original: "Murder",	name: "殺人",	id: "murder",	questions: ["容疑者と武器は？", "遺体は何処で見つかった？"] },
	{ original: "Mystery Module",	name: "ミステリーモジュール",	id: "mysterymodule",	questions: ["どのモジュールが隠されていた？", "最初に解除するように指示されたモジュールは？"] },
	{ original: "Mystic Square",	name: "神秘スクエア",	id: "MysticSquareModule",	questions: ["初期状態の中央の数字は？"] },
	{ original: "N&Ms",	name: "NとM",	id: "NandMs",	questions: ["正しいボタンのラベルは？"] },
	{ original: "N&Ns",	name: "NとN",	id: "NandNs",	questions: ["ステージ2と3のラベルは？", "ステージ3で欠けていた色は？"] },
	{ original: "Name Codes",	name: "名前コード",	id: "nameCodes",	questions: ["左右の指標は？"] },
	{ original: "Naming Conventions",	name: "命名規則",	id: "NamingConventions",	questions: ["最初のボタンのラベルは？"] },
	{ original: "Navigation Determination",	name: "ナビ決定",	id: "NavigationDeterminationModule",	questions: ["迷路の色とラベルは？"] },
	{ original: "Navinums",	name: "ナビ数字",	id: "navinums",	questions: ["どの方向ボタンが押された？", "最初の中央の数字は？"] },
	{ original: "The Navy Button",	name: "The Navy Button",	id: "NavyButtonModule",	questions: ["どのギリシャ文字が現れた？", "座標とそれから得られる値は？"] },
	{ original: "The Necronomicon",	name: "ネクロノミコン",	id: "necronomicon",	questions: ["What were the chapter numbers?"] },
	{ original: "Negativity",	name: "負極性",	id: "Negativity",	questions: ["送信した値は(十進数と平衡三進数で)？"] },
	{ original: "Neptune",	name: "海王星",	id: "neptune",	questions: ["表示されたスターは？"] },
	{ original: "Neutralization",	name: "中和滴定",	id: "neutralization",	questions: ["酸の色と量は？"] },
	{ original: "Next In Line",	name: "ネクストライン",	id: "NextInLine",	questions: ["1番目のワイヤの色は？"] },
	{ original: "Nim",	name: "Nim",	id: "nim",	questions: ["各段にあったマッチの数は？"] },
	{ original: "Noise Identification",	name: "Noise Identification",	id: "noiseIdentification",	questions: ["最初に表示されたノイズの種類は？"] },
	{ original: "Not Colored Squares",	name: "偽色付き格子",	id: "NotColoredSquaresModule",	questions: ["初めに押したのはどの位置？"] },
	{ original: "Not Colored Switches",	name: "偽色付きスイッチ",	id: "NotColoredSwitchesModule",	questions: ["暗号化された単語は？"] },
	{ original: "Not Colour Flash",	name: "偽カラーフラッシュ",	id: "notColourFlash",	questions: ["表示された単語シーケンスと色シーケンスは？"] },
	{ original: "Not Connection Check",	name: "偽接続確認",	id: "notConnectionCheck",	questions: ["点滅していたシンボルは？", "ボタンの値は？"] },
	{ original: "Not Coordinates",	name: "偽座標",	id: "notCoordinates",	questions: ["正方形の頂点は？"] },
	{ original: "Not Double-Oh",	name: "偽ダブル・オー",	id: "NotDoubleOhModule",	questions: ["第2ステージで表示された位置は？"] },
	{ original: "Not Keypad",	name: "偽キーパッド",	id: "NotKeypad",	questions: ["最後のシーケンスで点滅した色は？", "最後のシーケンスで点滅したボタンのシンボルは？"] },
	{ original: "Not Maze",	name: "偽迷路",	id: "NotMaze",	questions: ["開始時の距離は?"] },
	{ original: "Not Morse Code",	name: "偽モールス信号",	id: "NotMorseCode",	questions: ["送信した単語の並びは？"] },
	{ original: "Not Morsematics",	name: "偽モールスマティック",	id: "notMorsematics",	questions: ["送信された単語は？"] },
	{ original: "Not Murder",	name: "偽殺人",	id: "notMurder",	questions: ["最初に容疑者はどの部屋にいた？", "最初に容疑者はどの武器を使用した？"] },
	{ original: "Not Number Pad",	name: "偽ナンバーパッド",	id: "notNumberPad",	questions: ["各ステージでどの数字が点滅した？"] },
	{ original: "Not Password",	name: "偽パスワード",	id: "NotPassword",	questions: ["欠けていた英字は？"] },
	{ original: "Not Perspective Pegs",	name: "偽奥行きペグ",	id: "NotPerspectivePegsModule",	questions: ["各点滅の位置、視点、色は？"] },
	{ original: "Not Piano Keys",	name: "偽鍵盤",	id: "notPianoKeys",	questions: ["表示されたシンボルは？"] },
	{ original: "Not Red Arrows",	name: "偽赤色矢印",	id: "notRedArrowsModule",	questions: ["スタートの数字は？"] },
	{ original: "Not Simaze",	name: "偽サイモンゲーム",	id: "NotSimaze",	questions: ["どの迷路を使用した？", "スタートとゴールの位置は？"] },
	{ original: "Not Text Field",	name: "偽テキストフィールド",	id: "notTextField",	questions: ["初めに9回現れた文字は？", "最初のステージで押した文字は？"] },
	{ original: "Not The Bulb",	name: "偽電球",	id: "notTheBulb",	questions: ["送信された単語は？"] },
	{ original: "Not the Button",	name: "偽ボタン",	id: "NotButton",	questions: ["ライトは何色に光った？"] },
	{ original: "Not The Plunger Button",	name: "偽プランジャーボタン",	id: "notPlungerButtonModule",	questions: ["背景の点滅色は？"] },
	{ original: "Not The Screw",	name: "偽ザ・ネジ",	id: "notTheScrew",	questions: ["始めの位置は何処？"] },
	{ original: "Not Who’s on First",	name: "偽表比較",	id: "NotWhosOnFirst",	questions: ["押した正しいボタンおよび参照したボタンの位置とラベルは？", "ステージ2で計算した数は？"] },
	{ original: "Not Word Search",	name: "偽ワードサーチ",	id: "notWordSearch",	questions: ["どの子音が抜けていた？", "初めに正しく押された文字は？"] },
	{ original: "Not X-Ray",	name: "偽レントゲン",	id: "NotXRayModule",	questions: ["どの表にいる？", "どのボタンがどの方向に向かっている？", "スキャナーの色は？"] },
	{ original: "Not X01",	name: "偽ダーツ",	id: "notX01",	questions: ["セクターの値は？"] },
	{ original: "The Number Game",	name: "The Number Game",	id: "TheNumberGame",	questions: ["最大の数字は？"] },
	{ original: "Numbered Buttons",	name: "番号ボタン",	id: "numberedButtonsModule",	questions: ["正しく押したのはどの数字？"] },
	{ original: "Numbers",	name: "ナンバー",	id: "Numbers",	questions: ["与えられた2つの数字は？"] },
	{ original: "Numpath",	name: "ナンパス",	id: "numpath",	questions: ["数字とその色は？"] },
	{ original: "Object Shows",	name: "オブジェクトショー",	id: "objectShows",	questions: ["表示されていたが優勝できなかった出場者は？"] },
	{ original: "The Octadecayotton",	name: "9次元超立方体",	id: "TheOctadecayotton",	questions: ["スタートボールは？", "各変形の二次変形は？"] },
	{ original: "Odd One Out",	name: "仲間外れ",	id: "OddOneOutModule",	questions: ["押した正しいボタンはどれ？"] },
	{ original: "Off Keys",	name: "音痴鍵盤",	id: "offKeys",	questions: ["表示された記号は？", "間違った音程で鳴っていた鍵盤は？"] },
	{ original: "Off-White Cipher",	name: "乳白色暗号",	id: "offWhiteCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Old AI",	name: "オールドAI",	id: "SCP079",	questions: ["表示された数字のグループ/サブグループは？"] },
	{ original: "Old Fogey",	name: "耄碌爺",	id: "oldFogey",	questions: ["ステータスライトの初期色は？"] },
	{ original: "One Links To All",	name: "One Links To All",	id: "oneLinksToAllModule",	questions: ["初期状態で表示された文章は？"] },
	{ original: "Only Connect",	name: "オンリーコネクト",	id: "OnlyConnectModule",	questions: ["ヒエログリフの位置は何処？"] },
	{ original: "Orange Arrows",	name: "橙色矢印",	id: "orangeArrowsModule",	questions: ["各ステージにおけるディスプレー上の最初の3本の矢印は？"] },
	{ original: "Orange Cipher",	name: "橙色暗号",	id: "orangeCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Order Picking",	name: "注文ピッキング",	id: "OrderPickingModule",	questions: ["各注文の注文ID、製品IDとパレットは？"] },
	{ original: "Ordered Keys",	name: "順番音板",	id: "orderedKeys",	questions: ["各ステージにおける音板の色、ラベル、ラベルの色は？"] },
	{ original: "Orientation Cube",	name: "方向キューブ",	id: "OrientationCube",	questions: ["最初の観測者の位置は？"] },
	{ original: "Orientation Hypercube",	name: "Orientation Hypercube",	id: "OrientationHypercube",	questions: ["最初の観測者の位置は？", "各面の初期状態の色は？"] },
	{ original: "Painting Cube",	name: "色塗りキューブ",	id: "paintingCube",	questions: ["存在しない色は？"] },
	{ original: "Palindromes",	name: "回文",	id: "palindromes",	questions: ["X、Y、Z、画面に表示された数は？"] },
	{ original: "Papa’s Pizzeria",	name: "パパのピザ屋さん",	id: "papasPizzeria",	questions: ["注文番号は？"] },
	{ original: "Parity",	name: "偶奇性",	id: "parity",	questions: ["ディスプレー上の数は？"] },
	{ original: "Partial Derivatives",	name: "偏微分",	id: "partialDerivatives",	questions: ["機能の条件は？", "各ステージにおけるLEDの色は？"] },
	{ original: "Passport Control",	name: "パスポートコントロール",	id: "passportControl",	questions: ["各乗客の有効期限年は？"] },
	{ original: "Password Destroyer",	name: "パスワード破壊",	id: "pwDestroyer",	questions: ["2FAST™の値は？"] },
	{ original: "Pattern Cube",	name: "パターンキューブ",	id: "PatternCubeModule",	questions: ["どのシンボルがハイライトされている？"] },
	{ original: "Pattern Recognition",	name: "パターン識別",	id: "patternRecognition",	questions: ["繰り返されているパターンは？"] },
	{ original: "The Pentabutton",	name: "五角形ボタン",	id: "GSPentabutton",	questions: ["ベースの色は？"] },
	{ original: "Periodic Words",	name: "周期単語",	id: "periodicWordsRB",	questions: ["各ステージで表示された単語は？"] },
	{ original: "Perspective Pegs",	name: "奥行きペグ",	id: "spwizPerspectivePegs",	questions: ["最初の色シーケンスは？"] },
	{ original: "Phosphorescence",	name: "燐光",	id: "Phosphorescence",	questions: ["押したボタンとオフセットは？"] },
	{ original: "Pickup Identification",	name: "アイテム識別",	id: "PickupIdentification",	questions: ["表示されたアイテムは？"] },
	{ original: "Pictionary",	name: "画像ロジック",	id: "pictionaryModule",	questions: ["コードは？"] },
	{ original: "Pie",	name: "パイ",	id: "pieModule",	questions: ["表示された数字は？"] },
	{ original: "Pie Flash",	name: "点滅パイ",	id: "pieFlash",	questions: ["表示された数字は？"] },
	{ original: "Pigpen Cycle",	name: "ピッグペンサイクル",	id: "pigpenCycle",	questions: ["ダイヤルが指していた方向は？", "ダイヤルに書かれていた英字は？"] },
	{ original: "The Pink Button",	name: "桃色ボタン",	id: "PinkButtonModule",	questions: ["表示された単語とその色は？"] },
	{ original: "Pinpoint",	name: "ピンポイント",	id: "pinpoint",	questions: ["与えられた座標とその距離は？"] },
	{ original: "Pixel Cipher",	name: "ピクセル暗号",	id: "pixelcipher",	questions: ["キーワードは？"] },
	{ original: "Placeholder Talk",	name: "プレースホルダートーク",	id: "placeholderTalk",	questions: ["最初のフレーズは？", "2番目のフレーズで計算された値は？"] },
	{ original: "Placement Roulette",	name: "マリオカート",	id: "PlacementRouletteModule",	questions: ["表示されたキャラクター、階級、乗り物は？"] },
	{ original: "Planets",	name: "惑星",	id: "planets",	questions: ["表示された惑星は？", "各ストリップの色は？"] },
	{ original: "Playfair Cycle",	name: "プレイフェアサイクル",	id: "playfairCycle",	questions: ["ダイヤルが指していた方向は？", "ダイヤルに書かれていた英字は？"] },
	{ original: "Pointless Machines",	name: "無意味なマシーン",	id: "PointlessMachines",	questions: ["点滅した色は？"] },
	{ original: "Pokémon Sprite Cipher",	name: "ポケモンスプライト暗号",	id: "PokemonSpriteCipherModule",	questions: ["各スクリーンの文字は？"] },
	{ original: "Polygons",	name: "多角形",	id: "polygons",	questions: ["存在した図形は？"] },
	{ original: "Polyhedral Maze",	name: "多面体迷路",	id: "PolyhedralMazeModule",	questions: ["開始位置は？"] },
	{ original: "Prime Encryption",	name: "素数暗号",	id: "primeEncryption",	questions: ["表示された数字は？"] },
	{ original: "Prison Break",	name: "Prison Break",	id: "prisonBreak",	questions: ["囚人と処理担当者が最初にいた場所は？"] },
	{ original: "Probing",	name: "回路接続",	id: "Probing",	questions: ["各ワイヤで失われている周波数は？"] },
	{ original: "Procedural Maze",	name: "Procedural Maze",	id: "ProceduralMaze",	questions: ["初期シードは？"] },
	{ original: "Purple Arrows",	name: "紫色矢印",	id: "purpleArrowsModule",	questions: ["ターゲットの単語は？"] },
	{ original: "The Purple Button",	name: "紫色ボタン",	id: "PurpleButtonModule",	questions: ["循環シーケンス中の数字は？"] },
	{ original: "Puzzle Identification",	name: "パズル識別",	id: "GSPuzzleIdentification",	questions: ["各パズルの元になったゲームは？", "各パズルの名前と数字は？"] },
	{ original: "Puzzling Hexabuttons",	name: "困惑六角形ボタン",	id: "puzzlingHexabuttons",	questions: ["送信モードで表示された英字は？"] },
	{ original: "Q & A",	name: "Q&A",	id: "q&a",	questions: ["尋ねられた質問は？"] },
	{ original: "Quadrants",	name: "Quadrants",	id: "Quadrants",	questions: ["各ステージでボタンに表示されていたのは？"] },
	{ original: "Quantum Passwords",	name: "量子パスワード",	id: "quantumPasswords",	questions: ["使用された単語は？"] },
	{ original: "Quantum Ternary Converter",	name: "Quantum Ternary Converter",	id: "quTern",	questions: ["数字は？"] },
	{ original: "Quaver",	name: "Quaver",	id: "Quaver",	questions: ["シーケンスの回答は？"] },
	{ original: "Question Mark",	name: "疑問符",	id: "Questionmark",	questions: ["点滅していたシンボルは？"] },
	{ original: "Quick Arithmetic",	name: "瞬速計算",	id: "QuickArithmetic",	questions: ["両方のシーケンス内の数字と色は？"] },
	{ original: "Quintuples",	name: "五重",	id: "quintuples",	questions: ["全てのスロットの数と色は？", "各色の数字はいくつあった？"] },
	{ original: "Quiplash",	name: "クイプラッシュ",	id: "QLModule",	questions: ["表示された数字は？"] },
	{ original: "Quiz Buzz",	name: "クィズバズ",	id: "quizBuzz",	questions: ["ディスプレーの初期状態は？"] },
	{ original: "Qwirkle",	name: "クワークル",	id: "qwirkle",	questions: ["置いたタイルは？"] },
	{ original: "Raiding Temples",	name: "神殿探検",	id: "raidingTemples",	questions: ["共通プールに初めにあった宝石はいくつ？"] },
	{ original: "Railway Cargo Loading",	name: "鉄道貨物積載センター",	id: "RailwayCargoLoading",	questions: ["連結した車両は？", "貨車検索表で当てはまった条件は？ "] },
	{ original: "Rainbow Arrows",	name: "虹色矢印",	id: "ksmRainbowArrows",	questions: ["表示された数字は？"] },
	{ original: "Recolored Switches",	name: "色変えスイッチ",	id: "R4YRecoloredSwitches",	questions: ["LEDの色は？"] },
	{ original: "Recursive Password",	name: "桃色ボタン",	id: "RecursivePassword",	questions: ["不完全なパスワードは？", "パスワードは？"] },
	{ original: "Red Arrows",	name: "赤色矢印",	id: "redArrowsModule",	questions: ["スタートの数字は？"] },
	{ original: "Red Button’t",	name: "偽赤色ボタン",	id: "redbuttont",	questions: ["表示された単語は？"] },
	{ original: "Red Cipher",	name: "赤色暗号",	id: "redCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Red Herring",	name: "レッドヘリング",	id: "RedHerring",	questions: ["最初に点滅した色は？"] },
	{ original: "Reformed Role Reversal",	name: "Reformed Role Reversal",	id: "ReformedRoleReversal",	questions: ["解除条件は？", "ワイヤの色は？"] },
	{ original: "ReGret-B Filtering",	name: "ReGret-B Filtering",	id: "regretbFiltering",	questions: ["使用した計算方法は？"] },
	{ original: "Regular Crazy Talk",	name: "レギュラークレイジートーク",	id: "RegularCrazyTalkModule",	questions: ["解除フレーズに対応して表示された数字は？", "解除フレーズの装飾子は？"] },
	{ original: "Reordered Keys",	name: "順番替え音板",	id: "reorderedKeys",	questions: ["各ステージにおける初期状態の音板の色、ラベル、ラベルの色は？"] },
	{ original: "Retirement",	name: "退職",	id: "retirement",	questions: ["Bobが選ばなかったがオファーされた家は？"] },
	{ original: "Reverse Morse",	name: "逆モールス信号",	id: "reverseMorse",	questions: ["表示されたシンボルとその色は？"] },
	{ original: "Reverse Polish Notation",	name: "逆ポーランド記法",	id: "revPolNot",	questions: ["各ラウンドで使われた文字は？"] },
	{ original: "RGB Encryption",	name: "暗号化RGB",	id: "RGBEncryption",	questions: ["モールス信号と色のシーケンスは？"] },
	{ original: "RGB Maze",	name: "RGB迷路",	id: "rgbMaze",	questions: ["迷路の出口と鍵は？", "各迷路の数字は？"] },
	{ original: "RGB Sequences",	name: "RGBシークエンス",	id: "RGBSequences",	questions: ["各ボタンの色は？"] },
	{ original: "Rhythms",	name: "リズム",	id: "MusicRhythms",	questions: ["色は何だった？"] },
	{ original: "RNG Crystal",	name: "乱数クリスタル",	id: "rngCrystal",	questions: ["タップの位置は？"] },
	{ original: "Robo-Scanner",	name: "Robo-Scanner",	id: "roboScannerModule",	questions: ["空のセルはどこだった？"] },
	{ original: "Robot Programming",	name: "ロボットプログラミング",	id: "robotProgramming",	questions: ["各ロボットの形と色は？"] },
	{ original: "Roger",	name: "ロジャー",	id: "roger",	questions: ["与えられた4桁の数は？"] },
	{ original: "Role Reversal",	name: "Role Reversal",	id: "roleReversal",	questions: ["モジュールを解除するために必要だった数字は？", "内部のワイヤの色は？"] },
	{ original: "RPS Judging",	name: "RPS Judging",	id: "RPSJudging",	questions: ["各チームが勝ち/負け/引き分けになったのはどのラウンド？"] },
	{ original: "The Rule",	name: "ザ・ルール",	id: "theRule",	questions: ["ルール値は？"] },
	{ original: "Rule of Three",	name: "Rule of Three",	id: "RuleOfThreeModule",	questions: ["各サイクルにおいて、各球体の各軸上の位置は？", "頂点の座標は？"] },
	{ original: "S.E.T. Theory",	name: "S.E.T. Theory",	id: "SetTheory",	questions: ["各ステージで表示された方程式は？"] },
	{ original: "Safety Square",	name: "セイフティスクエア",	id: "safetySquare",	questions: ["表示された数字は？", "特殊ルールは？"] },
	{ original: "The Samsung",	name: "The Samsung",	id: "theSamsung",	questions: ["各アプリはどこ？"] },
	{ original: "Saturn",	name: "土星",	id: "saturn",	questions: ["ゴールの位置は？"] },
	{ original: "Sbemail Songs",	name: "Sbemail Songs",	id: "sbemailsongs",	questions: ["各ステージで表示された歌は？"] },
	{ original: "Scavenger Hunt",	name: "宝探し",	id: "scavengerHunt",	questions: ["最初のステージで正しく送信したタイルは？", "最初のステージで赤、緑、青のタイルは何処にあった？"] },
	{ original: "Schlag den Bomb",	name: "シュラグ・デン・ボム",	id: "qSchlagDenBomb",	questions: ["出演者の名前と二人のスコアは？"] },
	{ original: "Scramboozled Eggain",	name: "再卵炒",	id: "ScramboozledEggainModule",	questions: ["暗号化された単語は？"] },
	{ original: "Scrutiny Squares",	name: "正方形精査",	id: "scrutinySquares",	questions: ["最初に表示された正方形で変更されていた設定は？"] },
	{ original: "Sea Shells",	name: "シーシェル",	id: "SeaShells",	questions: ["フレーズは？"] },
	{ original: "Semamorse",	name: "セマモールス",	id: "semamorse",	questions: ["初期値の計算で使われたモールス信号、セマフォア信号は？"] },
	{ original: "The Sequencyclopedia",	name: "The Sequencyclopedia",	id: "TheSequencyclopedia",	questions: ["どのシーケンスが使われた？"] },
	{ original: "Shape Shift",	name: "形状変化",	id: "shapeshift",	questions: ["最初の図形は？"] },
	{ original: "Shapes And Bombs",	name: "形と爆弾",	id: "ShapesBombs",	questions: ["最初の文字は？"] },
	{ original: "Shifted Maze",	name: "シフト迷路",	id: "shiftedMaze",	questions: ["マーカーの色は？"] },
	{ original: "Shifting Maze",	name: "シフト中迷路",	id: "MazeShifting",	questions: ["Seed値は？"] },
	{ original: "Shogi Identification",	name: "将棋識別",	id: "shogiIdentification",	questions: ["表示された駒は？"] },
	{ original: "Sign Language",	name: "手話",	id: "signLanguage",	questions: ["復号した単語は？"] },
	{ original: "Silly Slots",	name: "ヘンテコスロット",	id: "SillySlots",	questions: ["各ステージにおけるスロットは？"] },
	{ original: "Silo Authorization",	name: "シロ認証",	id: "siloAuthorization",	questions: ["暗号化の種類、暗号化されたメッセージ、受信した認証コードは？"] },
	{ original: "Simon Said",	name: "サイモンの残響",	id: "simonSaidModule",	questions: ["最終的に点滅したシーケンスの色は？"] },
	{ original: "Simon Samples",	name: "サイモンの音源",	id: "simonSamples",	questions: ["各ステージで鳴った音は？"] },
	{ original: "Simon Says",	name: "サイモンゲーム",	id: "Simon",	questions: ["最後のシーケンスで点滅した色は？"] },
	{ original: "Simon Scrambles",	name: "サイモンの撹拌",	id: "simonScrambles",	questions: ["点滅した色のシーケンスは？"] },
	{ original: "Simon Screams",	name: "サイモンの絶叫",	id: "SimonScreamsModule",	questions: ["各ステージで使われた点滅する色は？", "どのステージでどのルールが適用された？"] },
	{ original: "Simon Selects",	name: "サイモンの選択",	id: "simonSelectsModule",	questions: ["各ステージで点滅した色は？"] },
	{ original: "Simon Sends",	name: "サイモンの送信",	id: "SimonSendsModule",	questions: ["赤、緑、青の受信した文字は？"] },
	{ original: "Simon Serves",	name: "サイモンの給仕",	id: "simonServes",	questions: ["各コースで点滅した人物は？", "各コースで提供されなかった品物は？"] },
	{ original: "Simon Shapes",	name: "サイモンの形状",	id: "SimonShapesModule",	questions: ["最終的に送信した図形は？"] },
	{ original: "Simon Shouts",	name: "サイモンの叫び",	id: "SimonShoutsModule",	questions: ["各ボタンで点滅した文字は？"] },
	{ original: "Simon Shrieks",	name: "サイモンの悲鳴",	id: "SimonShrieksModule",	questions: ["最終的なシーケンスで、点滅は矢印から時計回りで何番目のスペースにあったか？"] },
	{ original: "Simon Shuffles",	name: "サイモンの交雑",	id: "GSSimonShuffles",	questions: ["各ステージで点滅したボタンは？"] },
	{ original: "Simon Signals",	name: "サイモンの信号",	id: "SimonSignalsModule",	questions: ["各矢印の色、形、方向の回数は？"] },
	{ original: "Simon Simons",	name: "サイモンのサイモン",	id: "simonSimons",	questions: ["どのボタンが点滅した？"] },
	{ original: "Simon Sings",	name: "サイモンの歌唱",	id: "SimonSingsModule",	questions: ["各ステージでどの色の鍵盤が点滅した？"] },
	{ original: "Simon Smiles",	name: "サイモンの笑顔",	id: "SimonSmiles",	questions: ["各ボタンを押した時に再生された音は？"] },
	{ original: "Simon Smothers",	name: "サイモンの隠匿",	id: "simonSmothers",	questions: ["各ステージでどの色と方向が点滅した？"] },
	{ original: "Simon Sounds",	name: "サイモンの響き",	id: "simonSounds",	questions: ["各ステージでどのサンプルボタンが再生された？"] },
	{ original: "Simon Speaks",	name: "サイモンの発話",	id: "SimonSpeaksModule",	questions: ["点滅している吹き出しの属性は？"] },
	{ original: "Simon Stacks",	name: "六角形サイモン",	id: "simonstacks",	questions: ["各ステージで点滅した色は？"] },
	{ original: "Simon Stages",	name: "サイモンステージ",	id: "simonStages",	questions: ["各ステージで点滅した色は？", "各ステージにおけるインジケーターの色は？"] },
	{ original: "Simon States",	name: "サイモンの陳述",	id: "SimonV2",	questions: ["最初の3ステージで点滅した色は？"] },
	{ original: "Simon Stops",	name: "サイモンの停止",	id: "simonStops",	questions: ["出力シーケンスの点滅した色は？"] },
	{ original: "Simon Stores",	name: "サイモンの貯留",	id: "simonStores",	questions: ["最後のシーケンスで点滅した色は？"] },
	{ original: "Simon Subdivides",	name: "サイモンの分割",	id: "simonSubdivides",	questions: ["分割したのは何色のセル？"] },
	{ original: "Simon Supports",	name: "サイモンの支持",	id: "simonSupports",	questions: ["3つのトピックは？"] },
	{ original: "Simon Swizzles",	name: "Simon Swizzles",	id: "simonSwizzles",	questions: ["オンとオフの位置は？", "隠された二進数は？"] },
	{ original: "Simon’s Star",	name: "サイモンの星",	id: "simonsStar",	questions: ["どの色が点滅した？"] },
	{ original: "Simply Simon",	name: "シンプルサイモン",	id: "simplysimon",	questions: ["各ステージで点滅した色は？"] },
	{ original: "Simultaneous Simons",	name: "同時サイモン",	id: "simultaneousSimons",	questions: ["各サイモンでどの色が点滅した？"] },
	{ original: "Skewed Slots",	name: "歪曲スロット",	id: "SkewedSlotsModule",	questions: ["初期状態の数字は？"] },
	{ original: "Skewers",	name: "剣刺し",	id: "Skewers",	questions: ["宝石の色は？"] },
	{ original: "Skyrim",	name: "スカイリム",	id: "skyrim",	questions: ["選択可能だが回答ではない種族、武器、敵、故郷、ドラゴンシャウトはどれ？"] },
	{ original: "Slow Math",	name: "Slow Math",	id: "SlowMathModule",	questions: ["最後の三文字の英字は？"] },
	{ original: "Small Circle",	name: "スモールサークル",	id: "smallCircle",	questions: ["シーケンスはどのくらいずれた？", "最初に違う音がしたのは、どの部分？", "回答はどの色？"] },
	{ original: "Small Talk",	name: "スモールトーク",	id: "SmallTalk",	questions: ["ディスプレーの単語は？"] },
	{ original: "Smash, Marry, Kill",	name: "SMASH・MARRY・KILL",	id: "smashmarrykill",	questions: ["各モジュールが入れられたカテゴリは？"] },
	{ original: "Snooker",	name: "スヌーカー",	id: "snooker",	questions: ["最初に赤いボールはいくつあった？"] },
	{ original: "Snowflakes",	name: "雪の結晶",	id: "snowflakes",	questions: ["表示された雪の結晶は？"] },
	{ original: "Sonic & Knuckles",	name: "ソニック＆ナックルズ",	id: "sonicKnuckles",	questions: ["どのモニターとバドニクが表示された？"] },
	{ original: "Sonic the Hedgehog",	name: "ソニック・ザ・ヘッジホッグ",	id: "sonic",	questions: ["各ディスプレーでどの音が再生された？", "画像は何だった？"] },
	{ original: "Sorting",	name: "並び替え",	id: "sorting",	questions: ["最後の入れ替えに関係していたのはどの位置？"] },
	{ original: "Souvenir",	name: "思い出",	id: "SouvenirModule",	questions: ["他の「思い出」モジュールが最初に質問したのは、何のモジュールについて？"] },
	{ original: "Space Traders",	name: "Space Traders",	id: "space_traders",	questions: ["1隻あたりの税の上限はいくら？"] },
	{ original: "Spelling Bee",	name: "スペリング・ビー",	id: "spellingBee",	questions: ["綴るべき単語は？"] },
	{ original: "The Sphere",	name: "球",	id: "sphere",	questions: ["点滅した色は？"] },
	{ original: "Splitting The Loot",	name: "戦利品分割",	id: "SplittingTheLootModule",	questions: ["最初に色がついたのはどのバッグ？"] },
	{ original: "Spongebob Birthday Identification",	name: "スポンジ・ボブ誕生日カード識別",	id: "spongebobBirthdayIdentification",	questions: ["送信した名前は？"] },
	{ original: "Stability",	name: "Stability",	id: "stabilityModule",	questions: ["点灯したLEDの色は？", "特定用の数字は？"] },
	{ original: "Stable Time Signatures",	name: "安定拍子記号",	id: "StableTimeSignatures",	questions: ["再生された拍子記号は？"] },
	{ original: "Stacked Sequences",	name: "Stacked Sequences",	id: "stackedSequences",	questions: ["シーケンスの長さは？"] },
	{ original: "Stars",	name: "星",	id: "stars",	questions: ["中央にある数字は？"] },
	{ original: "Starstruck",	name: "Starstruck",	id: "starstruck",	questions: ["表示された星は？"] },
	{ original: "State of Aggregation",	name: "元素状態",	id: "stateOfAggregation",	questions: ["どの元素が表示された？"] },
	{ original: "Stellar",	name: "星型十二面体",	id: "stellar",	questions: ["文字は？"] },
	{ original: "Stroop’s Test",	name: "ストループ検査",	id: "stroopsTest",	questions: ["送信したスライドは？"] },
	{ original: "Stupid Slots",	name: "馬鹿スロット",	id: "stupidSlots",	questions: ["各矢印の値は？"] },
	{ original: "Subbly Jubbly",	name: "Subbly Jubbly",	id: "subblyJubbly",	questions: ["置き換えるフレーズは？"] },
	{ original: "Subscribe to Pewdiepie",	name: "ピューディパイの登録",	id: "subscribeToPewdiepie",	questions: ["ピューディパイとTシリーズのチャンネル登録者数は？"] },
	{ original: "Subway",	name: "SUBWAY",	id: "subway",	questions: ["客が注文したパンは？", "客が注文しなかった商品は？"] },
	{ original: "Sugar Skulls",	name: "シュガースカル",	id: "sugarSkulls",	questions: ["表示されたどくろは？"] },
	{ original: "Suits and Colours",	name: "スートと色",	id: "GSSuitsAndColours",	questions: ["各セルの色とスートは？"] },
	{ original: "Superparsing",	name: "超解析",	id: "superparsing",	questions: ["表示された単語は？"] },
	{ original: "SUSadmin",	name: "システム侵入者",	id: "susadmin",	questions: ["インストールしたセキュリティプロコトルは？", "バージョン番号は？"] },
	{ original: "The Switch",	name: "ザ・スイッチ",	id: "BigSwitch",	questions: ["LEDの色は？"] },
	{ original: "Switches",	name: "スイッチ",	id: "switchModule",	questions: ["最初のスイッチの位置は？"] },
	{ original: "Switching Maze",	name: "切り替え迷路",	id: "MazeSwitching",	questions: ["Seed値は？", "初期の迷路の色は？"] },
	{ original: "Symbol Cycle",	name: "シンボルサイクル",	id: "SymbolCycleModule",	questions: ["各画面で循環しているシンボル数は？"] },
	{ original: "Symbolic Coordinates",	name: "シンボル座標",	id: "symbolicCoordinates",	questions: ["各ステージで表示されたシンボルは？"] },
	{ original: "Symbolic Tasha",	name: "シンボルターシャ",	id: "symbolicTasha",	questions: ["ボタンのシンボルは？", "点滅したボタンは？"] },
	{ original: "Synapse Says",	name: "記憶ゲーム",	id: "synapseSays",	questions: ["各ステージで表示された数字は？", "各ステージごとの色の位置は？", "各ステージで点滅した色は？"] },
	{ original: "SYNC-125 [3]",	name: "SYNC-125 [3]",	id: "sync125_3",	questions: [" 各ステージでディスプレーに表示されたものは？"] },
	{ original: "Synonyms",	name: "同義語",	id: "synonyms",	questions: ["表示された数字は？"] },
	{ original: "Sysadmin",	name: "システム管理者",	id: "sysadmin",	questions: ["何のエラーコードを修正した？"] },
	{ original: "TAC",	name: "タック",	id: "TACModule",	questions: ["交換されたカードは？", "手持ちのカードは？"] },
	{ original: "Tap Code",	name: "タップ・コード",	id: "tapCode",	questions: ["受信した単語は？"] },
	{ original: "Tasha Squeals",	name: "ターシャの悲鳴",	id: "tashaSqueals",	questions: ["点滅した色は？"] },
	{ original: "Tasque Managing",	name: "タスク管理",	id: "tasqueManaging",	questions: ["開始位置は？"] },
	{ original: "The Tea Set",	name: "The Tea Set",	id: "GSTeaSet",	questions: ["何の材料がどの順番で表示された？"] },
	{ original: "Technical Keypad",	name: "テクニックキーパッド",	id: "TechnicalKeypad",	questions: ["表示された数字は？"] },
	{ original: "Ten-Button Color Code",	name: "10ボタン色コード",	id: "TenButtonColorCode",	questions: ["各ステージにおけるボタンの初期状態における色は？"] },
	{ original: "Tenpins",	name: "テンピン",	id: "tenpins",	questions: ["スプリットの状態は？"] },
	{ original: "Tetriamonds",	name: "Tetriamonds",	id: "tetriamonds",	questions: ["動いた色の順番は？"] },
	{ original: "Text Field",	name: "テキストフィールド",	id: "TextField",	questions: ["表示された文字は？"] },
	{ original: "Thinking Wires",	name: "思考ワイヤ",	id: "thinkingWiresModule",	questions: ["最初に切るべきワイヤは？", "2つ目の切断可能なワイヤの色は？", "ディスプレーの数字は？"] },
	{ original: "Third Base",	name: "サードベース",	id: "ThirdBase",	questions: ["ディスプレーの単語は？"] },
	{ original: "Thirty Dollar Module",	name: "Thirty Dollar Module",	id: "ThirtyDollarModule",	questions: ["再生された音は？"] },
	{ original: "Tic Tac Toe",	name: "○×ゲーム",	id: "TicTacToeModule",	questions: ["フィールドの初期状態は？"] },
	{ original: "Time Signatures",	name: "拍子記号",	id: "timeSignatures",	questions: ["再生された拍子記号は？"] },
	{ original: "Timezone",	name: "タイムゾーン",	id: "timezone",	questions: ["出発地と目的地は？"] },
	{ original: "Tip Toe",	name: "Tip Toe",	id: "TipToe",	questions: ["9段目と10段目で安全な正方形はどれ？"] },
	{ original: "Topsy Turvy",	name: "トプシー・タービー",	id: "topsyTurvy",	questions: ["最初に表示された単語は？"] },
	{ original: "Touch Transmission",	name: "接触送信",	id: "touchTransmission",	questions: ["送信された単語は？", "点字はどの順で読まれた？"] },
	{ original: "Toxic Crystals",	name: "Toxic Crystals",	id: "ToxicCrystals",	questions: ["{0}を解除したとき、ケースに書かれていた文字は？"] },
	{ original: "Transmitted Morse",	name: "送信モールス",	id: "transmittedMorseModule",	questions: ["受信したメッセージは？"] },
	{ original: "Triamonds",	name: "Triamonds",	id: "triamonds",	questions: ["動いた色の順番は？"] },
	{ original: "Tribal Council",	name: "Tribal Council",	id: "TribalCouncil",	questions: ["北東と南西の名前は？"] },
	{ original: "Tricky Tetris Pieces",	name: "Tricky Tetris Pieces",	id: "TrickyTetrisPieces",	questions: ["最初に押したピースの形は？", "二番目に変換された色のパレットは？"] },
	{ original: "Triple Term",	name: "三単語",	id: "tripleTermModule",	questions: ["パスワードは？"] },
	{ original: "Two Bits",	name: "ツービッツ",	id: "TwoBits",	questions: ["正しい3つのクエリの返答は？"] },
	{ original: "Twodoku",	name: "Twodoku",	id: "TwodokuModule",	questions: ["数字、シンボル、ハイライト表示されているマスは？"] },
	{ original: "UFO Satellites",	name: "UFO Satellites",	id: "UfoSatellites",	questions: ["存在した数字は？"] },
	{ original: "Ultimate Cipher",	name: "究極暗号",	id: "ultimateCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Ultimate Cycle",	name: "究極サイクル",	id: "ultimateCycle",	questions: ["ダイヤルが指していた方向は？", "ダイヤルに書かれていた英字は？"] },
	{ original: "The Ultracube",	name: "極立方体",	id: "TheUltracubeModule",	questions: ["回転方向は？"] },
	{ original: "UltraStores",	name: "極貯留",	id: "UltraStores",	questions: ["回転方向は？"] },
	{ original: "Uncolored Squares",	name: "色無し格子",	id: "UncoloredSquaresModule",	questions: ["最初のステージでは何色を利用した？"] },
	{ original: "Uncolored Switches",	name: "色無しスイッチ",	id: "R4YUncoloredSwitches",	questions: ["最初のスイッチの状態は？", "LEDの色は？"] },
	{ original: "Uncolour Flash",	name: "アンカラーフラッシュ",	id: "uncolourFlash",	questions: ["最初の「YES」シーケンスと「NO」シーケンスは？"] },
	{ original: "Undertunneling",	name: "Undertunneling",	id: "undertunneling",	questions: ["第1フェーズ完了後における迷路内の位置は？"] },
	{ original: "Unfair Cipher",	name: "アンフェア暗号",	id: "unfairCipher",	questions: ["暗号化されたメッセージは？"] },
	{ original: "Unfair’s Cruel Revenge",	name: "アンフェアの残忍逆襲",	id: "unfairsRevengeCruel",	questions: ["解読した指示は？"] },
	{ original: "Unfair’s Revenge",	name: "アンフェアの逆襲",	id: "unfairsRevenge",	questions: ["解読した指示は？"] },
	{ original: "Unicode",	name: "ユニコード",	id: "UnicodeModule",	questions: ["送信したコードは？"] },
	{ original: "UNO!",	name: "UNO",	id: "UNO",	questions: ["初期カードは？"] },
	{ original: "Unordered Keys",	name: "順番無し音板",	id: "unorderedKeys",	questions: ["各ステージにおける音板の色、ラベル、ラベルの色は？"] },
	{ original: "Unown Cipher",	name: "アンノーン暗号",	id: "UnownCipher",	questions: ["送信した文字は？"] },
	{ original: "Unpleasant Squares",	name: "不愉快な正方形",	id: "unpleasantSquares",	questions: ["各正方形の色は？"] },
	{ original: "Updog",	name: "うざいイヌ",	id: "Updog",	questions: ["表示された単語は？", "点滅している色は？"] },
	{ original: "USA Cycle",	name: "USAサイクル",	id: "USACycle",	questions: ["どの州が表示された？"] },
	{ original: "USA Maze",	name: "USA迷路",	id: "USA",	questions: ["出発地はどの州？"] },
	{ original: "V",	name: "V",	id: "V",	questions: ["どの単語が表示された？"] },
	{ original: "Valves",	name: "バルブ",	id: "valves",	questions: ["初期状態は？"] },
	{ original: "Varicolored Squares",	name: "色どり格子",	id: "VaricoloredSquaresModule",	questions: ["最初に押した色は？"] },
	{ original: "Varicolour Flash",	name: "バリカラーフラッシュ",	id: "varicolourFlash",	questions: ["各ゴールの色と単語は？"] },
	{ original: "Variety",	name: "寄せ集め",	id: "VarietyModule",	questions: ["LEDの色は？", "色付きダイヤルや電球のNは？", "数字ディスプレーに表示された数字は？", "英字ディスプレーが形成する単語は？", "タイマーの最大値は？"] },
	{ original: "Vcrcs",	name: "単語識別",	id: "VCRCS",	questions: ["表示された単語は？"] },
	{ original: "Vectors",	name: "ベクトル",	id: "vectorsModule",	questions: ["ベクトルの色は？"] },
	{ original: "Vexillology",	name: "旗章学",	id: "vexillology",	questions: ["旗のポールの色は？"] },
	{ original: "Violet Cipher",	name: "紫色暗号",	id: "violetCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Visual Impairment",	name: "視覚障害",	id: "visual_impairment",	questions: ["押すべき色は？"] },
	{ original: "Walking Cube",	name: "Walking Cube",	id: "WalkingCubeModule",	questions: ["キューブが通ったセルは？"] },
	{ original: "Warning Signs",	name: "警戒標識",	id: "warningSigns",	questions: ["表示された標識は？"] },
	{ original: "WASD",	name: "WASD",	id: "wasdModule",	questions: ["表示された位置は？"] },
	{ original: "Watching Paint Dry",	name: "ペンキの乾燥観察",	id: "watchingPaintDry",	questions: ["ブラシのストローク回数は？"] },
	{ original: "Wavetapping",	name: "ウェーブタッピング",	id: "Wavetapping",	questions: ["最初の2ステージの色は？"] },
	{ original: "The Weakest Link",	name: "The Weakest Link",	id: "TheWeakestLink",	questions: ["退場させられたのは誰？", "あなたと一緒にマネーフェイズに進出したのは誰？", "他の対戦相手のスキルと正しい回答の割合は？"] },
	{ original: "What’s on Second",	name: "色付き表比較",	id: "WhatsOnSecond",	questions: ["各ステージにおけるディスプレーの単語と色は？"] },
	{ original: "White Arrows",	name: "白色矢印",	id: "WhiteArrows",	questions: ["白以外の矢印は？"] },
	{ original: "White Cipher",	name: "白色暗号",	id: "whiteCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Who’s on First",	name: "表比較",	id: "WhosOnFirst",	questions: ["ディスプレーの単語は？"] },
	{ original: "Who’s on Gas",	name: "ガス比較",	id: "whosOnGas",	questions: ["各ステージの第1フェーズで表示されたのは？"] },
	{ original: "Who’s on Morse",	name: "モールス比較",	id: "whosOnMorseModule",	questions: ["各ステージで送信された単語は？"] },
	{ original: "WhoOF",	name: "表比",	id: "whoOF",	questions: ["各ステージにおけるディスプレーは？"] },
	{ original: "The Wire",	name: "ザ・ワイヤ",	id: "wire",	questions: ["ダイヤルの色は？", "表示された数字は？"] },
	{ original: "Wire Ordering",	name: "順序ワイヤ",	id: "kataWireOrdering",	questions: ["ディスプレーの数字と色は？", "ワイヤの色は？"] },
	{ original: "Wire Sequence",	name: "順番ワイヤ",	id: "WireSequence",	questions: ["各色のワイヤは何本あった？"] },
	{ original: "Wolf, Goat, and Cabbage",	name: "川渡り問題",	id: "wolfGoatCabbageModule",	questions: ["どの生物がいた？", "ボートのサイズは？"] },
	{ original: "Word Count",	name: "単語カウント",	id: "wordCount",	questions: ["表示された数字は？"] },
	{ original: "Working Title",	name: "ワーキングタイトル",	id: "workingTitle",	questions: ["ディスプレーに何が表示されていた？"] },
	{ original: "Wumbo",	name: "ウンボ",	id: "wumbo",	questions: ["数字は？"] },
	{ original: "X-Ring",	name: "円形レントゲン",	id: "xring",	questions: ["スキャンされたシンボルは？"] },
	{ original: "X-Rotor",	name: "回転レントゲン",	id: "xrotor",	questions: ["スキャンされたシンボルは？"] },
	{ original: "The Xenocryst",	name: "ゼノクリスト",	id: "GSXenocryst",	questions: ["各点滅の色は？"] },
	{ original: "XmORse Code",	name: "Xモールス信号",	id: "xmorse",	questions: ["ディスプレーの文字は？", "解読した単語は？"] },
	{ original: "xobekuJ ehT",	name: "スクッボクーュジ",	id: "xobekuj",	questions: ["再生された曲は？"] },
	{ original: "XY-Ray",	name: "XYレントゲン",	id: "xyRay",	questions: ["スキャンされた図形は？"] },
	{ original: "Yahtzee",	name: "ヤッツィー",	id: "YahtzeeModule",	questions: ["最初のロールは？"] },
	{ original: "Yellow Arrows",	name: "黄色矢印",	id: "yellowArrowsModule",	questions: ["開始段は？"] },
	{ original: "The Yellow Button",	name: "黄色ボタン",	id: "YellowButtonModule",	questions: ["色は？"] },
	{ original: "Yellow Button’t",	name: "偽黄色ボタン",	id: "yellowbuttont",	questions: ["ファイル名は？"] },
	{ original: "Yellow Cipher",	name: "黄色暗号",	id: "yellowCipher",	questions: ["各ディスプレーの文字は？"] },
	{ original: "Yellow Huffman Cipher",	name: "Yellow Huffman Cipher",	id: "YellowHuffmanCipherModule",	questions: ["各スクリーンの文字は？"] },
	{ original: "Zero, Zero",	name: "ゼロ・ゼロ",	id: "zeroZero",	questions: ["各星の点の色と数字は？", "色付きの四角はどこ？"] },
	{ original: "Zoni",	name: "ゾニ文字",	id: "lgndZoni",	questions: ["単語は？"] },
];